// Code generated by sdkgen-v2. DO NOT EDIT.
package sqlserversdk

import (
	"context"

	sqlserver "github.com/yandex-cloud/go-genproto/yandex/cloud/mdb/sqlserver/v1"
	"github.com/yandex-cloud/go-sdk/v2/pkg/iterator"
	"google.golang.org/grpc"
)

type BackupClientIterator interface {
	Iterator(context.Context, *sqlserver.ListBackupsRequest, ...grpc.CallOption) *iterator.Iterator[*sqlserver.ListBackupsRequest, *sqlserver.Backup]
}

type backupServiceListInternal struct {
	*sqlserver.ListBackupsResponse
}

func (r backupServiceListInternal) Items() []*sqlserver.Backup { return r.ListBackupsResponse.Backups }

func (c backupClient) Iterator(ctx context.Context, req *sqlserver.ListBackupsRequest, opts ...grpc.CallOption) *iterator.Iterator[*sqlserver.ListBackupsRequest, *sqlserver.Backup] {
	return iterator.NewIterator[*sqlserver.ListBackupsRequest, *sqlserver.Backup](ctx, req,
		func(ctx context.Context, req *sqlserver.ListBackupsRequest, opts ...grpc.CallOption) (iterator.PageResponse[*sqlserver.Backup], error) {
			resp, err := c.List(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return backupServiceListInternal{resp}, nil
		})
}
