// Code generated by sdkgen-v2. DO NOT EDIT.
package sqlserversdk

import (
	"context"

	sqlserver "github.com/yandex-cloud/go-genproto/yandex/cloud/mdb/sqlserver/v1"
	operation "github.com/yandex-cloud/go-genproto/yandex/cloud/operation"
	"github.com/yandex-cloud/go-sdk/v2/pkg/iterator"
	"google.golang.org/grpc"
)

type ClusterClientIterator interface {
	Iterator(context.Context, *sqlserver.ListClustersRequest, ...grpc.CallOption) *iterator.Iterator[*sqlserver.ListClustersRequest, *sqlserver.Cluster]
	LogsIterator(context.Context, *sqlserver.ListClusterLogsRequest, ...grpc.CallOption) *iterator.Iterator[*sqlserver.ListClusterLogsRequest, *sqlserver.LogRecord]
	OperationsIterator(context.Context, *sqlserver.ListClusterOperationsRequest, ...grpc.CallOption) *iterator.Iterator[*sqlserver.ListClusterOperationsRequest, *operation.Operation]
	BackupsIterator(context.Context, *sqlserver.ListClusterBackupsRequest, ...grpc.CallOption) *iterator.Iterator[*sqlserver.ListClusterBackupsRequest, *sqlserver.Backup]
	HostsIterator(context.Context, *sqlserver.ListClusterHostsRequest, ...grpc.CallOption) *iterator.Iterator[*sqlserver.ListClusterHostsRequest, *sqlserver.Host]
}

type clusterServiceListInternal struct {
	*sqlserver.ListClustersResponse
}

func (r clusterServiceListInternal) Items() []*sqlserver.Cluster {
	return r.ListClustersResponse.Clusters
}

func (c clusterClient) Iterator(ctx context.Context, req *sqlserver.ListClustersRequest, opts ...grpc.CallOption) *iterator.Iterator[*sqlserver.ListClustersRequest, *sqlserver.Cluster] {
	return iterator.NewIterator[*sqlserver.ListClustersRequest, *sqlserver.Cluster](ctx, req,
		func(ctx context.Context, req *sqlserver.ListClustersRequest, opts ...grpc.CallOption) (iterator.PageResponse[*sqlserver.Cluster], error) {
			resp, err := c.List(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return clusterServiceListInternal{resp}, nil
		})
}

type clusterServiceListLogsInternal struct {
	*sqlserver.ListClusterLogsResponse
}

func (r clusterServiceListLogsInternal) Items() []*sqlserver.LogRecord {
	return r.ListClusterLogsResponse.Logs
}

func (c clusterClient) LogsIterator(ctx context.Context, req *sqlserver.ListClusterLogsRequest, opts ...grpc.CallOption) *iterator.Iterator[*sqlserver.ListClusterLogsRequest, *sqlserver.LogRecord] {
	return iterator.NewIterator[*sqlserver.ListClusterLogsRequest, *sqlserver.LogRecord](ctx, req,
		func(ctx context.Context, req *sqlserver.ListClusterLogsRequest, opts ...grpc.CallOption) (iterator.PageResponse[*sqlserver.LogRecord], error) {
			resp, err := c.ListLogs(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return clusterServiceListLogsInternal{resp}, nil
		})
}

type clusterServiceListOperationsInternal struct {
	*sqlserver.ListClusterOperationsResponse
}

func (r clusterServiceListOperationsInternal) Items() []*operation.Operation {
	return r.ListClusterOperationsResponse.Operations
}

func (c clusterClient) OperationsIterator(ctx context.Context, req *sqlserver.ListClusterOperationsRequest, opts ...grpc.CallOption) *iterator.Iterator[*sqlserver.ListClusterOperationsRequest, *operation.Operation] {
	return iterator.NewIterator[*sqlserver.ListClusterOperationsRequest, *operation.Operation](ctx, req,
		func(ctx context.Context, req *sqlserver.ListClusterOperationsRequest, opts ...grpc.CallOption) (iterator.PageResponse[*operation.Operation], error) {
			resp, err := c.ListOperations(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return clusterServiceListOperationsInternal{resp}, nil
		})
}

type clusterServiceListBackupsInternal struct {
	*sqlserver.ListClusterBackupsResponse
}

func (r clusterServiceListBackupsInternal) Items() []*sqlserver.Backup {
	return r.ListClusterBackupsResponse.Backups
}

func (c clusterClient) BackupsIterator(ctx context.Context, req *sqlserver.ListClusterBackupsRequest, opts ...grpc.CallOption) *iterator.Iterator[*sqlserver.ListClusterBackupsRequest, *sqlserver.Backup] {
	return iterator.NewIterator[*sqlserver.ListClusterBackupsRequest, *sqlserver.Backup](ctx, req,
		func(ctx context.Context, req *sqlserver.ListClusterBackupsRequest, opts ...grpc.CallOption) (iterator.PageResponse[*sqlserver.Backup], error) {
			resp, err := c.ListBackups(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return clusterServiceListBackupsInternal{resp}, nil
		})
}

type clusterServiceListHostsInternal struct {
	*sqlserver.ListClusterHostsResponse
}

func (r clusterServiceListHostsInternal) Items() []*sqlserver.Host {
	return r.ListClusterHostsResponse.Hosts
}

func (c clusterClient) HostsIterator(ctx context.Context, req *sqlserver.ListClusterHostsRequest, opts ...grpc.CallOption) *iterator.Iterator[*sqlserver.ListClusterHostsRequest, *sqlserver.Host] {
	return iterator.NewIterator[*sqlserver.ListClusterHostsRequest, *sqlserver.Host](ctx, req,
		func(ctx context.Context, req *sqlserver.ListClusterHostsRequest, opts ...grpc.CallOption) (iterator.PageResponse[*sqlserver.Host], error) {
			resp, err := c.ListHosts(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return clusterServiceListHostsInternal{resp}, nil
		})
}
