// Code generated by sdkgen-v2. DO NOT EDIT.
package sqlserversdk

import (
	"context"

	sqlserver "github.com/yandex-cloud/go-genproto/yandex/cloud/mdb/sqlserver/v1"
	operation "github.com/yandex-cloud/go-genproto/yandex/cloud/operation"
	sdkop "github.com/yandex-cloud/go-sdk/v2/pkg/operation"
	"github.com/yandex-cloud/go-sdk/v2/pkg/transport"
	"google.golang.org/grpc"
	proto "google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// ClusterClient provides methods for managing Cluster resources of Yandex.Cloud Sqlserver.
type ClusterClient interface {
	ClusterClientIterator
	Get(context.Context, *sqlserver.GetClusterRequest, ...grpc.CallOption) (*sqlserver.Cluster, error)
	List(context.Context, *sqlserver.ListClustersRequest, ...grpc.CallOption) (*sqlserver.ListClustersResponse, error)
	Create(context.Context, *sqlserver.CreateClusterRequest, ...grpc.CallOption) (*ClusterCreateOperation, error)
	Update(context.Context, *sqlserver.UpdateClusterRequest, ...grpc.CallOption) (*ClusterUpdateOperation, error)
	Delete(context.Context, *sqlserver.DeleteClusterRequest, ...grpc.CallOption) (*ClusterDeleteOperation, error)
	Start(context.Context, *sqlserver.StartClusterRequest, ...grpc.CallOption) (*ClusterStartOperation, error)
	Stop(context.Context, *sqlserver.StopClusterRequest, ...grpc.CallOption) (*ClusterStopOperation, error)
	Move(context.Context, *sqlserver.MoveClusterRequest, ...grpc.CallOption) (*ClusterMoveOperation, error)
	Backup(context.Context, *sqlserver.BackupClusterRequest, ...grpc.CallOption) (*ClusterBackupOperation, error)
	Restore(context.Context, *sqlserver.RestoreClusterRequest, ...grpc.CallOption) (*ClusterRestoreOperation, error)
	StartFailover(context.Context, *sqlserver.StartClusterFailoverRequest, ...grpc.CallOption) (*ClusterStartFailoverOperation, error)
	ListLogs(context.Context, *sqlserver.ListClusterLogsRequest, ...grpc.CallOption) (*sqlserver.ListClusterLogsResponse, error)
	ListOperations(context.Context, *sqlserver.ListClusterOperationsRequest, ...grpc.CallOption) (*sqlserver.ListClusterOperationsResponse, error)
	ListBackups(context.Context, *sqlserver.ListClusterBackupsRequest, ...grpc.CallOption) (*sqlserver.ListClusterBackupsResponse, error)
	ListHosts(context.Context, *sqlserver.ListClusterHostsRequest, ...grpc.CallOption) (*sqlserver.ListClusterHostsResponse, error)
	UpdateHosts(context.Context, *sqlserver.UpdateClusterHostsRequest, ...grpc.CallOption) (*ClusterUpdateHostsOperation, error)
}

var _ ClusterClient = clusterClient{}

type clusterClient struct {
	connector transport.Connector
}

// NewClusterClient returns ClusterClient implementation.
func NewClusterClient(connector transport.Connector) ClusterClient {
	return clusterClient{connector}
}

// Get is an operation of Yandex.Cloud Sqlserver Cluster service.
func (c clusterClient) Get(ctx context.Context, in *sqlserver.GetClusterRequest, opts ...grpc.CallOption) (*sqlserver.Cluster, error) {
	connection, err := c.connector.GetConnection(ctx, ClusterGet, opts...)
	if err != nil {
		return nil, err
	}
	return sqlserver.NewClusterServiceClient(connection).Get(ctx, in, opts...)
}

// List is an operation of Yandex.Cloud Sqlserver Cluster service.
func (c clusterClient) List(ctx context.Context, in *sqlserver.ListClustersRequest, opts ...grpc.CallOption) (*sqlserver.ListClustersResponse, error) {
	connection, err := c.connector.GetConnection(ctx, ClusterList, opts...)
	if err != nil {
		return nil, err
	}
	return sqlserver.NewClusterServiceClient(connection).List(ctx, in, opts...)
}

// ClusterCreateOperation is used to monitor the state of Create operations.
type ClusterCreateOperation struct {
	sdkop.Operation
}

// Metadata retrieves the operation metadata.
func (o *ClusterCreateOperation) Metadata() *sqlserver.CreateClusterMetadata {
	return o.Operation.Metadata().(*sqlserver.CreateClusterMetadata)
}

// Response retrieves the operation response.
func (o *ClusterCreateOperation) Response() *sqlserver.Cluster {
	return o.Operation.Response().(*sqlserver.Cluster)
}

// Wait polls the operation until it's done.
func (o *ClusterCreateOperation) Wait(ctx context.Context, opts ...grpc.CallOption) (*sqlserver.Cluster, error) {
	abstract, err := o.Operation.Wait(ctx, opts...)
	response, _ := abstract.(*sqlserver.Cluster)
	return response, err
}

// WaitInterval polls the operation until it's done with custom interval.
func (o *ClusterCreateOperation) WaitInterval(ctx context.Context, pollInterval sdkop.PollIntervalFunc, opts ...grpc.CallOption) (*sqlserver.Cluster, error) {
	abstract, err := o.Operation.WaitInterval(ctx, pollInterval, opts...)
	response, _ := abstract.(*sqlserver.Cluster)
	return response, err
}

// Create is an operation of Yandex.Cloud Sqlserver Cluster service.
// It returns an object which should be used to monitor the operation state.
func (c clusterClient) Create(ctx context.Context, in *sqlserver.CreateClusterRequest, opts ...grpc.CallOption) (*ClusterCreateOperation, error) {
	connection, err := c.connector.GetConnection(ctx, ClusterCreate, opts...)
	if err != nil {
		return nil, err
	}
	pb, err := sqlserver.NewClusterServiceClient(connection).Create(ctx, in, opts...)
	if err != nil {
		return nil, err
	}
	op, err := sdkop.NewOperation(pb, &sdkop.Concretization{
		Poll: c.pollOperation,
		GetResourceID: func(metadata proto.Message) string {
			return metadata.(*sqlserver.CreateClusterMetadata).GetClusterId()
		},
		MetadataType: (*sqlserver.CreateClusterMetadata)(nil),
		ResponseType: (*sqlserver.Cluster)(nil),
	})
	if err != nil {
		return nil, err
	}
	return &ClusterCreateOperation{*op}, nil
}

// ClusterUpdateOperation is used to monitor the state of Update operations.
type ClusterUpdateOperation struct {
	sdkop.Operation
}

// Metadata retrieves the operation metadata.
func (o *ClusterUpdateOperation) Metadata() *sqlserver.UpdateClusterMetadata {
	return o.Operation.Metadata().(*sqlserver.UpdateClusterMetadata)
}

// Response retrieves the operation response.
func (o *ClusterUpdateOperation) Response() *sqlserver.Cluster {
	return o.Operation.Response().(*sqlserver.Cluster)
}

// Wait polls the operation until it's done.
func (o *ClusterUpdateOperation) Wait(ctx context.Context, opts ...grpc.CallOption) (*sqlserver.Cluster, error) {
	abstract, err := o.Operation.Wait(ctx, opts...)
	response, _ := abstract.(*sqlserver.Cluster)
	return response, err
}

// WaitInterval polls the operation until it's done with custom interval.
func (o *ClusterUpdateOperation) WaitInterval(ctx context.Context, pollInterval sdkop.PollIntervalFunc, opts ...grpc.CallOption) (*sqlserver.Cluster, error) {
	abstract, err := o.Operation.WaitInterval(ctx, pollInterval, opts...)
	response, _ := abstract.(*sqlserver.Cluster)
	return response, err
}

// Update is an operation of Yandex.Cloud Sqlserver Cluster service.
// It returns an object which should be used to monitor the operation state.
func (c clusterClient) Update(ctx context.Context, in *sqlserver.UpdateClusterRequest, opts ...grpc.CallOption) (*ClusterUpdateOperation, error) {
	connection, err := c.connector.GetConnection(ctx, ClusterUpdate, opts...)
	if err != nil {
		return nil, err
	}
	pb, err := sqlserver.NewClusterServiceClient(connection).Update(ctx, in, opts...)
	if err != nil {
		return nil, err
	}
	op, err := sdkop.NewOperation(pb, &sdkop.Concretization{
		Poll: c.pollOperation,
		GetResourceID: func(metadata proto.Message) string {
			return metadata.(*sqlserver.UpdateClusterMetadata).GetClusterId()
		},
		MetadataType: (*sqlserver.UpdateClusterMetadata)(nil),
		ResponseType: (*sqlserver.Cluster)(nil),
	})
	if err != nil {
		return nil, err
	}
	return &ClusterUpdateOperation{*op}, nil
}

// ClusterDeleteOperation is used to monitor the state of Delete operations.
type ClusterDeleteOperation struct {
	sdkop.Operation
}

// Metadata retrieves the operation metadata.
func (o *ClusterDeleteOperation) Metadata() *sqlserver.DeleteClusterMetadata {
	return o.Operation.Metadata().(*sqlserver.DeleteClusterMetadata)
}

// Response retrieves the operation response.
func (o *ClusterDeleteOperation) Response() *emptypb.Empty {
	return o.Operation.Response().(*emptypb.Empty)
}

// Wait polls the operation until it's done.
func (o *ClusterDeleteOperation) Wait(ctx context.Context, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	abstract, err := o.Operation.Wait(ctx, opts...)
	response, _ := abstract.(*emptypb.Empty)
	return response, err
}

// WaitInterval polls the operation until it's done with custom interval.
func (o *ClusterDeleteOperation) WaitInterval(ctx context.Context, pollInterval sdkop.PollIntervalFunc, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	abstract, err := o.Operation.WaitInterval(ctx, pollInterval, opts...)
	response, _ := abstract.(*emptypb.Empty)
	return response, err
}

// Delete is an operation of Yandex.Cloud Sqlserver Cluster service.
// It returns an object which should be used to monitor the operation state.
func (c clusterClient) Delete(ctx context.Context, in *sqlserver.DeleteClusterRequest, opts ...grpc.CallOption) (*ClusterDeleteOperation, error) {
	connection, err := c.connector.GetConnection(ctx, ClusterDelete, opts...)
	if err != nil {
		return nil, err
	}
	pb, err := sqlserver.NewClusterServiceClient(connection).Delete(ctx, in, opts...)
	if err != nil {
		return nil, err
	}
	op, err := sdkop.NewOperation(pb, &sdkop.Concretization{
		Poll: c.pollOperation,
		GetResourceID: func(metadata proto.Message) string {
			return metadata.(*sqlserver.DeleteClusterMetadata).GetClusterId()
		},
		MetadataType: (*sqlserver.DeleteClusterMetadata)(nil),
		ResponseType: (*emptypb.Empty)(nil),
	})
	if err != nil {
		return nil, err
	}
	return &ClusterDeleteOperation{*op}, nil
}

// ClusterStartOperation is used to monitor the state of Start operations.
type ClusterStartOperation struct {
	sdkop.Operation
}

// Metadata retrieves the operation metadata.
func (o *ClusterStartOperation) Metadata() *sqlserver.StartClusterMetadata {
	return o.Operation.Metadata().(*sqlserver.StartClusterMetadata)
}

// Response retrieves the operation response.
func (o *ClusterStartOperation) Response() *sqlserver.Cluster {
	return o.Operation.Response().(*sqlserver.Cluster)
}

// Wait polls the operation until it's done.
func (o *ClusterStartOperation) Wait(ctx context.Context, opts ...grpc.CallOption) (*sqlserver.Cluster, error) {
	abstract, err := o.Operation.Wait(ctx, opts...)
	response, _ := abstract.(*sqlserver.Cluster)
	return response, err
}

// WaitInterval polls the operation until it's done with custom interval.
func (o *ClusterStartOperation) WaitInterval(ctx context.Context, pollInterval sdkop.PollIntervalFunc, opts ...grpc.CallOption) (*sqlserver.Cluster, error) {
	abstract, err := o.Operation.WaitInterval(ctx, pollInterval, opts...)
	response, _ := abstract.(*sqlserver.Cluster)
	return response, err
}

// Start is an operation of Yandex.Cloud Sqlserver Cluster service.
// It returns an object which should be used to monitor the operation state.
func (c clusterClient) Start(ctx context.Context, in *sqlserver.StartClusterRequest, opts ...grpc.CallOption) (*ClusterStartOperation, error) {
	connection, err := c.connector.GetConnection(ctx, ClusterStart, opts...)
	if err != nil {
		return nil, err
	}
	pb, err := sqlserver.NewClusterServiceClient(connection).Start(ctx, in, opts...)
	if err != nil {
		return nil, err
	}
	op, err := sdkop.NewOperation(pb, &sdkop.Concretization{
		Poll: c.pollOperation,
		GetResourceID: func(metadata proto.Message) string {
			return metadata.(*sqlserver.StartClusterMetadata).GetClusterId()
		},
		MetadataType: (*sqlserver.StartClusterMetadata)(nil),
		ResponseType: (*sqlserver.Cluster)(nil),
	})
	if err != nil {
		return nil, err
	}
	return &ClusterStartOperation{*op}, nil
}

// ClusterStopOperation is used to monitor the state of Stop operations.
type ClusterStopOperation struct {
	sdkop.Operation
}

// Metadata retrieves the operation metadata.
func (o *ClusterStopOperation) Metadata() *sqlserver.StopClusterMetadata {
	return o.Operation.Metadata().(*sqlserver.StopClusterMetadata)
}

// Response retrieves the operation response.
func (o *ClusterStopOperation) Response() *sqlserver.Cluster {
	return o.Operation.Response().(*sqlserver.Cluster)
}

// Wait polls the operation until it's done.
func (o *ClusterStopOperation) Wait(ctx context.Context, opts ...grpc.CallOption) (*sqlserver.Cluster, error) {
	abstract, err := o.Operation.Wait(ctx, opts...)
	response, _ := abstract.(*sqlserver.Cluster)
	return response, err
}

// WaitInterval polls the operation until it's done with custom interval.
func (o *ClusterStopOperation) WaitInterval(ctx context.Context, pollInterval sdkop.PollIntervalFunc, opts ...grpc.CallOption) (*sqlserver.Cluster, error) {
	abstract, err := o.Operation.WaitInterval(ctx, pollInterval, opts...)
	response, _ := abstract.(*sqlserver.Cluster)
	return response, err
}

// Stop is an operation of Yandex.Cloud Sqlserver Cluster service.
// It returns an object which should be used to monitor the operation state.
func (c clusterClient) Stop(ctx context.Context, in *sqlserver.StopClusterRequest, opts ...grpc.CallOption) (*ClusterStopOperation, error) {
	connection, err := c.connector.GetConnection(ctx, ClusterStop, opts...)
	if err != nil {
		return nil, err
	}
	pb, err := sqlserver.NewClusterServiceClient(connection).Stop(ctx, in, opts...)
	if err != nil {
		return nil, err
	}
	op, err := sdkop.NewOperation(pb, &sdkop.Concretization{
		Poll: c.pollOperation,
		GetResourceID: func(metadata proto.Message) string {
			return metadata.(*sqlserver.StopClusterMetadata).GetClusterId()
		},
		MetadataType: (*sqlserver.StopClusterMetadata)(nil),
		ResponseType: (*sqlserver.Cluster)(nil),
	})
	if err != nil {
		return nil, err
	}
	return &ClusterStopOperation{*op}, nil
}

// ClusterMoveOperation is used to monitor the state of Move operations.
type ClusterMoveOperation struct {
	sdkop.Operation
}

// Metadata retrieves the operation metadata.
func (o *ClusterMoveOperation) Metadata() *sqlserver.MoveClusterMetadata {
	return o.Operation.Metadata().(*sqlserver.MoveClusterMetadata)
}

// Response retrieves the operation response.
func (o *ClusterMoveOperation) Response() *sqlserver.Cluster {
	return o.Operation.Response().(*sqlserver.Cluster)
}

// Wait polls the operation until it's done.
func (o *ClusterMoveOperation) Wait(ctx context.Context, opts ...grpc.CallOption) (*sqlserver.Cluster, error) {
	abstract, err := o.Operation.Wait(ctx, opts...)
	response, _ := abstract.(*sqlserver.Cluster)
	return response, err
}

// WaitInterval polls the operation until it's done with custom interval.
func (o *ClusterMoveOperation) WaitInterval(ctx context.Context, pollInterval sdkop.PollIntervalFunc, opts ...grpc.CallOption) (*sqlserver.Cluster, error) {
	abstract, err := o.Operation.WaitInterval(ctx, pollInterval, opts...)
	response, _ := abstract.(*sqlserver.Cluster)
	return response, err
}

// Move is an operation of Yandex.Cloud Sqlserver Cluster service.
// It returns an object which should be used to monitor the operation state.
func (c clusterClient) Move(ctx context.Context, in *sqlserver.MoveClusterRequest, opts ...grpc.CallOption) (*ClusterMoveOperation, error) {
	connection, err := c.connector.GetConnection(ctx, ClusterMove, opts...)
	if err != nil {
		return nil, err
	}
	pb, err := sqlserver.NewClusterServiceClient(connection).Move(ctx, in, opts...)
	if err != nil {
		return nil, err
	}
	op, err := sdkop.NewOperation(pb, &sdkop.Concretization{
		Poll: c.pollOperation,
		GetResourceID: func(metadata proto.Message) string {
			return metadata.(*sqlserver.MoveClusterMetadata).GetClusterId()
		},
		MetadataType: (*sqlserver.MoveClusterMetadata)(nil),
		ResponseType: (*sqlserver.Cluster)(nil),
	})
	if err != nil {
		return nil, err
	}
	return &ClusterMoveOperation{*op}, nil
}

// ClusterBackupOperation is used to monitor the state of Backup operations.
type ClusterBackupOperation struct {
	sdkop.Operation
}

// Metadata retrieves the operation metadata.
func (o *ClusterBackupOperation) Metadata() *sqlserver.BackupClusterMetadata {
	return o.Operation.Metadata().(*sqlserver.BackupClusterMetadata)
}

// Response retrieves the operation response.
func (o *ClusterBackupOperation) Response() *sqlserver.Cluster {
	return o.Operation.Response().(*sqlserver.Cluster)
}

// Wait polls the operation until it's done.
func (o *ClusterBackupOperation) Wait(ctx context.Context, opts ...grpc.CallOption) (*sqlserver.Cluster, error) {
	abstract, err := o.Operation.Wait(ctx, opts...)
	response, _ := abstract.(*sqlserver.Cluster)
	return response, err
}

// WaitInterval polls the operation until it's done with custom interval.
func (o *ClusterBackupOperation) WaitInterval(ctx context.Context, pollInterval sdkop.PollIntervalFunc, opts ...grpc.CallOption) (*sqlserver.Cluster, error) {
	abstract, err := o.Operation.WaitInterval(ctx, pollInterval, opts...)
	response, _ := abstract.(*sqlserver.Cluster)
	return response, err
}

// Backup is an operation of Yandex.Cloud Sqlserver Cluster service.
// It returns an object which should be used to monitor the operation state.
func (c clusterClient) Backup(ctx context.Context, in *sqlserver.BackupClusterRequest, opts ...grpc.CallOption) (*ClusterBackupOperation, error) {
	connection, err := c.connector.GetConnection(ctx, ClusterBackup, opts...)
	if err != nil {
		return nil, err
	}
	pb, err := sqlserver.NewClusterServiceClient(connection).Backup(ctx, in, opts...)
	if err != nil {
		return nil, err
	}
	op, err := sdkop.NewOperation(pb, &sdkop.Concretization{
		Poll: c.pollOperation,
		GetResourceID: func(metadata proto.Message) string {
			return metadata.(*sqlserver.BackupClusterMetadata).GetClusterId()
		},
		MetadataType: (*sqlserver.BackupClusterMetadata)(nil),
		ResponseType: (*sqlserver.Cluster)(nil),
	})
	if err != nil {
		return nil, err
	}
	return &ClusterBackupOperation{*op}, nil
}

// ClusterRestoreOperation is used to monitor the state of Restore operations.
type ClusterRestoreOperation struct {
	sdkop.Operation
}

// Metadata retrieves the operation metadata.
func (o *ClusterRestoreOperation) Metadata() *sqlserver.RestoreClusterMetadata {
	return o.Operation.Metadata().(*sqlserver.RestoreClusterMetadata)
}

// Response retrieves the operation response.
func (o *ClusterRestoreOperation) Response() *sqlserver.Cluster {
	return o.Operation.Response().(*sqlserver.Cluster)
}

// Wait polls the operation until it's done.
func (o *ClusterRestoreOperation) Wait(ctx context.Context, opts ...grpc.CallOption) (*sqlserver.Cluster, error) {
	abstract, err := o.Operation.Wait(ctx, opts...)
	response, _ := abstract.(*sqlserver.Cluster)
	return response, err
}

// WaitInterval polls the operation until it's done with custom interval.
func (o *ClusterRestoreOperation) WaitInterval(ctx context.Context, pollInterval sdkop.PollIntervalFunc, opts ...grpc.CallOption) (*sqlserver.Cluster, error) {
	abstract, err := o.Operation.WaitInterval(ctx, pollInterval, opts...)
	response, _ := abstract.(*sqlserver.Cluster)
	return response, err
}

// Restore is an operation of Yandex.Cloud Sqlserver Cluster service.
// It returns an object which should be used to monitor the operation state.
func (c clusterClient) Restore(ctx context.Context, in *sqlserver.RestoreClusterRequest, opts ...grpc.CallOption) (*ClusterRestoreOperation, error) {
	connection, err := c.connector.GetConnection(ctx, ClusterRestore, opts...)
	if err != nil {
		return nil, err
	}
	pb, err := sqlserver.NewClusterServiceClient(connection).Restore(ctx, in, opts...)
	if err != nil {
		return nil, err
	}
	op, err := sdkop.NewOperation(pb, &sdkop.Concretization{
		Poll: c.pollOperation,
		GetResourceID: func(metadata proto.Message) string {
			return metadata.(*sqlserver.RestoreClusterMetadata).GetClusterId()
		},
		MetadataType: (*sqlserver.RestoreClusterMetadata)(nil),
		ResponseType: (*sqlserver.Cluster)(nil),
	})
	if err != nil {
		return nil, err
	}
	return &ClusterRestoreOperation{*op}, nil
}

// ClusterStartFailoverOperation is used to monitor the state of StartFailover operations.
type ClusterStartFailoverOperation struct {
	sdkop.Operation
}

// Metadata retrieves the operation metadata.
func (o *ClusterStartFailoverOperation) Metadata() *sqlserver.StartClusterFailoverMetadata {
	return o.Operation.Metadata().(*sqlserver.StartClusterFailoverMetadata)
}

// Response retrieves the operation response.
func (o *ClusterStartFailoverOperation) Response() *sqlserver.Cluster {
	return o.Operation.Response().(*sqlserver.Cluster)
}

// Wait polls the operation until it's done.
func (o *ClusterStartFailoverOperation) Wait(ctx context.Context, opts ...grpc.CallOption) (*sqlserver.Cluster, error) {
	abstract, err := o.Operation.Wait(ctx, opts...)
	response, _ := abstract.(*sqlserver.Cluster)
	return response, err
}

// WaitInterval polls the operation until it's done with custom interval.
func (o *ClusterStartFailoverOperation) WaitInterval(ctx context.Context, pollInterval sdkop.PollIntervalFunc, opts ...grpc.CallOption) (*sqlserver.Cluster, error) {
	abstract, err := o.Operation.WaitInterval(ctx, pollInterval, opts...)
	response, _ := abstract.(*sqlserver.Cluster)
	return response, err
}

// StartFailover is an operation of Yandex.Cloud Sqlserver Cluster service.
// It returns an object which should be used to monitor the operation state.
func (c clusterClient) StartFailover(ctx context.Context, in *sqlserver.StartClusterFailoverRequest, opts ...grpc.CallOption) (*ClusterStartFailoverOperation, error) {
	connection, err := c.connector.GetConnection(ctx, ClusterStartFailover, opts...)
	if err != nil {
		return nil, err
	}
	pb, err := sqlserver.NewClusterServiceClient(connection).StartFailover(ctx, in, opts...)
	if err != nil {
		return nil, err
	}
	op, err := sdkop.NewOperation(pb, &sdkop.Concretization{
		Poll: c.pollOperation,
		GetResourceID: func(metadata proto.Message) string {
			return metadata.(*sqlserver.StartClusterFailoverMetadata).GetClusterId()
		},
		MetadataType: (*sqlserver.StartClusterFailoverMetadata)(nil),
		ResponseType: (*sqlserver.Cluster)(nil),
	})
	if err != nil {
		return nil, err
	}
	return &ClusterStartFailoverOperation{*op}, nil
}

// ListLogs is an operation of Yandex.Cloud Sqlserver Cluster service.
func (c clusterClient) ListLogs(ctx context.Context, in *sqlserver.ListClusterLogsRequest, opts ...grpc.CallOption) (*sqlserver.ListClusterLogsResponse, error) {
	connection, err := c.connector.GetConnection(ctx, ClusterListLogs, opts...)
	if err != nil {
		return nil, err
	}
	return sqlserver.NewClusterServiceClient(connection).ListLogs(ctx, in, opts...)
}

// ListOperations is an operation of Yandex.Cloud Sqlserver Cluster service.
func (c clusterClient) ListOperations(ctx context.Context, in *sqlserver.ListClusterOperationsRequest, opts ...grpc.CallOption) (*sqlserver.ListClusterOperationsResponse, error) {
	connection, err := c.connector.GetConnection(ctx, ClusterListOperations, opts...)
	if err != nil {
		return nil, err
	}
	return sqlserver.NewClusterServiceClient(connection).ListOperations(ctx, in, opts...)
}

// ListBackups is an operation of Yandex.Cloud Sqlserver Cluster service.
func (c clusterClient) ListBackups(ctx context.Context, in *sqlserver.ListClusterBackupsRequest, opts ...grpc.CallOption) (*sqlserver.ListClusterBackupsResponse, error) {
	connection, err := c.connector.GetConnection(ctx, ClusterListBackups, opts...)
	if err != nil {
		return nil, err
	}
	return sqlserver.NewClusterServiceClient(connection).ListBackups(ctx, in, opts...)
}

// ListHosts is an operation of Yandex.Cloud Sqlserver Cluster service.
func (c clusterClient) ListHosts(ctx context.Context, in *sqlserver.ListClusterHostsRequest, opts ...grpc.CallOption) (*sqlserver.ListClusterHostsResponse, error) {
	connection, err := c.connector.GetConnection(ctx, ClusterListHosts, opts...)
	if err != nil {
		return nil, err
	}
	return sqlserver.NewClusterServiceClient(connection).ListHosts(ctx, in, opts...)
}

// ClusterUpdateHostsOperation is used to monitor the state of UpdateHosts operations.
type ClusterUpdateHostsOperation struct {
	sdkop.Operation
}

// Metadata retrieves the operation metadata.
func (o *ClusterUpdateHostsOperation) Metadata() *sqlserver.UpdateClusterHostsMetadata {
	return o.Operation.Metadata().(*sqlserver.UpdateClusterHostsMetadata)
}

// Response retrieves the operation response.
func (o *ClusterUpdateHostsOperation) Response() *emptypb.Empty {
	return o.Operation.Response().(*emptypb.Empty)
}

// Wait polls the operation until it's done.
func (o *ClusterUpdateHostsOperation) Wait(ctx context.Context, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	abstract, err := o.Operation.Wait(ctx, opts...)
	response, _ := abstract.(*emptypb.Empty)
	return response, err
}

// WaitInterval polls the operation until it's done with custom interval.
func (o *ClusterUpdateHostsOperation) WaitInterval(ctx context.Context, pollInterval sdkop.PollIntervalFunc, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	abstract, err := o.Operation.WaitInterval(ctx, pollInterval, opts...)
	response, _ := abstract.(*emptypb.Empty)
	return response, err
}

// UpdateHosts is an operation of Yandex.Cloud Sqlserver Cluster service.
// It returns an object which should be used to monitor the operation state.
func (c clusterClient) UpdateHosts(ctx context.Context, in *sqlserver.UpdateClusterHostsRequest, opts ...grpc.CallOption) (*ClusterUpdateHostsOperation, error) {
	connection, err := c.connector.GetConnection(ctx, ClusterUpdateHosts, opts...)
	if err != nil {
		return nil, err
	}
	pb, err := sqlserver.NewClusterServiceClient(connection).UpdateHosts(ctx, in, opts...)
	if err != nil {
		return nil, err
	}
	op, err := sdkop.NewOperation(pb, &sdkop.Concretization{
		Poll: c.pollOperation,
		GetResourceID: func(metadata proto.Message) string {
			return metadata.(*sqlserver.UpdateClusterHostsMetadata).GetClusterId()
		},
		MetadataType: (*sqlserver.UpdateClusterHostsMetadata)(nil),
		ResponseType: (*emptypb.Empty)(nil),
	})
	if err != nil {
		return nil, err
	}
	return &ClusterUpdateHostsOperation{*op}, nil
}

// pollOperation returns the current state of the polled operation.
func (c clusterClient) pollOperation(ctx context.Context, operationId string, opts ...grpc.CallOption) (sdkop.YCOperation, error) {
	connection, err := c.connector.GetConnection(ctx, ClusterOperationPoller, opts...)
	if err != nil {
		return nil, err
	}
	return operation.NewOperationServiceClient(connection).Get(ctx, &operation.GetOperationRequest{OperationId: operationId}, opts...)
}

var (
	ClusterGet             = protoreflect.FullName("yandex.cloud.mdb.sqlserver.v1.ClusterService.Get")
	ClusterList            = protoreflect.FullName("yandex.cloud.mdb.sqlserver.v1.ClusterService.List")
	ClusterCreate          = protoreflect.FullName("yandex.cloud.mdb.sqlserver.v1.ClusterService.Create")
	ClusterUpdate          = protoreflect.FullName("yandex.cloud.mdb.sqlserver.v1.ClusterService.Update")
	ClusterDelete          = protoreflect.FullName("yandex.cloud.mdb.sqlserver.v1.ClusterService.Delete")
	ClusterStart           = protoreflect.FullName("yandex.cloud.mdb.sqlserver.v1.ClusterService.Start")
	ClusterStop            = protoreflect.FullName("yandex.cloud.mdb.sqlserver.v1.ClusterService.Stop")
	ClusterMove            = protoreflect.FullName("yandex.cloud.mdb.sqlserver.v1.ClusterService.Move")
	ClusterBackup          = protoreflect.FullName("yandex.cloud.mdb.sqlserver.v1.ClusterService.Backup")
	ClusterRestore         = protoreflect.FullName("yandex.cloud.mdb.sqlserver.v1.ClusterService.Restore")
	ClusterStartFailover   = protoreflect.FullName("yandex.cloud.mdb.sqlserver.v1.ClusterService.StartFailover")
	ClusterListLogs        = protoreflect.FullName("yandex.cloud.mdb.sqlserver.v1.ClusterService.ListLogs")
	ClusterListOperations  = protoreflect.FullName("yandex.cloud.mdb.sqlserver.v1.ClusterService.ListOperations")
	ClusterListBackups     = protoreflect.FullName("yandex.cloud.mdb.sqlserver.v1.ClusterService.ListBackups")
	ClusterListHosts       = protoreflect.FullName("yandex.cloud.mdb.sqlserver.v1.ClusterService.ListHosts")
	ClusterUpdateHosts     = protoreflect.FullName("yandex.cloud.mdb.sqlserver.v1.ClusterService.UpdateHosts")
	ClusterOperationPoller = protoreflect.FullName("yandex.cloud.operation.OperationService.Get")
)
