// Code generated by sdkgen-v2. DO NOT EDIT.
package sqlserversdk

import (
	"context"

	sqlserver "github.com/yandex-cloud/go-genproto/yandex/cloud/mdb/sqlserver/v1"
	"github.com/yandex-cloud/go-sdk/v2/pkg/iterator"
	"google.golang.org/grpc"
)

type DatabaseClientIterator interface {
	Iterator(context.Context, *sqlserver.ListDatabasesRequest, ...grpc.CallOption) *iterator.Iterator[*sqlserver.ListDatabasesRequest, *sqlserver.Database]
}

type databaseServiceListInternal struct {
	*sqlserver.ListDatabasesResponse
}

func (r databaseServiceListInternal) Items() []*sqlserver.Database {
	return r.ListDatabasesResponse.Databases
}

func (c databaseClient) Iterator(ctx context.Context, req *sqlserver.ListDatabasesRequest, opts ...grpc.CallOption) *iterator.Iterator[*sqlserver.ListDatabasesRequest, *sqlserver.Database] {
	return iterator.NewIterator[*sqlserver.ListDatabasesRequest, *sqlserver.Database](ctx, req,
		func(ctx context.Context, req *sqlserver.ListDatabasesRequest, opts ...grpc.CallOption) (iterator.PageResponse[*sqlserver.Database], error) {
			resp, err := c.List(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return databaseServiceListInternal{resp}, nil
		})
}
