// Code generated by sdkgen-v2. DO NOT EDIT.
package sqlserversdk

import (
	"context"

	sqlserver "github.com/yandex-cloud/go-genproto/yandex/cloud/mdb/sqlserver/v1"
	"github.com/yandex-cloud/go-sdk/v2/pkg/sdkresolvers"
)

type databaseResolver struct {
	client DatabaseClient
	sdkresolvers.BaseNameResolver
}

func DatabaseResolver(name string, client DatabaseClient, opts ...sdkresolvers.ResolveOption) sdkresolvers.Resolver {
	return &databaseResolver{
		client:           client,
		BaseNameResolver: sdkresolvers.NewBaseNameResolver(name, "Database", opts...),
	}
}

func (r *databaseResolver) Run(ctx context.Context) error {
	err := r.EnsureClusterID()
	if err != nil {
		return err
	}

	resp := r.client.Iterator(ctx, &sqlserver.ListDatabasesRequest{
		ClusterId: r.ClusterID(),

		PageSize: sdkresolvers.DefaultResolverPageSize,
	})
	return r.FindName(resp.TakeAll())
}
