// Code generated by sdkgen-v2. DO NOT EDIT.
package sqlserversdk

import (
	"context"

	sqlserver "github.com/yandex-cloud/go-genproto/yandex/cloud/mdb/sqlserver/v1"
	"github.com/yandex-cloud/go-sdk/v2/pkg/iterator"
	"google.golang.org/grpc"
)

type ResourcePresetClientIterator interface {
	Iterator(context.Context, *sqlserver.ListResourcePresetsRequest, ...grpc.CallOption) *iterator.Iterator[*sqlserver.ListResourcePresetsRequest, *sqlserver.ResourcePreset]
}

type resourcePresetServiceListInternal struct {
	*sqlserver.ListResourcePresetsResponse
}

func (r resourcePresetServiceListInternal) Items() []*sqlserver.ResourcePreset {
	return r.ListResourcePresetsResponse.ResourcePresets
}

func (c resourcePresetClient) Iterator(ctx context.Context, req *sqlserver.ListResourcePresetsRequest, opts ...grpc.CallOption) *iterator.Iterator[*sqlserver.ListResourcePresetsRequest, *sqlserver.ResourcePreset] {
	return iterator.NewIterator[*sqlserver.ListResourcePresetsRequest, *sqlserver.ResourcePreset](ctx, req,
		func(ctx context.Context, req *sqlserver.ListResourcePresetsRequest, opts ...grpc.CallOption) (iterator.PageResponse[*sqlserver.ResourcePreset], error) {
			resp, err := c.List(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return resourcePresetServiceListInternal{resp}, nil
		})
}
