// Code generated by sdkgen-v2. DO NOT EDIT.
package sqlserversdk

import (
	"context"

	sqlserver "github.com/yandex-cloud/go-genproto/yandex/cloud/mdb/sqlserver/v1"
	"github.com/yandex-cloud/go-sdk/v2/pkg/iterator"
	"google.golang.org/grpc"
)

type UserClientIterator interface {
	Iterator(context.Context, *sqlserver.ListUsersRequest, ...grpc.CallOption) *iterator.Iterator[*sqlserver.ListUsersRequest, *sqlserver.User]
}

type userServiceListInternal struct {
	*sqlserver.ListUsersResponse
}

func (r userServiceListInternal) Items() []*sqlserver.User { return r.ListUsersResponse.Users }

func (c userClient) Iterator(ctx context.Context, req *sqlserver.ListUsersRequest, opts ...grpc.CallOption) *iterator.Iterator[*sqlserver.ListUsersRequest, *sqlserver.User] {
	return iterator.NewIterator[*sqlserver.ListUsersRequest, *sqlserver.User](ctx, req,
		func(ctx context.Context, req *sqlserver.ListUsersRequest, opts ...grpc.CallOption) (iterator.PageResponse[*sqlserver.User], error) {
			resp, err := c.List(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return userServiceListInternal{resp}, nil
		})
}
