version: "2"

issues:
  exclude-rules:
    - linters: [staticcheck]
      text: "grpc.Dial is deprecated: use NewClient instead.  Will be supported throughout 1.x."
    - linters: [staticcheck]
      text: "grpc.DialContext is deprecated: use NewClient instead.  Will be supported throughout 1.x."
    - linters: [staticcheck]
      text: "grpc.WithBlock is deprecated: this DialOption is not supported by NewClient. Will be supported throughout 1.x."