// Code generated by sdkgen-v2. DO NOT EDIT.
package backupsdk

import (
	"context"

	backup "github.com/yandex-cloud/go-genproto/yandex/cloud/backup/v1"
	"github.com/yandex-cloud/go-sdk/v2/pkg/iterator"
	"google.golang.org/grpc"
)

type BackupClientIterator interface {
	Iterator(context.Context, *backup.ListBackupsRequest, ...grpc.CallOption) *iterator.Iterator[*backup.ListBackupsRequest, *backup.Backup]
}

type backupServiceListInternal struct {
	*backup.ListBackupsResponse
}

func (r backupServiceListInternal) Items() []*backup.Backup { return r.ListBackupsResponse.Backups }

func (c backupClient) Iterator(ctx context.Context, req *backup.ListBackupsRequest, opts ...grpc.CallOption) *iterator.Iterator[*backup.ListBackupsRequest, *backup.Backup] {
	return iterator.NewIterator[*backup.ListBackupsRequest, *backup.Backup](ctx, req,
		func(ctx context.Context, req *backup.ListBackupsRequest, opts ...grpc.CallOption) (iterator.PageResponse[*backup.Backup], error) {
			resp, err := c.List(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return backupServiceListInternal{resp}, nil
		})
}
