// Code generated by sdkgen-v2. DO NOT EDIT.
package loadtestingsdk

import (
	"context"

	loadtesting "github.com/yandex-cloud/go-genproto/yandex/cloud/loadtesting/v1"
	"github.com/yandex-cloud/go-sdk/v2/pkg/transport"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// ResourcePresetClient provides methods for managing ResourcePreset resources of Yandex.Cloud Loadtesting.
type ResourcePresetClient interface {
	Get(context.Context, *loadtesting.GetResourcePresetRequest, ...grpc.CallOption) (*loadtesting.ResourcePreset, error)
	List(context.Context, *loadtesting.ListResourcePresetsRequest, ...grpc.CallOption) (*loadtesting.ListResourcePresetsResponse, error)
}

var _ ResourcePresetClient = resourcePresetClient{}

type resourcePresetClient struct {
	connector transport.Connector
}

// NewResourcePresetClient returns ResourcePresetClient implementation.
func NewResourcePresetClient(connector transport.Connector) ResourcePresetClient {
	return resourcePresetClient{connector}
}

// Get is an operation of Yandex.Cloud Loadtesting ResourcePreset service.
func (c resourcePresetClient) Get(ctx context.Context, in *loadtesting.GetResourcePresetRequest, opts ...grpc.CallOption) (*loadtesting.ResourcePreset, error) {
	connection, err := c.connector.GetConnection(ctx, ResourcePresetGet, opts...)
	if err != nil {
		return nil, err
	}
	return loadtesting.NewResourcePresetServiceClient(connection).Get(ctx, in, opts...)
}

// List is an operation of Yandex.Cloud Loadtesting ResourcePreset service.
func (c resourcePresetClient) List(ctx context.Context, in *loadtesting.ListResourcePresetsRequest, opts ...grpc.CallOption) (*loadtesting.ListResourcePresetsResponse, error) {
	connection, err := c.connector.GetConnection(ctx, ResourcePresetList, opts...)
	if err != nil {
		return nil, err
	}
	return loadtesting.NewResourcePresetServiceClient(connection).List(ctx, in, opts...)
}

var (
	ResourcePresetGet  = protoreflect.FullName("yandex.cloud.loadtesting.v1.ResourcePresetService.Get")
	ResourcePresetList = protoreflect.FullName("yandex.cloud.loadtesting.v1.ResourcePresetService.List")
)
