// Code generated by sdkgen-v2. DO NOT EDIT.
package translatesdk

import (
	"context"

	translate "github.com/yandex-cloud/go-genproto/yandex/cloud/ai/translate/v2"
	"github.com/yandex-cloud/go-sdk/v2/pkg/sdkresolvers"
)

type translationLanguagesResolver struct {
	client TranslationClient
	sdkresolvers.BaseNameResolver
}

func TranslationLanguagesResolver(name string, client TranslationClient, opts ...sdkresolvers.ResolveOption) sdkresolvers.Resolver {
	return &translationLanguagesResolver{
		client:           client,
		BaseNameResolver: sdkresolvers.NewBaseNameResolver(name, "TranslationLanguages", opts...),
	}
}

func (r *translationLanguagesResolver) Run(ctx context.Context) error {
	err := r.EnsureFolderID()
	if err != nil {
		return err
	}

	resp := r.client.LanguagesIterator(ctx, &translate.ListLanguagesRequest{
		FolderId: r.FolderID(),
	})
	return r.FindName(resp.TakeAll())
}
