// Code generated by sdkgen-v2. DO NOT EDIT.
package translatesdk

import (
	"context"

	translate "github.com/yandex-cloud/go-genproto/yandex/cloud/ai/translate/v2"
	"github.com/yandex-cloud/go-sdk/v2/pkg/iterator"
	"google.golang.org/grpc"
)

type TranslationClientIterator interface {
	LanguagesIterator(context.Context, *translate.ListLanguagesRequest, ...grpc.CallOption) *iterator.SimpleIterator[*translate.ListLanguagesRequest, *translate.Language]
}

type translationServiceListLanguagesInternal struct {
	*translate.ListLanguagesResponse
}

func (r translationServiceListLanguagesInternal) Items() []*translate.Language {
	return r.ListLanguagesResponse.Languages
}

func (c translationClient) LanguagesIterator(ctx context.Context, req *translate.ListLanguagesRequest, opts ...grpc.CallOption) *iterator.SimpleIterator[*translate.ListLanguagesRequest, *translate.Language] {
	return iterator.NewSimpleIterator[*translate.ListLanguagesRequest, *translate.Language](ctx, req,
		func(ctx context.Context, req *translate.ListLanguagesRequest, opts ...grpc.CallOption) (iterator.SimpleResponse[*translate.Language], error) {
			resp, err := c.ListLanguages(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return translationServiceListLanguagesInternal{resp}, nil
		})
}
