// Code generated by sdkgen-v2. DO NOT EDIT.
package extendsdk

import (
	"context"

	extend "github.com/yandex-cloud/go-genproto/yandex/cloud/baremetal/v2/extend"
	operation "github.com/yandex-cloud/go-genproto/yandex/cloud/operation"
	"github.com/yandex-cloud/go-sdk/v2/pkg/iterator"
	"google.golang.org/grpc"
)

type StacklandClusterClientIterator interface {
	StacklandClustersIterator(context.Context, *extend.ListStacklandClustersRequest, ...grpc.CallOption) *iterator.Iterator[*extend.ListStacklandClustersRequest, *extend.StacklandCluster]
	StacklandClusterOperationsIterator(context.Context, *extend.ListStacklandClusterOperationsRequest, ...grpc.CallOption) *iterator.Iterator[*extend.ListStacklandClusterOperationsRequest, *operation.Operation]
	StacklandVersionsIterator(context.Context, *extend.ListStacklandVersionsRequest, ...grpc.CallOption) *iterator.Iterator[*extend.ListStacklandVersionsRequest, *extend.StacklandVersion]
}

type stacklandClusterServiceListStacklandClustersInternal struct {
	*extend.ListStacklandClustersResponse
}

func (r stacklandClusterServiceListStacklandClustersInternal) Items() []*extend.StacklandCluster {
	return r.ListStacklandClustersResponse.Clusters
}

func (c stacklandClusterClient) StacklandClustersIterator(ctx context.Context, req *extend.ListStacklandClustersRequest, opts ...grpc.CallOption) *iterator.Iterator[*extend.ListStacklandClustersRequest, *extend.StacklandCluster] {
	return iterator.NewIterator[*extend.ListStacklandClustersRequest, *extend.StacklandCluster](ctx, req,
		func(ctx context.Context, req *extend.ListStacklandClustersRequest, opts ...grpc.CallOption) (iterator.PageResponse[*extend.StacklandCluster], error) {
			resp, err := c.ListStacklandClusters(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return stacklandClusterServiceListStacklandClustersInternal{resp}, nil
		})
}

type stacklandClusterServiceListStacklandClusterOperationsInternal struct {
	*extend.ListStacklandClusterOperationsResponse
}

func (r stacklandClusterServiceListStacklandClusterOperationsInternal) Items() []*operation.Operation {
	return r.ListStacklandClusterOperationsResponse.Operations
}

func (c stacklandClusterClient) StacklandClusterOperationsIterator(ctx context.Context, req *extend.ListStacklandClusterOperationsRequest, opts ...grpc.CallOption) *iterator.Iterator[*extend.ListStacklandClusterOperationsRequest, *operation.Operation] {
	return iterator.NewIterator[*extend.ListStacklandClusterOperationsRequest, *operation.Operation](ctx, req,
		func(ctx context.Context, req *extend.ListStacklandClusterOperationsRequest, opts ...grpc.CallOption) (iterator.PageResponse[*operation.Operation], error) {
			resp, err := c.ListStacklandClusterOperations(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return stacklandClusterServiceListStacklandClusterOperationsInternal{resp}, nil
		})
}

type stacklandClusterServiceListStacklandVersionsInternal struct {
	*extend.ListStacklandVersionsResponse
}

func (r stacklandClusterServiceListStacklandVersionsInternal) Items() []*extend.StacklandVersion {
	return r.ListStacklandVersionsResponse.StacklandVersions
}

func (c stacklandClusterClient) StacklandVersionsIterator(ctx context.Context, req *extend.ListStacklandVersionsRequest, opts ...grpc.CallOption) *iterator.Iterator[*extend.ListStacklandVersionsRequest, *extend.StacklandVersion] {
	return iterator.NewIterator[*extend.ListStacklandVersionsRequest, *extend.StacklandVersion](ctx, req,
		func(ctx context.Context, req *extend.ListStacklandVersionsRequest, opts ...grpc.CallOption) (iterator.PageResponse[*extend.StacklandVersion], error) {
			resp, err := c.ListStacklandVersions(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return stacklandClusterServiceListStacklandVersionsInternal{resp}, nil
		})
}
