// Code generated by sdkgen-v2. DO NOT EDIT.
package mcpgatewaysdk

import (
	"context"

	mcpgateway "github.com/yandex-cloud/go-genproto/yandex/cloud/serverless/mcpgateway/v1"
	"github.com/yandex-cloud/go-sdk/v2/pkg/sdkresolvers"
)

type mcpGatewayResolver struct {
	client McpGatewayClient
	sdkresolvers.BaseNameResolver
}

func McpGatewayResolver(name string, client McpGatewayClient, opts ...sdkresolvers.ResolveOption) sdkresolvers.Resolver {
	return &mcpGatewayResolver{
		client:           client,
		BaseNameResolver: sdkresolvers.NewBaseNameResolver(name, "McpGateway", opts...),
	}
}

func (r *mcpGatewayResolver) Run(ctx context.Context) error {
	err := r.EnsureFolderID()
	if err != nil {
		return err
	}

	resp := r.client.Iterator(ctx, &mcpgateway.ListMcpGatewayRequest{
		FolderId: r.FolderID(),
		Filter:   sdkresolvers.CreateResolverFilter("name", r.Name),
		PageSize: sdkresolvers.DefaultResolverPageSize,
	})
	return r.FindName(resp.TakeAll())
}
