// Code generated by sdkgen-v2. DO NOT EDIT.
package mcpgatewaysdk

import (
	"context"

	access "github.com/yandex-cloud/go-genproto/yandex/cloud/access"
	operation "github.com/yandex-cloud/go-genproto/yandex/cloud/operation"
	mcpgateway "github.com/yandex-cloud/go-genproto/yandex/cloud/serverless/mcpgateway/v1"
	"github.com/yandex-cloud/go-sdk/v2/pkg/iterator"
	"google.golang.org/grpc"
)

type McpGatewayClientIterator interface {
	Iterator(context.Context, *mcpgateway.ListMcpGatewayRequest, ...grpc.CallOption) *iterator.Iterator[*mcpgateway.ListMcpGatewayRequest, *mcpgateway.McpGatewayPreview]
	OperationsIterator(context.Context, *mcpgateway.ListOperationsRequest, ...grpc.CallOption) *iterator.Iterator[*mcpgateway.ListOperationsRequest, *operation.Operation]
	AccessBindingsIterator(context.Context, *access.ListAccessBindingsRequest, ...grpc.CallOption) *iterator.Iterator[*access.ListAccessBindingsRequest, *access.AccessBinding]
}

type mcpGatewayServiceListInternal struct {
	*mcpgateway.ListMcpGatewayResponse
}

func (r mcpGatewayServiceListInternal) Items() []*mcpgateway.McpGatewayPreview {
	return r.ListMcpGatewayResponse.Gateways
}

func (c mcpGatewayClient) Iterator(ctx context.Context, req *mcpgateway.ListMcpGatewayRequest, opts ...grpc.CallOption) *iterator.Iterator[*mcpgateway.ListMcpGatewayRequest, *mcpgateway.McpGatewayPreview] {
	return iterator.NewIterator[*mcpgateway.ListMcpGatewayRequest, *mcpgateway.McpGatewayPreview](ctx, req,
		func(ctx context.Context, req *mcpgateway.ListMcpGatewayRequest, opts ...grpc.CallOption) (iterator.PageResponse[*mcpgateway.McpGatewayPreview], error) {
			resp, err := c.List(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return mcpGatewayServiceListInternal{resp}, nil
		})
}

type mcpGatewayServiceListOperationsInternal struct {
	*mcpgateway.ListOperationsResponse
}

func (r mcpGatewayServiceListOperationsInternal) Items() []*operation.Operation {
	return r.ListOperationsResponse.Operations
}

func (c mcpGatewayClient) OperationsIterator(ctx context.Context, req *mcpgateway.ListOperationsRequest, opts ...grpc.CallOption) *iterator.Iterator[*mcpgateway.ListOperationsRequest, *operation.Operation] {
	return iterator.NewIterator[*mcpgateway.ListOperationsRequest, *operation.Operation](ctx, req,
		func(ctx context.Context, req *mcpgateway.ListOperationsRequest, opts ...grpc.CallOption) (iterator.PageResponse[*operation.Operation], error) {
			resp, err := c.ListOperations(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return mcpGatewayServiceListOperationsInternal{resp}, nil
		})
}

type mcpGatewayServiceListAccessBindingsInternal struct {
	*access.ListAccessBindingsResponse
}

func (r mcpGatewayServiceListAccessBindingsInternal) Items() []*access.AccessBinding {
	return r.ListAccessBindingsResponse.AccessBindings
}

func (c mcpGatewayClient) AccessBindingsIterator(ctx context.Context, req *access.ListAccessBindingsRequest, opts ...grpc.CallOption) *iterator.Iterator[*access.ListAccessBindingsRequest, *access.AccessBinding] {
	return iterator.NewIterator[*access.ListAccessBindingsRequest, *access.AccessBinding](ctx, req,
		func(ctx context.Context, req *access.ListAccessBindingsRequest, opts ...grpc.CallOption) (iterator.PageResponse[*access.AccessBinding], error) {
			resp, err := c.ListAccessBindings(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return mcpGatewayServiceListAccessBindingsInternal{resp}, nil
		})
}
