// Code generated by sdkgen-v2. DO NOT EDIT.
package mdbproxysdk

import (
	"context"

	mdbproxy "github.com/yandex-cloud/go-genproto/yandex/cloud/serverless/mdbproxy/v1"
	"github.com/yandex-cloud/go-sdk/v2/pkg/sdkresolvers"
)

type proxyResolver struct {
	client ProxyClient
	sdkresolvers.BaseNameResolver
}

func ProxyResolver(name string, client ProxyClient, opts ...sdkresolvers.ResolveOption) sdkresolvers.Resolver {
	return &proxyResolver{
		client:           client,
		BaseNameResolver: sdkresolvers.NewBaseNameResolver(name, "Proxy", opts...),
	}
}

func (r *proxyResolver) Run(ctx context.Context) error {
	err := r.EnsureFolderID()
	if err != nil {
		return err
	}

	resp := r.client.Iterator(ctx, &mdbproxy.ListProxyRequest{
		FolderId: r.FolderID(),
		Filter:   sdkresolvers.CreateResolverFilter("name", r.Name),
		PageSize: sdkresolvers.DefaultResolverPageSize,
	})
	return r.FindName(resp.TakeAll())
}
