// Code generated by sdkgen-v2. DO NOT EDIT.
package monitoringsdk

import (
	"context"

	monitoring "github.com/yandex-cloud/go-genproto/yandex/cloud/monitoring/v2"
	"github.com/yandex-cloud/go-sdk/v2/pkg/transport"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// MetricsDataClient provides methods for managing MetricsData resources of Yandex.Cloud Monitoring.
type MetricsDataClient interface {
	Read(context.Context, *monitoring.ReadMetricsDataRequest, ...grpc.CallOption) (*monitoring.ReadMetricsDataResponse, error)
	Write(context.Context, *monitoring.WriteMetricsDataRequest, ...grpc.CallOption) (*monitoring.WriteMetricsDataResponse, error)
}

var _ MetricsDataClient = metricsDataClient{}

type metricsDataClient struct {
	connector transport.Connector
}

// NewMetricsDataClient returns MetricsDataClient implementation.
func NewMetricsDataClient(connector transport.Connector) MetricsDataClient {
	return metricsDataClient{connector}
}

// Read is an operation of Yandex.Cloud Monitoring MetricsData service.
func (c metricsDataClient) Read(ctx context.Context, in *monitoring.ReadMetricsDataRequest, opts ...grpc.CallOption) (*monitoring.ReadMetricsDataResponse, error) {
	connection, err := c.connector.GetConnection(ctx, MetricsDataRead, opts...)
	if err != nil {
		return nil, err
	}
	return monitoring.NewMetricsDataServiceClient(connection).Read(ctx, in, opts...)
}

// Write is an operation of Yandex.Cloud Monitoring MetricsData service.
func (c metricsDataClient) Write(ctx context.Context, in *monitoring.WriteMetricsDataRequest, opts ...grpc.CallOption) (*monitoring.WriteMetricsDataResponse, error) {
	connection, err := c.connector.GetConnection(ctx, MetricsDataWrite, opts...)
	if err != nil {
		return nil, err
	}
	return monitoring.NewMetricsDataServiceClient(connection).Write(ctx, in, opts...)
}

var (
	MetricsDataRead  = protoreflect.FullName("yandex.cloud.monitoring.v2.MetricsDataService.Read")
	MetricsDataWrite = protoreflect.FullName("yandex.cloud.monitoring.v2.MetricsDataService.Write")
)
