// Code generated by sdkgen-v2. DO NOT EDIT.
package agentsdk

import (
	"context"

	agent "github.com/yandex-cloud/go-genproto/yandex/cloud/loadtesting/agent/v1"
	"github.com/yandex-cloud/go-sdk/v2/pkg/transport"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// MonitoringClient provides methods for managing Monitoring resources of Yandex.Cloud Agent.
type MonitoringClient interface {
	AddMetric(context.Context, *agent.AddMetricRequest, ...grpc.CallOption) (*agent.AddMetricResponse, error)
}

var _ MonitoringClient = monitoringClient{}

type monitoringClient struct {
	connector transport.Connector
}

// NewMonitoringClient returns MonitoringClient implementation.
func NewMonitoringClient(connector transport.Connector) MonitoringClient {
	return monitoringClient{connector}
}

// AddMetric is an operation of Yandex.Cloud Agent Monitoring service.
func (c monitoringClient) AddMetric(ctx context.Context, in *agent.AddMetricRequest, opts ...grpc.CallOption) (*agent.AddMetricResponse, error) {
	connection, err := c.connector.GetConnection(ctx, MonitoringAddMetric, opts...)
	if err != nil {
		return nil, err
	}
	return agent.NewMonitoringServiceClient(connection).AddMetric(ctx, in, opts...)
}

var (
	MonitoringAddMetric = protoreflect.FullName("yandex.cloud.loadtesting.agent.v1.MonitoringService.AddMetric")
)
