// Code generated by sdkgen-v2. DO NOT EDIT.
package agentsdk

import (
	"context"

	agent "github.com/yandex-cloud/go-genproto/yandex/cloud/loadtesting/agent/v1"
	"github.com/yandex-cloud/go-sdk/v2/pkg/transport"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// TrailClient provides methods for managing Trail resources of Yandex.Cloud Agent.
type TrailClient interface {
	Create(context.Context, *agent.CreateTrailRequest, ...grpc.CallOption) (*agent.CreateTrailResponse, error)
}

var _ TrailClient = trailClient{}

type trailClient struct {
	connector transport.Connector
}

// NewTrailClient returns TrailClient implementation.
func NewTrailClient(connector transport.Connector) TrailClient {
	return trailClient{connector}
}

// Create is an operation of Yandex.Cloud Agent Trail service.
func (c trailClient) Create(ctx context.Context, in *agent.CreateTrailRequest, opts ...grpc.CallOption) (*agent.CreateTrailResponse, error) {
	connection, err := c.connector.GetConnection(ctx, TrailCreate, opts...)
	if err != nil {
		return nil, err
	}
	return agent.NewTrailServiceClient(connection).Create(ctx, in, opts...)
}

var (
	TrailCreate = protoreflect.FullName("yandex.cloud.loadtesting.agent.v1.TrailService.Create")
)
