// Code generated by sdkgen-v2. DO NOT EDIT.
package visionsdk

import (
	"context"

	vision "github.com/yandex-cloud/go-genproto/yandex/cloud/ai/vision/v2"
	"github.com/yandex-cloud/go-sdk/v2/pkg/transport"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// ImageClassifierClient provides methods for managing ImageClassifier resources of Yandex.Cloud Vision.
type ImageClassifierClient interface {
	Annotate(context.Context, *vision.AnnotationRequest, ...grpc.CallOption) (*vision.AnnotationResponse, error)
}

var _ ImageClassifierClient = imageClassifierClient{}

type imageClassifierClient struct {
	connector transport.Connector
}

// NewImageClassifierClient returns ImageClassifierClient implementation.
func NewImageClassifierClient(connector transport.Connector) ImageClassifierClient {
	return imageClassifierClient{connector}
}

// Annotate is an operation of Yandex.Cloud Vision ImageClassifier service.
func (c imageClassifierClient) Annotate(ctx context.Context, in *vision.AnnotationRequest, opts ...grpc.CallOption) (*vision.AnnotationResponse, error) {
	connection, err := c.connector.GetConnection(ctx, ImageClassifierAnnotate, opts...)
	if err != nil {
		return nil, err
	}
	return vision.NewImageClassifierServiceClient(connection).Annotate(ctx, in, opts...)
}

var (
	ImageClassifierAnnotate = protoreflect.FullName("yandex.cloud.ai.vision.v2.ImageClassifierService.Annotate")
)
