// Code generated by sdkgen-v2. DO NOT EDIT.
package usagerecordssdk

import (
	"context"

	usage_records "github.com/yandex-cloud/go-genproto/yandex/cloud/billing/usage_records/v1"
	"github.com/yandex-cloud/go-sdk/v2/pkg/transport"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// MetadataClient provides methods for managing Metadata resources of Yandex.Cloud UsageRecords.
type MetadataClient interface {
	MetadataClientIterator
	GetUsage(context.Context, *usage_records.GetUsageRequest, ...grpc.CallOption) (*usage_records.GetUsageResponse, error)
	GetLabel(context.Context, *usage_records.GetLabelRequest, ...grpc.CallOption) (*usage_records.GetLabelResponse, error)
	GetCloud(context.Context, *usage_records.GetCloudRequest, ...grpc.CallOption) (*usage_records.GetCloudResponse, error)
	GetResourceIDs(context.Context, *usage_records.GetResourceIDsRequest, ...grpc.CallOption) (*usage_records.GetResourceIDsResponse, error)
}

var _ MetadataClient = metadataClient{}

type metadataClient struct {
	connector transport.Connector
}

// NewMetadataClient returns MetadataClient implementation.
func NewMetadataClient(connector transport.Connector) MetadataClient {
	return metadataClient{connector}
}

// GetUsage is an operation of Yandex.Cloud UsageRecords Metadata service.
func (c metadataClient) GetUsage(ctx context.Context, in *usage_records.GetUsageRequest, opts ...grpc.CallOption) (*usage_records.GetUsageResponse, error) {
	connection, err := c.connector.GetConnection(ctx, MetadataGetUsage, opts...)
	if err != nil {
		return nil, err
	}
	return usage_records.NewMetadataServiceClient(connection).GetUsage(ctx, in, opts...)
}

// GetLabel is an operation of Yandex.Cloud UsageRecords Metadata service.
func (c metadataClient) GetLabel(ctx context.Context, in *usage_records.GetLabelRequest, opts ...grpc.CallOption) (*usage_records.GetLabelResponse, error) {
	connection, err := c.connector.GetConnection(ctx, MetadataGetLabel, opts...)
	if err != nil {
		return nil, err
	}
	return usage_records.NewMetadataServiceClient(connection).GetLabel(ctx, in, opts...)
}

// GetCloud is an operation of Yandex.Cloud UsageRecords Metadata service.
func (c metadataClient) GetCloud(ctx context.Context, in *usage_records.GetCloudRequest, opts ...grpc.CallOption) (*usage_records.GetCloudResponse, error) {
	connection, err := c.connector.GetConnection(ctx, MetadataGetCloud, opts...)
	if err != nil {
		return nil, err
	}
	return usage_records.NewMetadataServiceClient(connection).GetCloud(ctx, in, opts...)
}

// GetResourceIDs is an operation of Yandex.Cloud UsageRecords Metadata service.
func (c metadataClient) GetResourceIDs(ctx context.Context, in *usage_records.GetResourceIDsRequest, opts ...grpc.CallOption) (*usage_records.GetResourceIDsResponse, error) {
	connection, err := c.connector.GetConnection(ctx, MetadataGetResourceIDs, opts...)
	if err != nil {
		return nil, err
	}
	return usage_records.NewMetadataServiceClient(connection).GetResourceIDs(ctx, in, opts...)
}

var (
	MetadataGetUsage       = protoreflect.FullName("yandex.cloud.billing.usage_records.v1.MetadataService.GetUsage")
	MetadataGetLabel       = protoreflect.FullName("yandex.cloud.billing.usage_records.v1.MetadataService.GetLabel")
	MetadataGetCloud       = protoreflect.FullName("yandex.cloud.billing.usage_records.v1.MetadataService.GetCloud")
	MetadataGetResourceIDs = protoreflect.FullName("yandex.cloud.billing.usage_records.v1.MetadataService.GetResourceIDs")
)
