// Code generated by sdkgen-v2. DO NOT EDIT.
package organizationmanagersdk

import (
	"context"

	organizationmanager "github.com/yandex-cloud/go-genproto/yandex/cloud/organizationmanager/v1"
	"github.com/yandex-cloud/go-sdk/v2/pkg/iterator"
	"google.golang.org/grpc"
)

type MfaEnforcementClientIterator interface {
	Iterator(context.Context, *organizationmanager.ListMfaEnforcementsRequest, ...grpc.CallOption) *iterator.Iterator[*organizationmanager.ListMfaEnforcementsRequest, *organizationmanager.MfaEnforcement]
	AudienceIterator(context.Context, *organizationmanager.ListAudienceRequest, ...grpc.CallOption) *iterator.Iterator[*organizationmanager.ListAudienceRequest, *organizationmanager.ListAudienceResponse_Subject]
}

type mfaEnforcementServiceListInternal struct {
	*organizationmanager.ListMfaEnforcementsResponse
}

func (r mfaEnforcementServiceListInternal) Items() []*organizationmanager.MfaEnforcement {
	return r.ListMfaEnforcementsResponse.MfaEnforcements
}

func (c mfaEnforcementClient) Iterator(ctx context.Context, req *organizationmanager.ListMfaEnforcementsRequest, opts ...grpc.CallOption) *iterator.Iterator[*organizationmanager.ListMfaEnforcementsRequest, *organizationmanager.MfaEnforcement] {
	return iterator.NewIterator[*organizationmanager.ListMfaEnforcementsRequest, *organizationmanager.MfaEnforcement](ctx, req,
		func(ctx context.Context, req *organizationmanager.ListMfaEnforcementsRequest, opts ...grpc.CallOption) (iterator.PageResponse[*organizationmanager.MfaEnforcement], error) {
			resp, err := c.List(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return mfaEnforcementServiceListInternal{resp}, nil
		})
}

type mfaEnforcementServiceListAudienceInternal struct {
	*organizationmanager.ListAudienceResponse
}

func (r mfaEnforcementServiceListAudienceInternal) Items() []*organizationmanager.ListAudienceResponse_Subject {
	return r.ListAudienceResponse.Subjects
}

func (c mfaEnforcementClient) AudienceIterator(ctx context.Context, req *organizationmanager.ListAudienceRequest, opts ...grpc.CallOption) *iterator.Iterator[*organizationmanager.ListAudienceRequest, *organizationmanager.ListAudienceResponse_Subject] {
	return iterator.NewIterator[*organizationmanager.ListAudienceRequest, *organizationmanager.ListAudienceResponse_Subject](ctx, req,
		func(ctx context.Context, req *organizationmanager.ListAudienceRequest, opts ...grpc.CallOption) (iterator.PageResponse[*organizationmanager.ListAudienceResponse_Subject], error) {
			resp, err := c.ListAudience(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return mfaEnforcementServiceListAudienceInternal{resp}, nil
		})
}
