// Code generated by sdkgen-v2. DO NOT EDIT.
package mysqlsdk

import (
	"context"

	mysql "github.com/yandex-cloud/go-genproto/yandex/cloud/mdb/mysql/v1"
	"github.com/yandex-cloud/go-sdk/v2/pkg/transport"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// BackupRetentionPolicyClient provides methods for managing BackupRetentionPolicy resources of Yandex.Cloud MySQL.
type BackupRetentionPolicyClient interface {
	BackupRetentionPolicyClientIterator
	List(context.Context, *mysql.ListBackupRetentionPoliciesRequest, ...grpc.CallOption) (*mysql.ListBackupRetentionPoliciesResponse, error)
	ListByFolder(context.Context, *mysql.ListBackupRetentionPoliciesByFolderRequest, ...grpc.CallOption) (*mysql.ListBackupRetentionPoliciesResponse, error)
	Create(context.Context, *mysql.CreateBackupRetentionPolicyRequest, ...grpc.CallOption) (*mysql.CreateBackupRetentionPolicyResponse, error)
	Delete(context.Context, *mysql.DeleteBackupRetentionPolicyRequest, ...grpc.CallOption) (*mysql.DeleteBackupRetentionPolicyResponse, error)
}

var _ BackupRetentionPolicyClient = backupRetentionPolicyClient{}

type backupRetentionPolicyClient struct {
	connector transport.Connector
}

// NewBackupRetentionPolicyClient returns BackupRetentionPolicyClient implementation.
func NewBackupRetentionPolicyClient(connector transport.Connector) BackupRetentionPolicyClient {
	return backupRetentionPolicyClient{connector}
}

// List is an operation of Yandex.Cloud MySQL BackupRetentionPolicy service.
func (c backupRetentionPolicyClient) List(ctx context.Context, in *mysql.ListBackupRetentionPoliciesRequest, opts ...grpc.CallOption) (*mysql.ListBackupRetentionPoliciesResponse, error) {
	connection, err := c.connector.GetConnection(ctx, BackupRetentionPolicyList, opts...)
	if err != nil {
		return nil, err
	}
	return mysql.NewBackupRetentionPolicyServiceClient(connection).List(ctx, in, opts...)
}

// ListByFolder is an operation of Yandex.Cloud MySQL BackupRetentionPolicy service.
func (c backupRetentionPolicyClient) ListByFolder(ctx context.Context, in *mysql.ListBackupRetentionPoliciesByFolderRequest, opts ...grpc.CallOption) (*mysql.ListBackupRetentionPoliciesResponse, error) {
	connection, err := c.connector.GetConnection(ctx, BackupRetentionPolicyListByFolder, opts...)
	if err != nil {
		return nil, err
	}
	return mysql.NewBackupRetentionPolicyServiceClient(connection).ListByFolder(ctx, in, opts...)
}

// Create is an operation of Yandex.Cloud MySQL BackupRetentionPolicy service.
func (c backupRetentionPolicyClient) Create(ctx context.Context, in *mysql.CreateBackupRetentionPolicyRequest, opts ...grpc.CallOption) (*mysql.CreateBackupRetentionPolicyResponse, error) {
	connection, err := c.connector.GetConnection(ctx, BackupRetentionPolicyCreate, opts...)
	if err != nil {
		return nil, err
	}
	return mysql.NewBackupRetentionPolicyServiceClient(connection).Create(ctx, in, opts...)
}

// Delete is an operation of Yandex.Cloud MySQL BackupRetentionPolicy service.
func (c backupRetentionPolicyClient) Delete(ctx context.Context, in *mysql.DeleteBackupRetentionPolicyRequest, opts ...grpc.CallOption) (*mysql.DeleteBackupRetentionPolicyResponse, error) {
	connection, err := c.connector.GetConnection(ctx, BackupRetentionPolicyDelete, opts...)
	if err != nil {
		return nil, err
	}
	return mysql.NewBackupRetentionPolicyServiceClient(connection).Delete(ctx, in, opts...)
}

var (
	BackupRetentionPolicyList         = protoreflect.FullName("yandex.cloud.mdb.mysql.v1.BackupRetentionPolicyService.List")
	BackupRetentionPolicyListByFolder = protoreflect.FullName("yandex.cloud.mdb.mysql.v1.BackupRetentionPolicyService.ListByFolder")
	BackupRetentionPolicyCreate       = protoreflect.FullName("yandex.cloud.mdb.mysql.v1.BackupRetentionPolicyService.Create")
	BackupRetentionPolicyDelete       = protoreflect.FullName("yandex.cloud.mdb.mysql.v1.BackupRetentionPolicyService.Delete")
)
