// Code generated by sdkgen-v2. DO NOT EDIT.
package jobssdk

import (
	"github.com/yandex-cloud/go-sdk/v2/pkg/transport"
)

// Jobs provides access to components and services of Yandex.Cloud Jobs.
type Jobs struct {
	connector transport.Connector
}

// New creates an instance of Jobs.
func New(connector transport.Connector) Jobs {
	return Jobs{connector: connector}
}

// ProjectJob provides access to the ProjectJob service of Yandex.Cloud Jobs.
func (g Jobs) ProjectJob() ProjectJobClient {
	return NewProjectJobClient(g.connector)
}
