// Code generated by sdkgen-v2. DO NOT EDIT.
package jobssdk

import (
	"context"

	jobs "github.com/yandex-cloud/go-genproto/yandex/cloud/datasphere/v2/jobs"
	"github.com/yandex-cloud/go-sdk/v2/pkg/iterator"
	"google.golang.org/grpc"
)

type ProjectJobClientIterator interface {
	Iterator(context.Context, *jobs.ListProjectJobRequest, ...grpc.CallOption) *iterator.Iterator[*jobs.ListProjectJobRequest, *jobs.Job]
}

type projectJobServiceListInternal struct {
	*jobs.ListProjectJobResponse
}

func (r projectJobServiceListInternal) Items() []*jobs.Job { return r.ListProjectJobResponse.Jobs }

func (c projectJobClient) Iterator(ctx context.Context, req *jobs.ListProjectJobRequest, opts ...grpc.CallOption) *iterator.Iterator[*jobs.ListProjectJobRequest, *jobs.Job] {
	return iterator.NewIterator[*jobs.ListProjectJobRequest, *jobs.Job](ctx, req,
		func(ctx context.Context, req *jobs.ListProjectJobRequest, opts ...grpc.CallOption) (iterator.PageResponse[*jobs.Job], error) {
			resp, err := c.List(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return projectJobServiceListInternal{resp}, nil
		})
}
