// Code generated by sdkgen-v2. DO NOT EDIT.
package mongodbsdk

import (
	"context"

	mongodb "github.com/yandex-cloud/go-genproto/yandex/cloud/mdb/mongodb/v1"
	mdb "github.com/yandex-cloud/go-genproto/yandex/cloud/mdb/v1"
	"github.com/yandex-cloud/go-sdk/v2/pkg/transport"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// BackupRetentionPolicyClient provides methods for managing BackupRetentionPolicy resources of Yandex.Cloud MongoDB.
type BackupRetentionPolicyClient interface {
	BackupRetentionPolicyClientIterator
	Get(context.Context, *mongodb.GetBackupRetentionPolicyRequest, ...grpc.CallOption) (*mdb.BackupRetentionPolicy, error)
	List(context.Context, *mongodb.ListBackupRetentionPoliciesRequest, ...grpc.CallOption) (*mongodb.ListBackupRetentionPoliciesResponse, error)
	ListByFolder(context.Context, *mongodb.ListBackupRetentionPoliciesByFolderRequest, ...grpc.CallOption) (*mongodb.ListBackupRetentionPoliciesResponse, error)
	Create(context.Context, *mongodb.CreateBackupRetentionPolicyRequest, ...grpc.CallOption) (*mongodb.CreateBackupRetentionPolicyResponse, error)
	Delete(context.Context, *mongodb.DeleteBackupRetentionPolicyRequest, ...grpc.CallOption) (*mongodb.DeleteBackupRetentionPolicyResponse, error)
}

var _ BackupRetentionPolicyClient = backupRetentionPolicyClient{}

type backupRetentionPolicyClient struct {
	connector transport.Connector
}

// NewBackupRetentionPolicyClient returns BackupRetentionPolicyClient implementation.
func NewBackupRetentionPolicyClient(connector transport.Connector) BackupRetentionPolicyClient {
	return backupRetentionPolicyClient{connector}
}

// Get is an operation of Yandex.Cloud MongoDB BackupRetentionPolicy service.
func (c backupRetentionPolicyClient) Get(ctx context.Context, in *mongodb.GetBackupRetentionPolicyRequest, opts ...grpc.CallOption) (*mdb.BackupRetentionPolicy, error) {
	connection, err := c.connector.GetConnection(ctx, BackupRetentionPolicyGet, opts...)
	if err != nil {
		return nil, err
	}
	return mongodb.NewBackupRetentionPolicyServiceClient(connection).Get(ctx, in, opts...)
}

// List is an operation of Yandex.Cloud MongoDB BackupRetentionPolicy service.
func (c backupRetentionPolicyClient) List(ctx context.Context, in *mongodb.ListBackupRetentionPoliciesRequest, opts ...grpc.CallOption) (*mongodb.ListBackupRetentionPoliciesResponse, error) {
	connection, err := c.connector.GetConnection(ctx, BackupRetentionPolicyList, opts...)
	if err != nil {
		return nil, err
	}
	return mongodb.NewBackupRetentionPolicyServiceClient(connection).List(ctx, in, opts...)
}

// ListByFolder is an operation of Yandex.Cloud MongoDB BackupRetentionPolicy service.
func (c backupRetentionPolicyClient) ListByFolder(ctx context.Context, in *mongodb.ListBackupRetentionPoliciesByFolderRequest, opts ...grpc.CallOption) (*mongodb.ListBackupRetentionPoliciesResponse, error) {
	connection, err := c.connector.GetConnection(ctx, BackupRetentionPolicyListByFolder, opts...)
	if err != nil {
		return nil, err
	}
	return mongodb.NewBackupRetentionPolicyServiceClient(connection).ListByFolder(ctx, in, opts...)
}

// Create is an operation of Yandex.Cloud MongoDB BackupRetentionPolicy service.
func (c backupRetentionPolicyClient) Create(ctx context.Context, in *mongodb.CreateBackupRetentionPolicyRequest, opts ...grpc.CallOption) (*mongodb.CreateBackupRetentionPolicyResponse, error) {
	connection, err := c.connector.GetConnection(ctx, BackupRetentionPolicyCreate, opts...)
	if err != nil {
		return nil, err
	}
	return mongodb.NewBackupRetentionPolicyServiceClient(connection).Create(ctx, in, opts...)
}

// Delete is an operation of Yandex.Cloud MongoDB BackupRetentionPolicy service.
func (c backupRetentionPolicyClient) Delete(ctx context.Context, in *mongodb.DeleteBackupRetentionPolicyRequest, opts ...grpc.CallOption) (*mongodb.DeleteBackupRetentionPolicyResponse, error) {
	connection, err := c.connector.GetConnection(ctx, BackupRetentionPolicyDelete, opts...)
	if err != nil {
		return nil, err
	}
	return mongodb.NewBackupRetentionPolicyServiceClient(connection).Delete(ctx, in, opts...)
}

var (
	BackupRetentionPolicyGet          = protoreflect.FullName("yandex.cloud.mdb.mongodb.v1.BackupRetentionPolicyService.Get")
	BackupRetentionPolicyList         = protoreflect.FullName("yandex.cloud.mdb.mongodb.v1.BackupRetentionPolicyService.List")
	BackupRetentionPolicyListByFolder = protoreflect.FullName("yandex.cloud.mdb.mongodb.v1.BackupRetentionPolicyService.ListByFolder")
	BackupRetentionPolicyCreate       = protoreflect.FullName("yandex.cloud.mdb.mongodb.v1.BackupRetentionPolicyService.Create")
	BackupRetentionPolicyDelete       = protoreflect.FullName("yandex.cloud.mdb.mongodb.v1.BackupRetentionPolicyService.Delete")
)
