// Code generated by sdkgen-v2. DO NOT EDIT.
package brokersdk

import (
	"context"

	broker "github.com/yandex-cloud/go-genproto/yandex/cloud/iot/broker/v1"
	operation "github.com/yandex-cloud/go-genproto/yandex/cloud/operation"
	"github.com/yandex-cloud/go-sdk/v2/pkg/iterator"
	"google.golang.org/grpc"
)

type BrokerClientIterator interface {
	Iterator(context.Context, *broker.ListBrokersRequest, ...grpc.CallOption) *iterator.Iterator[*broker.ListBrokersRequest, *broker.Broker]
	OperationsIterator(context.Context, *broker.ListBrokerOperationsRequest, ...grpc.CallOption) *iterator.Iterator[*broker.ListBrokerOperationsRequest, *operation.Operation]
}

type brokerServiceListInternal struct {
	*broker.ListBrokersResponse
}

func (r brokerServiceListInternal) Items() []*broker.Broker { return r.ListBrokersResponse.Brokers }

func (c brokerClient) Iterator(ctx context.Context, req *broker.ListBrokersRequest, opts ...grpc.CallOption) *iterator.Iterator[*broker.ListBrokersRequest, *broker.Broker] {
	return iterator.NewIterator[*broker.ListBrokersRequest, *broker.Broker](ctx, req,
		func(ctx context.Context, req *broker.ListBrokersRequest, opts ...grpc.CallOption) (iterator.PageResponse[*broker.Broker], error) {
			resp, err := c.List(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return brokerServiceListInternal{resp}, nil
		})
}

type brokerServiceListOperationsInternal struct {
	*broker.ListBrokerOperationsResponse
}

func (r brokerServiceListOperationsInternal) Items() []*operation.Operation {
	return r.ListBrokerOperationsResponse.Operations
}

func (c brokerClient) OperationsIterator(ctx context.Context, req *broker.ListBrokerOperationsRequest, opts ...grpc.CallOption) *iterator.Iterator[*broker.ListBrokerOperationsRequest, *operation.Operation] {
	return iterator.NewIterator[*broker.ListBrokerOperationsRequest, *operation.Operation](ctx, req,
		func(ctx context.Context, req *broker.ListBrokerOperationsRequest, opts ...grpc.CallOption) (iterator.PageResponse[*operation.Operation], error) {
			resp, err := c.ListOperations(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return brokerServiceListOperationsInternal{resp}, nil
		})
}
