// Code generated by sdkgen-v2. DO NOT EDIT.
package devicessdk

import (
	"github.com/yandex-cloud/go-sdk/v2/pkg/transport"
)

// Devices provides access to components and services of Yandex.Cloud Devices.
type Devices struct {
	connector transport.Connector
}

// New creates an instance of Devices.
func New(connector transport.Connector) Devices {
	return Devices{connector: connector}
}

// DeviceData provides access to the DeviceData service of Yandex.Cloud Devices.
func (g Devices) DeviceData() DeviceDataClient {
	return NewDeviceDataClient(g.connector)
}

// Device provides access to the Device service of Yandex.Cloud Devices.
func (g Devices) Device() DeviceClient {
	return NewDeviceClient(g.connector)
}

// RegistryData provides access to the RegistryData service of Yandex.Cloud Devices.
func (g Devices) RegistryData() RegistryDataClient {
	return NewRegistryDataClient(g.connector)
}

// Registry provides access to the Registry service of Yandex.Cloud Devices.
func (g Devices) Registry() RegistryClient {
	return NewRegistryClient(g.connector)
}
