// Code generated by sdkgen-v2. DO NOT EDIT.
package devicessdk

import (
	"context"

	devices "github.com/yandex-cloud/go-genproto/yandex/cloud/iot/devices/v1"
	operation "github.com/yandex-cloud/go-genproto/yandex/cloud/operation"
	"github.com/yandex-cloud/go-sdk/v2/pkg/iterator"
	"google.golang.org/grpc"
)

type RegistryClientIterator interface {
	Iterator(context.Context, *devices.ListRegistriesRequest, ...grpc.CallOption) *iterator.Iterator[*devices.ListRegistriesRequest, *devices.Registry]
	DeviceTopicAliasesIterator(context.Context, *devices.ListDeviceTopicAliasesRequest, ...grpc.CallOption) *iterator.Iterator[*devices.ListDeviceTopicAliasesRequest, *devices.DeviceAlias]
	OperationsIterator(context.Context, *devices.ListRegistryOperationsRequest, ...grpc.CallOption) *iterator.Iterator[*devices.ListRegistryOperationsRequest, *operation.Operation]
}

type registryServiceListInternal struct {
	*devices.ListRegistriesResponse
}

func (r registryServiceListInternal) Items() []*devices.Registry {
	return r.ListRegistriesResponse.Registries
}

func (c registryClient) Iterator(ctx context.Context, req *devices.ListRegistriesRequest, opts ...grpc.CallOption) *iterator.Iterator[*devices.ListRegistriesRequest, *devices.Registry] {
	return iterator.NewIterator[*devices.ListRegistriesRequest, *devices.Registry](ctx, req,
		func(ctx context.Context, req *devices.ListRegistriesRequest, opts ...grpc.CallOption) (iterator.PageResponse[*devices.Registry], error) {
			resp, err := c.List(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return registryServiceListInternal{resp}, nil
		})
}

type registryServiceListDeviceTopicAliasesInternal struct {
	*devices.ListDeviceTopicAliasesResponse
}

func (r registryServiceListDeviceTopicAliasesInternal) Items() []*devices.DeviceAlias {
	return r.ListDeviceTopicAliasesResponse.Aliases
}

func (c registryClient) DeviceTopicAliasesIterator(ctx context.Context, req *devices.ListDeviceTopicAliasesRequest, opts ...grpc.CallOption) *iterator.Iterator[*devices.ListDeviceTopicAliasesRequest, *devices.DeviceAlias] {
	return iterator.NewIterator[*devices.ListDeviceTopicAliasesRequest, *devices.DeviceAlias](ctx, req,
		func(ctx context.Context, req *devices.ListDeviceTopicAliasesRequest, opts ...grpc.CallOption) (iterator.PageResponse[*devices.DeviceAlias], error) {
			resp, err := c.ListDeviceTopicAliases(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return registryServiceListDeviceTopicAliasesInternal{resp}, nil
		})
}

type registryServiceListOperationsInternal struct {
	*devices.ListRegistryOperationsResponse
}

func (r registryServiceListOperationsInternal) Items() []*operation.Operation {
	return r.ListRegistryOperationsResponse.Operations
}

func (c registryClient) OperationsIterator(ctx context.Context, req *devices.ListRegistryOperationsRequest, opts ...grpc.CallOption) *iterator.Iterator[*devices.ListRegistryOperationsRequest, *operation.Operation] {
	return iterator.NewIterator[*devices.ListRegistryOperationsRequest, *operation.Operation](ctx, req,
		func(ctx context.Context, req *devices.ListRegistryOperationsRequest, opts ...grpc.CallOption) (iterator.PageResponse[*operation.Operation], error) {
			resp, err := c.ListOperations(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return registryServiceListOperationsInternal{resp}, nil
		})
}
