// Code generated by sdkgen-v2. DO NOT EDIT.
package ycvcsdk

import (
	"context"

	ycvc "github.com/yandex-cloud/go-genproto/yandex/cloud/devtools/ycvc/v1"
	"github.com/yandex-cloud/go-sdk/v2/pkg/transport"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// VersionControlClient provides methods for managing VersionControl resources of Yandex.Cloud Ycvc.
type VersionControlClient interface {
	VersionControlClientIterator
	Init(context.Context, *ycvc.InitRequest, ...grpc.CallOption) (*ycvc.InitResponse, error)
}

var _ VersionControlClient = versionControlClient{}

type versionControlClient struct {
	connector transport.Connector
}

// NewVersionControlClient returns VersionControlClient implementation.
func NewVersionControlClient(connector transport.Connector) VersionControlClient {
	return versionControlClient{connector}
}

// Init is an operation of Yandex.Cloud Ycvc VersionControl service.
func (c versionControlClient) Init(ctx context.Context, in *ycvc.InitRequest, opts ...grpc.CallOption) (*ycvc.InitResponse, error) {
	connection, err := c.connector.GetConnection(ctx, VersionControlInit, opts...)
	if err != nil {
		return nil, err
	}
	return ycvc.NewVersionControlServiceClient(connection).Init(ctx, in, opts...)
}

var (
	VersionControlInit = protoreflect.FullName("yandex.cloud.devtools.ycvc.v1.VersionControlService.Init")
)
