// Code generated by sdkgen-v2. DO NOT EDIT.
package custompagesdk

import (
	"context"

	custom_page "github.com/yandex-cloud/go-genproto/yandex/cloud/smartwebsecurity/v1/custom_page"
	"github.com/yandex-cloud/go-sdk/v2/pkg/sdkresolvers"
)

type customPageResolver struct {
	client CustomPageClient
	sdkresolvers.BaseNameResolver
}

func CustomPageResolver(name string, client CustomPageClient, opts ...sdkresolvers.ResolveOption) sdkresolvers.Resolver {
	return &customPageResolver{
		client:           client,
		BaseNameResolver: sdkresolvers.NewBaseNameResolver(name, "CustomPage", opts...),
	}
}

func (r *customPageResolver) Run(ctx context.Context) error {
	resp := r.client.Iterator(ctx, &custom_page.ListCustomPagesRequest{
		FolderId: r.FolderID(),
		Filter:   sdkresolvers.CreateResolverFilter("name", r.Name),
		PageSize: sdkresolvers.DefaultResolverPageSize,
	})
	return r.FindName(resp.TakeAll())
}
