// Code generated by sdkgen-v2. DO NOT EDIT.
package custompagesdk

import (
	"context"

	custom_page "github.com/yandex-cloud/go-genproto/yandex/cloud/smartwebsecurity/v1/custom_page"
	"github.com/yandex-cloud/go-sdk/v2/pkg/iterator"
	"google.golang.org/grpc"
)

type CustomPageClientIterator interface {
	Iterator(context.Context, *custom_page.ListCustomPagesRequest, ...grpc.CallOption) *iterator.Iterator[*custom_page.ListCustomPagesRequest, *custom_page.CustomPage]
}

type customPageServiceListInternal struct {
	*custom_page.ListCustomPagesResponse
}

func (r customPageServiceListInternal) Items() []*custom_page.CustomPage {
	return r.ListCustomPagesResponse.CustomPages
}

func (c customPageClient) Iterator(ctx context.Context, req *custom_page.ListCustomPagesRequest, opts ...grpc.CallOption) *iterator.Iterator[*custom_page.ListCustomPagesRequest, *custom_page.CustomPage] {
	return iterator.NewIterator[*custom_page.ListCustomPagesRequest, *custom_page.CustomPage](ctx, req,
		func(ctx context.Context, req *custom_page.ListCustomPagesRequest, opts ...grpc.CallOption) (iterator.PageResponse[*custom_page.CustomPage], error) {
			resp, err := c.List(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return customPageServiceListInternal{resp}, nil
		})
}
