// Code generated by sdkgen-v2. DO NOT EDIT.
package baremetalsdk

import (
	"context"

	baremetal "github.com/yandex-cloud/go-genproto/yandex/cloud/baremetal/v2"
	operation "github.com/yandex-cloud/go-genproto/yandex/cloud/operation"
	sdkop "github.com/yandex-cloud/go-sdk/v2/pkg/operation"
	"github.com/yandex-cloud/go-sdk/v2/pkg/transport"
	"google.golang.org/grpc"
	proto "google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// BootImageClient provides methods for managing BootImage resources of Yandex.Cloud Baremetal.
type BootImageClient interface {
	BootImageClientIterator
	GetBootImage(context.Context, *baremetal.GetBootImageRequest, ...grpc.CallOption) (*baremetal.BootImage, error)
	ListBootImages(context.Context, *baremetal.ListBootImagesRequest, ...grpc.CallOption) (*baremetal.ListBootImagesResponse, error)
	CreateBootImage(context.Context, *baremetal.CreateBootImageRequest, ...grpc.CallOption) (*BootImageCreateBootImageOperation, error)
	UpdateBootImage(context.Context, *baremetal.UpdateBootImageRequest, ...grpc.CallOption) (*BootImageUpdateBootImageOperation, error)
	DeleteBootImage(context.Context, *baremetal.DeleteBootImageRequest, ...grpc.CallOption) (*BootImageDeleteBootImageOperation, error)
	ListBootImageOperations(context.Context, *baremetal.ListBootImageOperationsRequest, ...grpc.CallOption) (*baremetal.ListBootImageOperationsResponse, error)
}

var _ BootImageClient = bootImageClient{}

type bootImageClient struct {
	connector transport.Connector
}

// NewBootImageClient returns BootImageClient implementation.
func NewBootImageClient(connector transport.Connector) BootImageClient {
	return bootImageClient{connector}
}

// GetBootImage is an operation of Yandex.Cloud Baremetal BootImage service.
func (c bootImageClient) GetBootImage(ctx context.Context, in *baremetal.GetBootImageRequest, opts ...grpc.CallOption) (*baremetal.BootImage, error) {
	connection, err := c.connector.GetConnection(ctx, BootImageGetBootImage, opts...)
	if err != nil {
		return nil, err
	}
	return baremetal.NewBootImageServiceClient(connection).GetBootImage(ctx, in, opts...)
}

// ListBootImages is an operation of Yandex.Cloud Baremetal BootImage service.
func (c bootImageClient) ListBootImages(ctx context.Context, in *baremetal.ListBootImagesRequest, opts ...grpc.CallOption) (*baremetal.ListBootImagesResponse, error) {
	connection, err := c.connector.GetConnection(ctx, BootImageListBootImages, opts...)
	if err != nil {
		return nil, err
	}
	return baremetal.NewBootImageServiceClient(connection).ListBootImages(ctx, in, opts...)
}

// BootImageCreateBootImageOperation is used to monitor the state of CreateBootImage operations.
type BootImageCreateBootImageOperation struct {
	sdkop.Operation
}

// Metadata retrieves the operation metadata.
func (o *BootImageCreateBootImageOperation) Metadata() *baremetal.CreateBootImageMetadata {
	return o.Operation.Metadata().(*baremetal.CreateBootImageMetadata)
}

// Response retrieves the operation response.
func (o *BootImageCreateBootImageOperation) Response() *baremetal.BootImage {
	return o.Operation.Response().(*baremetal.BootImage)
}

// Wait polls the operation until it's done.
func (o *BootImageCreateBootImageOperation) Wait(ctx context.Context, opts ...grpc.CallOption) (*baremetal.BootImage, error) {
	abstract, err := o.Operation.Wait(ctx, opts...)
	response, _ := abstract.(*baremetal.BootImage)
	return response, err
}

// WaitInterval polls the operation until it's done with custom interval.
func (o *BootImageCreateBootImageOperation) WaitInterval(ctx context.Context, pollInterval sdkop.PollIntervalFunc, opts ...grpc.CallOption) (*baremetal.BootImage, error) {
	abstract, err := o.Operation.WaitInterval(ctx, pollInterval, opts...)
	response, _ := abstract.(*baremetal.BootImage)
	return response, err
}

// CreateBootImage is an operation of Yandex.Cloud Baremetal BootImage service.
// It returns an object which should be used to monitor the operation state.
func (c bootImageClient) CreateBootImage(ctx context.Context, in *baremetal.CreateBootImageRequest, opts ...grpc.CallOption) (*BootImageCreateBootImageOperation, error) {
	connection, err := c.connector.GetConnection(ctx, BootImageCreateBootImage, opts...)
	if err != nil {
		return nil, err
	}
	pb, err := baremetal.NewBootImageServiceClient(connection).CreateBootImage(ctx, in, opts...)
	if err != nil {
		return nil, err
	}
	op, err := sdkop.NewOperation(pb, &sdkop.Concretization{
		Poll: c.pollOperation,
		GetResourceID: func(metadata proto.Message) string {
			return metadata.(*baremetal.CreateBootImageMetadata).GetBootImageId()
		},
		MetadataType: (*baremetal.CreateBootImageMetadata)(nil),
		ResponseType: (*baremetal.BootImage)(nil),
	})
	if err != nil {
		return nil, err
	}
	return &BootImageCreateBootImageOperation{*op}, nil
}

// BootImageUpdateBootImageOperation is used to monitor the state of UpdateBootImage operations.
type BootImageUpdateBootImageOperation struct {
	sdkop.Operation
}

// Metadata retrieves the operation metadata.
func (o *BootImageUpdateBootImageOperation) Metadata() *baremetal.UpdateBootImageMetadata {
	return o.Operation.Metadata().(*baremetal.UpdateBootImageMetadata)
}

// Response retrieves the operation response.
func (o *BootImageUpdateBootImageOperation) Response() *baremetal.BootImage {
	return o.Operation.Response().(*baremetal.BootImage)
}

// Wait polls the operation until it's done.
func (o *BootImageUpdateBootImageOperation) Wait(ctx context.Context, opts ...grpc.CallOption) (*baremetal.BootImage, error) {
	abstract, err := o.Operation.Wait(ctx, opts...)
	response, _ := abstract.(*baremetal.BootImage)
	return response, err
}

// WaitInterval polls the operation until it's done with custom interval.
func (o *BootImageUpdateBootImageOperation) WaitInterval(ctx context.Context, pollInterval sdkop.PollIntervalFunc, opts ...grpc.CallOption) (*baremetal.BootImage, error) {
	abstract, err := o.Operation.WaitInterval(ctx, pollInterval, opts...)
	response, _ := abstract.(*baremetal.BootImage)
	return response, err
}

// UpdateBootImage is an operation of Yandex.Cloud Baremetal BootImage service.
// It returns an object which should be used to monitor the operation state.
func (c bootImageClient) UpdateBootImage(ctx context.Context, in *baremetal.UpdateBootImageRequest, opts ...grpc.CallOption) (*BootImageUpdateBootImageOperation, error) {
	connection, err := c.connector.GetConnection(ctx, BootImageUpdateBootImage, opts...)
	if err != nil {
		return nil, err
	}
	pb, err := baremetal.NewBootImageServiceClient(connection).UpdateBootImage(ctx, in, opts...)
	if err != nil {
		return nil, err
	}
	op, err := sdkop.NewOperation(pb, &sdkop.Concretization{
		Poll: c.pollOperation,
		GetResourceID: func(metadata proto.Message) string {
			return metadata.(*baremetal.UpdateBootImageMetadata).GetBootImageId()
		},
		MetadataType: (*baremetal.UpdateBootImageMetadata)(nil),
		ResponseType: (*baremetal.BootImage)(nil),
	})
	if err != nil {
		return nil, err
	}
	return &BootImageUpdateBootImageOperation{*op}, nil
}

// BootImageDeleteBootImageOperation is used to monitor the state of DeleteBootImage operations.
type BootImageDeleteBootImageOperation struct {
	sdkop.Operation
}

// Metadata retrieves the operation metadata.
func (o *BootImageDeleteBootImageOperation) Metadata() *baremetal.DeleteBootImageMetadata {
	return o.Operation.Metadata().(*baremetal.DeleteBootImageMetadata)
}

// Response retrieves the operation response.
func (o *BootImageDeleteBootImageOperation) Response() *emptypb.Empty {
	return o.Operation.Response().(*emptypb.Empty)
}

// Wait polls the operation until it's done.
func (o *BootImageDeleteBootImageOperation) Wait(ctx context.Context, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	abstract, err := o.Operation.Wait(ctx, opts...)
	response, _ := abstract.(*emptypb.Empty)
	return response, err
}

// WaitInterval polls the operation until it's done with custom interval.
func (o *BootImageDeleteBootImageOperation) WaitInterval(ctx context.Context, pollInterval sdkop.PollIntervalFunc, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	abstract, err := o.Operation.WaitInterval(ctx, pollInterval, opts...)
	response, _ := abstract.(*emptypb.Empty)
	return response, err
}

// DeleteBootImage is an operation of Yandex.Cloud Baremetal BootImage service.
// It returns an object which should be used to monitor the operation state.
func (c bootImageClient) DeleteBootImage(ctx context.Context, in *baremetal.DeleteBootImageRequest, opts ...grpc.CallOption) (*BootImageDeleteBootImageOperation, error) {
	connection, err := c.connector.GetConnection(ctx, BootImageDeleteBootImage, opts...)
	if err != nil {
		return nil, err
	}
	pb, err := baremetal.NewBootImageServiceClient(connection).DeleteBootImage(ctx, in, opts...)
	if err != nil {
		return nil, err
	}
	op, err := sdkop.NewOperation(pb, &sdkop.Concretization{
		Poll: c.pollOperation,
		GetResourceID: func(metadata proto.Message) string {
			return metadata.(*baremetal.DeleteBootImageMetadata).GetBootImageId()
		},
		MetadataType: (*baremetal.DeleteBootImageMetadata)(nil),
		ResponseType: (*emptypb.Empty)(nil),
	})
	if err != nil {
		return nil, err
	}
	return &BootImageDeleteBootImageOperation{*op}, nil
}

// ListBootImageOperations is an operation of Yandex.Cloud Baremetal BootImage service.
func (c bootImageClient) ListBootImageOperations(ctx context.Context, in *baremetal.ListBootImageOperationsRequest, opts ...grpc.CallOption) (*baremetal.ListBootImageOperationsResponse, error) {
	connection, err := c.connector.GetConnection(ctx, BootImageListBootImageOperations, opts...)
	if err != nil {
		return nil, err
	}
	return baremetal.NewBootImageServiceClient(connection).ListBootImageOperations(ctx, in, opts...)
}

// pollOperation returns the current state of the polled operation.
func (c bootImageClient) pollOperation(ctx context.Context, operationId string, opts ...grpc.CallOption) (sdkop.YCOperation, error) {
	connection, err := c.connector.GetConnection(ctx, BootImageOperationPoller, opts...)
	if err != nil {
		return nil, err
	}
	return operation.NewOperationServiceClient(connection).Get(ctx, &operation.GetOperationRequest{OperationId: operationId}, opts...)
}

var (
	BootImageGetBootImage            = protoreflect.FullName("yandex.cloud.baremetal.v2.BootImageService.GetBootImage")
	BootImageListBootImages          = protoreflect.FullName("yandex.cloud.baremetal.v2.BootImageService.ListBootImages")
	BootImageCreateBootImage         = protoreflect.FullName("yandex.cloud.baremetal.v2.BootImageService.CreateBootImage")
	BootImageUpdateBootImage         = protoreflect.FullName("yandex.cloud.baremetal.v2.BootImageService.UpdateBootImage")
	BootImageDeleteBootImage         = protoreflect.FullName("yandex.cloud.baremetal.v2.BootImageService.DeleteBootImage")
	BootImageListBootImageOperations = protoreflect.FullName("yandex.cloud.baremetal.v2.BootImageService.ListBootImageOperations")
	BootImageOperationPoller         = protoreflect.FullName("yandex.cloud.operation.OperationService.Get")
)
