// Code generated by sdkgen-v2. DO NOT EDIT.
package baremetalsdk

import (
	"context"

	baremetal "github.com/yandex-cloud/go-genproto/yandex/cloud/baremetal/v2"
	"github.com/yandex-cloud/go-sdk/v2/pkg/iterator"
	"google.golang.org/grpc"
)

type ConfigurationClientIterator interface {
	ConfigurationRentalPeriodsIterator(context.Context, *baremetal.ListConfigurationRentalPeriodsRequest, ...grpc.CallOption) *iterator.Iterator[*baremetal.ListConfigurationRentalPeriodsRequest, *baremetal.RentalPeriod]
}

type configurationServiceListConfigurationRentalPeriodsInternal struct {
	*baremetal.ListConfigurationRentalPeriodsResponse
}

func (r configurationServiceListConfigurationRentalPeriodsInternal) Items() []*baremetal.RentalPeriod {
	return r.ListConfigurationRentalPeriodsResponse.RentalPeriods
}

func (c configurationClient) ConfigurationRentalPeriodsIterator(ctx context.Context, req *baremetal.ListConfigurationRentalPeriodsRequest, opts ...grpc.CallOption) *iterator.Iterator[*baremetal.ListConfigurationRentalPeriodsRequest, *baremetal.RentalPeriod] {
	return iterator.NewIterator[*baremetal.ListConfigurationRentalPeriodsRequest, *baremetal.RentalPeriod](ctx, req,
		func(ctx context.Context, req *baremetal.ListConfigurationRentalPeriodsRequest, opts ...grpc.CallOption) (iterator.PageResponse[*baremetal.RentalPeriod], error) {
			resp, err := c.ListConfigurationRentalPeriods(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return configurationServiceListConfigurationRentalPeriodsInternal{resp}, nil
		})
}
