// Code generated by sdkgen-v2. DO NOT EDIT.
package baremetalsdk

import (
	"context"

	baremetal "github.com/yandex-cloud/go-genproto/yandex/cloud/baremetal/v2"
	"github.com/yandex-cloud/go-sdk/v2/pkg/transport"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// HardwarePoolClient provides methods for managing HardwarePool resources of Yandex.Cloud Baremetal.
type HardwarePoolClient interface {
	HardwarePoolClientIterator
	GetHardwarePool(context.Context, *baremetal.GetHardwarePoolRequest, ...grpc.CallOption) (*baremetal.HardwarePool, error)
	ListHardwarePools(context.Context, *baremetal.ListHardwarePoolsRequest, ...grpc.CallOption) (*baremetal.ListHardwarePoolsResponse, error)
}

var _ HardwarePoolClient = hardwarePoolClient{}

type hardwarePoolClient struct {
	connector transport.Connector
}

// NewHardwarePoolClient returns HardwarePoolClient implementation.
func NewHardwarePoolClient(connector transport.Connector) HardwarePoolClient {
	return hardwarePoolClient{connector}
}

// GetHardwarePool is an operation of Yandex.Cloud Baremetal HardwarePool service.
func (c hardwarePoolClient) GetHardwarePool(ctx context.Context, in *baremetal.GetHardwarePoolRequest, opts ...grpc.CallOption) (*baremetal.HardwarePool, error) {
	connection, err := c.connector.GetConnection(ctx, HardwarePoolGetHardwarePool, opts...)
	if err != nil {
		return nil, err
	}
	return baremetal.NewHardwarePoolServiceClient(connection).GetHardwarePool(ctx, in, opts...)
}

// ListHardwarePools is an operation of Yandex.Cloud Baremetal HardwarePool service.
func (c hardwarePoolClient) ListHardwarePools(ctx context.Context, in *baremetal.ListHardwarePoolsRequest, opts ...grpc.CallOption) (*baremetal.ListHardwarePoolsResponse, error) {
	connection, err := c.connector.GetConnection(ctx, HardwarePoolListHardwarePools, opts...)
	if err != nil {
		return nil, err
	}
	return baremetal.NewHardwarePoolServiceClient(connection).ListHardwarePools(ctx, in, opts...)
}

var (
	HardwarePoolGetHardwarePool   = protoreflect.FullName("yandex.cloud.baremetal.v2.HardwarePoolService.GetHardwarePool")
	HardwarePoolListHardwarePools = protoreflect.FullName("yandex.cloud.baremetal.v2.HardwarePoolService.ListHardwarePools")
)
