// Code generated by sdkgen-v2. DO NOT EDIT.
package baremetalsdk

import (
	"context"

	baremetal "github.com/yandex-cloud/go-genproto/yandex/cloud/baremetal/v2"
	"github.com/yandex-cloud/go-sdk/v2/pkg/iterator"
	"google.golang.org/grpc"
)

type ImageClientIterator interface {
	ImagesIterator(context.Context, *baremetal.ListImagesRequest, ...grpc.CallOption) *iterator.Iterator[*baremetal.ListImagesRequest, *baremetal.Image]
}

type imageServiceListImagesInternal struct {
	*baremetal.ListImagesResponse
}

func (r imageServiceListImagesInternal) Items() []*baremetal.Image {
	return r.ListImagesResponse.Images
}

func (c imageClient) ImagesIterator(ctx context.Context, req *baremetal.ListImagesRequest, opts ...grpc.CallOption) *iterator.Iterator[*baremetal.ListImagesRequest, *baremetal.Image] {
	return iterator.NewIterator[*baremetal.ListImagesRequest, *baremetal.Image](ctx, req,
		func(ctx context.Context, req *baremetal.ListImagesRequest, opts ...grpc.CallOption) (iterator.PageResponse[*baremetal.Image], error) {
			resp, err := c.ListImages(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return imageServiceListImagesInternal{resp}, nil
		})
}
