// Code generated by sdkgen-v2. DO NOT EDIT.
package baremetalsdk

import (
	"context"

	baremetal "github.com/yandex-cloud/go-genproto/yandex/cloud/baremetal/v2"
	"github.com/yandex-cloud/go-sdk/v2/pkg/sdkresolvers"
)

type privateSubnetPrivateSubnetsResolver struct {
	client PrivateSubnetClient
	sdkresolvers.BaseNameResolver
}

func PrivateSubnetPrivateSubnetsResolver(name string, client PrivateSubnetClient, opts ...sdkresolvers.ResolveOption) sdkresolvers.Resolver {
	return &privateSubnetPrivateSubnetsResolver{
		client:           client,
		BaseNameResolver: sdkresolvers.NewBaseNameResolver(name, "PrivateSubnetPrivateSubnets", opts...),
	}
}

func (r *privateSubnetPrivateSubnetsResolver) Run(ctx context.Context) error {
	resp := r.client.PrivateSubnetsIterator(ctx, &baremetal.ListPrivateSubnetsRequest{
		CloudId:  r.CloudID(),
		Filter:   sdkresolvers.CreateResolverFilter("name", r.Name),
		PageSize: sdkresolvers.DefaultResolverPageSize,
	})
	return r.FindName(resp.TakeAll())
}

type privateSubnetPrivateSubnetOperationsResolver struct {
	client PrivateSubnetClient
	sdkresolvers.BaseNameResolver
}

func PrivateSubnetPrivateSubnetOperationsResolver(name string, client PrivateSubnetClient, opts ...sdkresolvers.ResolveOption) sdkresolvers.Resolver {
	return &privateSubnetPrivateSubnetOperationsResolver{
		client:           client,
		BaseNameResolver: sdkresolvers.NewBaseNameResolver(name, "PrivateSubnetPrivateSubnetOperations", opts...),
	}
}

func (r *privateSubnetPrivateSubnetOperationsResolver) Run(ctx context.Context) error {
	resp := r.client.PrivateSubnetOperationsIterator(ctx, &baremetal.ListPrivateSubnetOperationsRequest{
		CloudId: r.CloudID(),

		PageSize: sdkresolvers.DefaultResolverPageSize,
	})
	return r.FindName(resp.TakeAll())
}
