// Code generated by sdkgen-v2. DO NOT EDIT.
package baremetalsdk

import (
	"context"

	baremetal "github.com/yandex-cloud/go-genproto/yandex/cloud/baremetal/v2"
	"github.com/yandex-cloud/go-sdk/v2/pkg/iterator"
	"google.golang.org/grpc"
)

type PrivateCloudConnectionClientIterator interface {
	PrivateCloudConnectionsIterator(context.Context, *baremetal.ListPrivateCloudConnectionsRequest, ...grpc.CallOption) *iterator.Iterator[*baremetal.ListPrivateCloudConnectionsRequest, *baremetal.PrivateCloudConnection]
}

type privateCloudConnectionServiceListPrivateCloudConnectionsInternal struct {
	*baremetal.ListPrivateCloudConnectionsResponse
}

func (r privateCloudConnectionServiceListPrivateCloudConnectionsInternal) Items() []*baremetal.PrivateCloudConnection {
	return r.ListPrivateCloudConnectionsResponse.PrivateCloudConnections
}

func (c privateCloudConnectionClient) PrivateCloudConnectionsIterator(ctx context.Context, req *baremetal.ListPrivateCloudConnectionsRequest, opts ...grpc.CallOption) *iterator.Iterator[*baremetal.ListPrivateCloudConnectionsRequest, *baremetal.PrivateCloudConnection] {
	return iterator.NewIterator[*baremetal.ListPrivateCloudConnectionsRequest, *baremetal.PrivateCloudConnection](ctx, req,
		func(ctx context.Context, req *baremetal.ListPrivateCloudConnectionsRequest, opts ...grpc.CallOption) (iterator.PageResponse[*baremetal.PrivateCloudConnection], error) {
			resp, err := c.ListPrivateCloudConnections(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return privateCloudConnectionServiceListPrivateCloudConnectionsInternal{resp}, nil
		})
}
