// Code generated by sdkgen-v2. DO NOT EDIT.
package baremetalsdk

import (
	"context"

	baremetal "github.com/yandex-cloud/go-genproto/yandex/cloud/baremetal/v2"
	operation "github.com/yandex-cloud/go-genproto/yandex/cloud/operation"
	"github.com/yandex-cloud/go-sdk/v2/pkg/iterator"
	"google.golang.org/grpc"
)

type PublicSubnetClientIterator interface {
	PublicSubnetsIterator(context.Context, *baremetal.ListPublicSubnetsRequest, ...grpc.CallOption) *iterator.Iterator[*baremetal.ListPublicSubnetsRequest, *baremetal.PublicSubnet]
	PublicSubnetOperationsIterator(context.Context, *baremetal.ListPublicSubnetOperationsRequest, ...grpc.CallOption) *iterator.Iterator[*baremetal.ListPublicSubnetOperationsRequest, *operation.Operation]
}

type publicSubnetServiceListPublicSubnetsInternal struct {
	*baremetal.ListPublicSubnetsResponse
}

func (r publicSubnetServiceListPublicSubnetsInternal) Items() []*baremetal.PublicSubnet {
	return r.ListPublicSubnetsResponse.PublicSubnets
}

func (c publicSubnetClient) PublicSubnetsIterator(ctx context.Context, req *baremetal.ListPublicSubnetsRequest, opts ...grpc.CallOption) *iterator.Iterator[*baremetal.ListPublicSubnetsRequest, *baremetal.PublicSubnet] {
	return iterator.NewIterator[*baremetal.ListPublicSubnetsRequest, *baremetal.PublicSubnet](ctx, req,
		func(ctx context.Context, req *baremetal.ListPublicSubnetsRequest, opts ...grpc.CallOption) (iterator.PageResponse[*baremetal.PublicSubnet], error) {
			resp, err := c.ListPublicSubnets(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return publicSubnetServiceListPublicSubnetsInternal{resp}, nil
		})
}

type publicSubnetServiceListPublicSubnetOperationsInternal struct {
	*baremetal.ListPublicSubnetOperationsResponse
}

func (r publicSubnetServiceListPublicSubnetOperationsInternal) Items() []*operation.Operation {
	return r.ListPublicSubnetOperationsResponse.Operations
}

func (c publicSubnetClient) PublicSubnetOperationsIterator(ctx context.Context, req *baremetal.ListPublicSubnetOperationsRequest, opts ...grpc.CallOption) *iterator.Iterator[*baremetal.ListPublicSubnetOperationsRequest, *operation.Operation] {
	return iterator.NewIterator[*baremetal.ListPublicSubnetOperationsRequest, *operation.Operation](ctx, req,
		func(ctx context.Context, req *baremetal.ListPublicSubnetOperationsRequest, opts ...grpc.CallOption) (iterator.PageResponse[*operation.Operation], error) {
			resp, err := c.ListPublicSubnetOperations(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return publicSubnetServiceListPublicSubnetOperationsInternal{resp}, nil
		})
}
