// Code generated by sdkgen-v2. DO NOT EDIT.
package baremetalsdk

import (
	"context"

	baremetal "github.com/yandex-cloud/go-genproto/yandex/cloud/baremetal/v2"
	operation "github.com/yandex-cloud/go-genproto/yandex/cloud/operation"
	sdkop "github.com/yandex-cloud/go-sdk/v2/pkg/operation"
	"github.com/yandex-cloud/go-sdk/v2/pkg/transport"
	"google.golang.org/grpc"
	proto "google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// PublicPrefixPoolClient provides methods for managing PublicPrefixPool resources of Yandex.Cloud Baremetal.
type PublicPrefixPoolClient interface {
	PublicPrefixPoolClientIterator
	GetPublicPrefixPool(context.Context, *baremetal.GetPublicPrefixPoolRequest, ...grpc.CallOption) (*baremetal.PublicPrefixPool, error)
	ListPublicPrefixPools(context.Context, *baremetal.ListPublicPrefixPoolsRequest, ...grpc.CallOption) (*baremetal.ListPublicPrefixPoolsResponse, error)
	UpdatePublicPrefixPool(context.Context, *baremetal.UpdatePublicPrefixPoolRequest, ...grpc.CallOption) (*PublicPrefixPoolUpdatePublicPrefixPoolOperation, error)
}

var _ PublicPrefixPoolClient = publicPrefixPoolClient{}

type publicPrefixPoolClient struct {
	connector transport.Connector
}

// NewPublicPrefixPoolClient returns PublicPrefixPoolClient implementation.
func NewPublicPrefixPoolClient(connector transport.Connector) PublicPrefixPoolClient {
	return publicPrefixPoolClient{connector}
}

// GetPublicPrefixPool is an operation of Yandex.Cloud Baremetal PublicPrefixPool service.
func (c publicPrefixPoolClient) GetPublicPrefixPool(ctx context.Context, in *baremetal.GetPublicPrefixPoolRequest, opts ...grpc.CallOption) (*baremetal.PublicPrefixPool, error) {
	connection, err := c.connector.GetConnection(ctx, PublicPrefixPoolGetPublicPrefixPool, opts...)
	if err != nil {
		return nil, err
	}
	return baremetal.NewPublicPrefixPoolServiceClient(connection).GetPublicPrefixPool(ctx, in, opts...)
}

// ListPublicPrefixPools is an operation of Yandex.Cloud Baremetal PublicPrefixPool service.
func (c publicPrefixPoolClient) ListPublicPrefixPools(ctx context.Context, in *baremetal.ListPublicPrefixPoolsRequest, opts ...grpc.CallOption) (*baremetal.ListPublicPrefixPoolsResponse, error) {
	connection, err := c.connector.GetConnection(ctx, PublicPrefixPoolListPublicPrefixPools, opts...)
	if err != nil {
		return nil, err
	}
	return baremetal.NewPublicPrefixPoolServiceClient(connection).ListPublicPrefixPools(ctx, in, opts...)
}

// PublicPrefixPoolUpdatePublicPrefixPoolOperation is used to monitor the state of UpdatePublicPrefixPool operations.
type PublicPrefixPoolUpdatePublicPrefixPoolOperation struct {
	sdkop.Operation
}

// Metadata retrieves the operation metadata.
func (o *PublicPrefixPoolUpdatePublicPrefixPoolOperation) Metadata() *baremetal.UpdatePublicPrefixPoolMetadata {
	return o.Operation.Metadata().(*baremetal.UpdatePublicPrefixPoolMetadata)
}

// Response retrieves the operation response.
func (o *PublicPrefixPoolUpdatePublicPrefixPoolOperation) Response() *baremetal.PublicPrefixPool {
	return o.Operation.Response().(*baremetal.PublicPrefixPool)
}

// Wait polls the operation until it's done.
func (o *PublicPrefixPoolUpdatePublicPrefixPoolOperation) Wait(ctx context.Context, opts ...grpc.CallOption) (*baremetal.PublicPrefixPool, error) {
	abstract, err := o.Operation.Wait(ctx, opts...)
	response, _ := abstract.(*baremetal.PublicPrefixPool)
	return response, err
}

// WaitInterval polls the operation until it's done with custom interval.
func (o *PublicPrefixPoolUpdatePublicPrefixPoolOperation) WaitInterval(ctx context.Context, pollInterval sdkop.PollIntervalFunc, opts ...grpc.CallOption) (*baremetal.PublicPrefixPool, error) {
	abstract, err := o.Operation.WaitInterval(ctx, pollInterval, opts...)
	response, _ := abstract.(*baremetal.PublicPrefixPool)
	return response, err
}

// UpdatePublicPrefixPool is an operation of Yandex.Cloud Baremetal PublicPrefixPool service.
// It returns an object which should be used to monitor the operation state.
func (c publicPrefixPoolClient) UpdatePublicPrefixPool(ctx context.Context, in *baremetal.UpdatePublicPrefixPoolRequest, opts ...grpc.CallOption) (*PublicPrefixPoolUpdatePublicPrefixPoolOperation, error) {
	connection, err := c.connector.GetConnection(ctx, PublicPrefixPoolUpdatePublicPrefixPool, opts...)
	if err != nil {
		return nil, err
	}
	pb, err := baremetal.NewPublicPrefixPoolServiceClient(connection).UpdatePublicPrefixPool(ctx, in, opts...)
	if err != nil {
		return nil, err
	}
	op, err := sdkop.NewOperation(pb, &sdkop.Concretization{
		Poll: c.pollOperation,
		GetResourceID: func(metadata proto.Message) string {
			return metadata.(*baremetal.UpdatePublicPrefixPoolMetadata).GetPublicPrefixPoolId()
		},
		MetadataType: (*baremetal.UpdatePublicPrefixPoolMetadata)(nil),
		ResponseType: (*baremetal.PublicPrefixPool)(nil),
	})
	if err != nil {
		return nil, err
	}
	return &PublicPrefixPoolUpdatePublicPrefixPoolOperation{*op}, nil
}

// pollOperation returns the current state of the polled operation.
func (c publicPrefixPoolClient) pollOperation(ctx context.Context, operationId string, opts ...grpc.CallOption) (sdkop.YCOperation, error) {
	connection, err := c.connector.GetConnection(ctx, PublicPrefixPoolOperationPoller, opts...)
	if err != nil {
		return nil, err
	}
	return operation.NewOperationServiceClient(connection).Get(ctx, &operation.GetOperationRequest{OperationId: operationId}, opts...)
}

var (
	PublicPrefixPoolGetPublicPrefixPool    = protoreflect.FullName("yandex.cloud.baremetal.v2.PublicPrefixPoolService.GetPublicPrefixPool")
	PublicPrefixPoolListPublicPrefixPools  = protoreflect.FullName("yandex.cloud.baremetal.v2.PublicPrefixPoolService.ListPublicPrefixPools")
	PublicPrefixPoolUpdatePublicPrefixPool = protoreflect.FullName("yandex.cloud.baremetal.v2.PublicPrefixPoolService.UpdatePublicPrefixPool")
	PublicPrefixPoolOperationPoller        = protoreflect.FullName("yandex.cloud.operation.OperationService.Get")
)
