// Code generated by sdkgen-v2. DO NOT EDIT.
package baremetalsdk

import (
	"context"

	baremetal "github.com/yandex-cloud/go-genproto/yandex/cloud/baremetal/v2"
	"github.com/yandex-cloud/go-sdk/v2/pkg/sdkresolvers"
)

type publicSubnetPublicSubnetsResolver struct {
	client PublicSubnetClient
	sdkresolvers.BaseNameResolver
}

func PublicSubnetPublicSubnetsResolver(name string, client PublicSubnetClient, opts ...sdkresolvers.ResolveOption) sdkresolvers.Resolver {
	return &publicSubnetPublicSubnetsResolver{
		client:           client,
		BaseNameResolver: sdkresolvers.NewBaseNameResolver(name, "PublicSubnetPublicSubnets", opts...),
	}
}

func (r *publicSubnetPublicSubnetsResolver) Run(ctx context.Context) error {
	resp := r.client.PublicSubnetsIterator(ctx, &baremetal.ListPublicSubnetsRequest{
		CloudId:  r.CloudID(),
		Filter:   sdkresolvers.CreateResolverFilter("name", r.Name),
		PageSize: sdkresolvers.DefaultResolverPageSize,
	})
	return r.FindName(resp.TakeAll())
}

type publicSubnetPublicSubnetOperationsResolver struct {
	client PublicSubnetClient
	sdkresolvers.BaseNameResolver
}

func PublicSubnetPublicSubnetOperationsResolver(name string, client PublicSubnetClient, opts ...sdkresolvers.ResolveOption) sdkresolvers.Resolver {
	return &publicSubnetPublicSubnetOperationsResolver{
		client:           client,
		BaseNameResolver: sdkresolvers.NewBaseNameResolver(name, "PublicSubnetPublicSubnetOperations", opts...),
	}
}

func (r *publicSubnetPublicSubnetOperationsResolver) Run(ctx context.Context) error {
	resp := r.client.PublicSubnetOperationsIterator(ctx, &baremetal.ListPublicSubnetOperationsRequest{
		CloudId: r.CloudID(),

		PageSize: sdkresolvers.DefaultResolverPageSize,
	})
	return r.FindName(resp.TakeAll())
}
