// Code generated by sdkgen-v2. DO NOT EDIT.
package baremetalsdk

import (
	"context"

	baremetal "github.com/yandex-cloud/go-genproto/yandex/cloud/baremetal/v2"
	"github.com/yandex-cloud/go-sdk/v2/pkg/iterator"
	"google.golang.org/grpc"
)

type RentalPeriodClientIterator interface {
	RentalPeriodsIterator(context.Context, *baremetal.ListRentalPeriodsRequest, ...grpc.CallOption) *iterator.Iterator[*baremetal.ListRentalPeriodsRequest, *baremetal.RentalPeriod]
}

type rentalPeriodServiceListRentalPeriodsInternal struct {
	*baremetal.ListRentalPeriodsResponse
}

func (r rentalPeriodServiceListRentalPeriodsInternal) Items() []*baremetal.RentalPeriod {
	return r.ListRentalPeriodsResponse.RentalPeriods
}

func (c rentalPeriodClient) RentalPeriodsIterator(ctx context.Context, req *baremetal.ListRentalPeriodsRequest, opts ...grpc.CallOption) *iterator.Iterator[*baremetal.ListRentalPeriodsRequest, *baremetal.RentalPeriod] {
	return iterator.NewIterator[*baremetal.ListRentalPeriodsRequest, *baremetal.RentalPeriod](ctx, req,
		func(ctx context.Context, req *baremetal.ListRentalPeriodsRequest, opts ...grpc.CallOption) (iterator.PageResponse[*baremetal.RentalPeriod], error) {
			resp, err := c.ListRentalPeriods(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return rentalPeriodServiceListRentalPeriodsInternal{resp}, nil
		})
}
