// Code generated by sdkgen-v2. DO NOT EDIT.
package baremetalsdk

import (
	"context"

	baremetal "github.com/yandex-cloud/go-genproto/yandex/cloud/baremetal/v2"
	operation "github.com/yandex-cloud/go-genproto/yandex/cloud/operation"
	"github.com/yandex-cloud/go-sdk/v2/pkg/iterator"
	"google.golang.org/grpc"
)

type ServerClientIterator interface {
	ServersIterator(context.Context, *baremetal.ListServersRequest, ...grpc.CallOption) *iterator.Iterator[*baremetal.ListServersRequest, *baremetal.Server]
	ServerOperationsIterator(context.Context, *baremetal.ListServerOperationsRequest, ...grpc.CallOption) *iterator.Iterator[*baremetal.ListServerOperationsRequest, *operation.Operation]
}

type serverServiceListServersInternal struct {
	*baremetal.ListServersResponse
}

func (r serverServiceListServersInternal) Items() []*baremetal.Server {
	return r.ListServersResponse.Servers
}

func (c serverClient) ServersIterator(ctx context.Context, req *baremetal.ListServersRequest, opts ...grpc.CallOption) *iterator.Iterator[*baremetal.ListServersRequest, *baremetal.Server] {
	return iterator.NewIterator[*baremetal.ListServersRequest, *baremetal.Server](ctx, req,
		func(ctx context.Context, req *baremetal.ListServersRequest, opts ...grpc.CallOption) (iterator.PageResponse[*baremetal.Server], error) {
			resp, err := c.ListServers(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return serverServiceListServersInternal{resp}, nil
		})
}

type serverServiceListServerOperationsInternal struct {
	*baremetal.ListServerOperationsResponse
}

func (r serverServiceListServerOperationsInternal) Items() []*operation.Operation {
	return r.ListServerOperationsResponse.Operations
}

func (c serverClient) ServerOperationsIterator(ctx context.Context, req *baremetal.ListServerOperationsRequest, opts ...grpc.CallOption) *iterator.Iterator[*baremetal.ListServerOperationsRequest, *operation.Operation] {
	return iterator.NewIterator[*baremetal.ListServerOperationsRequest, *operation.Operation](ctx, req,
		func(ctx context.Context, req *baremetal.ListServerOperationsRequest, opts ...grpc.CallOption) (iterator.PageResponse[*operation.Operation], error) {
			resp, err := c.ListServerOperations(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return serverServiceListServerOperationsInternal{resp}, nil
		})
}
