// Code generated by sdkgen-v2. DO NOT EDIT.
package baremetalsdk

import (
	"context"

	baremetal "github.com/yandex-cloud/go-genproto/yandex/cloud/baremetal/v2"
	operation "github.com/yandex-cloud/go-genproto/yandex/cloud/operation"
	sdkop "github.com/yandex-cloud/go-sdk/v2/pkg/operation"
	"github.com/yandex-cloud/go-sdk/v2/pkg/transport"
	"google.golang.org/grpc"
	proto "google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// ServerClient provides methods for managing Server resources of Yandex.Cloud Baremetal.
type ServerClient interface {
	ServerClientIterator
	GetServer(context.Context, *baremetal.GetServerRequest, ...grpc.CallOption) (*baremetal.Server, error)
	ListServers(context.Context, *baremetal.ListServersRequest, ...grpc.CallOption) (*baremetal.ListServersResponse, error)
	CreateServer(context.Context, *baremetal.CreateServerRequest, ...grpc.CallOption) (*ServerCreateServerOperation, error)
	BatchCreateServers(context.Context, *baremetal.BatchCreateServersRequest, ...grpc.CallOption) (*ServerBatchCreateServersOperation, error)
	UpdateServer(context.Context, *baremetal.UpdateServerRequest, ...grpc.CallOption) (*ServerUpdateServerOperation, error)
	DeleteServer(context.Context, *baremetal.DeleteServerRequest, ...grpc.CallOption) (*ServerDeleteServerOperation, error)
	PowerOffServer(context.Context, *baremetal.PowerOffServerRequest, ...grpc.CallOption) (*ServerPowerOffServerOperation, error)
	PowerOnServer(context.Context, *baremetal.PowerOnServerRequest, ...grpc.CallOption) (*ServerPowerOnServerOperation, error)
	RebootServer(context.Context, *baremetal.RebootServerRequest, ...grpc.CallOption) (*ServerRebootServerOperation, error)
	ReinstallServer(context.Context, *baremetal.ReinstallServerRequest, ...grpc.CallOption) (*ServerReinstallServerOperation, error)
	RenewServerRental(context.Context, *baremetal.RenewServerRentalRequest, ...grpc.CallOption) (*ServerRenewServerRentalOperation, error)
	ListServerOperations(context.Context, *baremetal.ListServerOperationsRequest, ...grpc.CallOption) (*baremetal.ListServerOperationsResponse, error)
}

var _ ServerClient = serverClient{}

type serverClient struct {
	connector transport.Connector
}

// NewServerClient returns ServerClient implementation.
func NewServerClient(connector transport.Connector) ServerClient {
	return serverClient{connector}
}

// GetServer is an operation of Yandex.Cloud Baremetal Server service.
func (c serverClient) GetServer(ctx context.Context, in *baremetal.GetServerRequest, opts ...grpc.CallOption) (*baremetal.Server, error) {
	connection, err := c.connector.GetConnection(ctx, ServerGetServer, opts...)
	if err != nil {
		return nil, err
	}
	return baremetal.NewServerServiceClient(connection).GetServer(ctx, in, opts...)
}

// ListServers is an operation of Yandex.Cloud Baremetal Server service.
func (c serverClient) ListServers(ctx context.Context, in *baremetal.ListServersRequest, opts ...grpc.CallOption) (*baremetal.ListServersResponse, error) {
	connection, err := c.connector.GetConnection(ctx, ServerListServers, opts...)
	if err != nil {
		return nil, err
	}
	return baremetal.NewServerServiceClient(connection).ListServers(ctx, in, opts...)
}

// ServerCreateServerOperation is used to monitor the state of CreateServer operations.
type ServerCreateServerOperation struct {
	sdkop.Operation
}

// Metadata retrieves the operation metadata.
func (o *ServerCreateServerOperation) Metadata() *baremetal.CreateServerMetadata {
	return o.Operation.Metadata().(*baremetal.CreateServerMetadata)
}

// Response retrieves the operation response.
func (o *ServerCreateServerOperation) Response() *baremetal.Server {
	return o.Operation.Response().(*baremetal.Server)
}

// Wait polls the operation until it's done.
func (o *ServerCreateServerOperation) Wait(ctx context.Context, opts ...grpc.CallOption) (*baremetal.Server, error) {
	abstract, err := o.Operation.Wait(ctx, opts...)
	response, _ := abstract.(*baremetal.Server)
	return response, err
}

// WaitInterval polls the operation until it's done with custom interval.
func (o *ServerCreateServerOperation) WaitInterval(ctx context.Context, pollInterval sdkop.PollIntervalFunc, opts ...grpc.CallOption) (*baremetal.Server, error) {
	abstract, err := o.Operation.WaitInterval(ctx, pollInterval, opts...)
	response, _ := abstract.(*baremetal.Server)
	return response, err
}

// CreateServer is an operation of Yandex.Cloud Baremetal Server service.
// It returns an object which should be used to monitor the operation state.
func (c serverClient) CreateServer(ctx context.Context, in *baremetal.CreateServerRequest, opts ...grpc.CallOption) (*ServerCreateServerOperation, error) {
	connection, err := c.connector.GetConnection(ctx, ServerCreateServer, opts...)
	if err != nil {
		return nil, err
	}
	pb, err := baremetal.NewServerServiceClient(connection).CreateServer(ctx, in, opts...)
	if err != nil {
		return nil, err
	}
	op, err := sdkop.NewOperation(pb, &sdkop.Concretization{
		Poll: c.pollOperation,
		GetResourceID: func(metadata proto.Message) string {
			return metadata.(*baremetal.CreateServerMetadata).GetServerId()
		},
		MetadataType: (*baremetal.CreateServerMetadata)(nil),
		ResponseType: (*baremetal.Server)(nil),
	})
	if err != nil {
		return nil, err
	}
	return &ServerCreateServerOperation{*op}, nil
}

// ServerBatchCreateServersOperation is used to monitor the state of BatchCreateServers operations.
type ServerBatchCreateServersOperation struct {
	sdkop.Operation
}

// Metadata retrieves the operation metadata.
func (o *ServerBatchCreateServersOperation) Metadata() *baremetal.BatchCreateServersMetadata {
	return o.Operation.Metadata().(*baremetal.BatchCreateServersMetadata)
}

// Response retrieves the operation response.
func (o *ServerBatchCreateServersOperation) Response() *baremetal.BatchCreateServersResponse {
	return o.Operation.Response().(*baremetal.BatchCreateServersResponse)
}

// Wait polls the operation until it's done.
func (o *ServerBatchCreateServersOperation) Wait(ctx context.Context, opts ...grpc.CallOption) (*baremetal.BatchCreateServersResponse, error) {
	abstract, err := o.Operation.Wait(ctx, opts...)
	response, _ := abstract.(*baremetal.BatchCreateServersResponse)
	return response, err
}

// WaitInterval polls the operation until it's done with custom interval.
func (o *ServerBatchCreateServersOperation) WaitInterval(ctx context.Context, pollInterval sdkop.PollIntervalFunc, opts ...grpc.CallOption) (*baremetal.BatchCreateServersResponse, error) {
	abstract, err := o.Operation.WaitInterval(ctx, pollInterval, opts...)
	response, _ := abstract.(*baremetal.BatchCreateServersResponse)
	return response, err
}

// BatchCreateServers is an operation of Yandex.Cloud Baremetal Server service.
// It returns an object which should be used to monitor the operation state.
func (c serverClient) BatchCreateServers(ctx context.Context, in *baremetal.BatchCreateServersRequest, opts ...grpc.CallOption) (*ServerBatchCreateServersOperation, error) {
	connection, err := c.connector.GetConnection(ctx, ServerBatchCreateServers, opts...)
	if err != nil {
		return nil, err
	}
	pb, err := baremetal.NewServerServiceClient(connection).BatchCreateServers(ctx, in, opts...)
	if err != nil {
		return nil, err
	}
	op, err := sdkop.NewOperation(pb, &sdkop.Concretization{
		Poll:         c.pollOperation,
		MetadataType: (*baremetal.BatchCreateServersMetadata)(nil),
		ResponseType: (*baremetal.BatchCreateServersResponse)(nil),
	})
	if err != nil {
		return nil, err
	}
	return &ServerBatchCreateServersOperation{*op}, nil
}

// ServerUpdateServerOperation is used to monitor the state of UpdateServer operations.
type ServerUpdateServerOperation struct {
	sdkop.Operation
}

// Metadata retrieves the operation metadata.
func (o *ServerUpdateServerOperation) Metadata() *baremetal.UpdateServerMetadata {
	return o.Operation.Metadata().(*baremetal.UpdateServerMetadata)
}

// Response retrieves the operation response.
func (o *ServerUpdateServerOperation) Response() *baremetal.Server {
	return o.Operation.Response().(*baremetal.Server)
}

// Wait polls the operation until it's done.
func (o *ServerUpdateServerOperation) Wait(ctx context.Context, opts ...grpc.CallOption) (*baremetal.Server, error) {
	abstract, err := o.Operation.Wait(ctx, opts...)
	response, _ := abstract.(*baremetal.Server)
	return response, err
}

// WaitInterval polls the operation until it's done with custom interval.
func (o *ServerUpdateServerOperation) WaitInterval(ctx context.Context, pollInterval sdkop.PollIntervalFunc, opts ...grpc.CallOption) (*baremetal.Server, error) {
	abstract, err := o.Operation.WaitInterval(ctx, pollInterval, opts...)
	response, _ := abstract.(*baremetal.Server)
	return response, err
}

// UpdateServer is an operation of Yandex.Cloud Baremetal Server service.
// It returns an object which should be used to monitor the operation state.
func (c serverClient) UpdateServer(ctx context.Context, in *baremetal.UpdateServerRequest, opts ...grpc.CallOption) (*ServerUpdateServerOperation, error) {
	connection, err := c.connector.GetConnection(ctx, ServerUpdateServer, opts...)
	if err != nil {
		return nil, err
	}
	pb, err := baremetal.NewServerServiceClient(connection).UpdateServer(ctx, in, opts...)
	if err != nil {
		return nil, err
	}
	op, err := sdkop.NewOperation(pb, &sdkop.Concretization{
		Poll: c.pollOperation,
		GetResourceID: func(metadata proto.Message) string {
			return metadata.(*baremetal.UpdateServerMetadata).GetServerId()
		},
		MetadataType: (*baremetal.UpdateServerMetadata)(nil),
		ResponseType: (*baremetal.Server)(nil),
	})
	if err != nil {
		return nil, err
	}
	return &ServerUpdateServerOperation{*op}, nil
}

// ServerDeleteServerOperation is used to monitor the state of DeleteServer operations.
type ServerDeleteServerOperation struct {
	sdkop.Operation
}

// Metadata retrieves the operation metadata.
func (o *ServerDeleteServerOperation) Metadata() *baremetal.DeleteServerByUserMetadata {
	return o.Operation.Metadata().(*baremetal.DeleteServerByUserMetadata)
}

// Response retrieves the operation response.
func (o *ServerDeleteServerOperation) Response() *emptypb.Empty {
	return o.Operation.Response().(*emptypb.Empty)
}

// Wait polls the operation until it's done.
func (o *ServerDeleteServerOperation) Wait(ctx context.Context, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	abstract, err := o.Operation.Wait(ctx, opts...)
	response, _ := abstract.(*emptypb.Empty)
	return response, err
}

// WaitInterval polls the operation until it's done with custom interval.
func (o *ServerDeleteServerOperation) WaitInterval(ctx context.Context, pollInterval sdkop.PollIntervalFunc, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	abstract, err := o.Operation.WaitInterval(ctx, pollInterval, opts...)
	response, _ := abstract.(*emptypb.Empty)
	return response, err
}

// DeleteServer is an operation of Yandex.Cloud Baremetal Server service.
// It returns an object which should be used to monitor the operation state.
func (c serverClient) DeleteServer(ctx context.Context, in *baremetal.DeleteServerRequest, opts ...grpc.CallOption) (*ServerDeleteServerOperation, error) {
	connection, err := c.connector.GetConnection(ctx, ServerDeleteServer, opts...)
	if err != nil {
		return nil, err
	}
	pb, err := baremetal.NewServerServiceClient(connection).DeleteServer(ctx, in, opts...)
	if err != nil {
		return nil, err
	}
	op, err := sdkop.NewOperation(pb, &sdkop.Concretization{
		Poll: c.pollOperation,
		GetResourceID: func(metadata proto.Message) string {
			return metadata.(*baremetal.DeleteServerByUserMetadata).GetServerId()
		},
		MetadataType: (*baremetal.DeleteServerByUserMetadata)(nil),
		ResponseType: (*emptypb.Empty)(nil),
	})
	if err != nil {
		return nil, err
	}
	return &ServerDeleteServerOperation{*op}, nil
}

// ServerPowerOffServerOperation is used to monitor the state of PowerOffServer operations.
type ServerPowerOffServerOperation struct {
	sdkop.Operation
}

// Metadata retrieves the operation metadata.
func (o *ServerPowerOffServerOperation) Metadata() *baremetal.PowerOffServerMetadata {
	return o.Operation.Metadata().(*baremetal.PowerOffServerMetadata)
}

// Response retrieves the operation response.
func (o *ServerPowerOffServerOperation) Response() *emptypb.Empty {
	return o.Operation.Response().(*emptypb.Empty)
}

// Wait polls the operation until it's done.
func (o *ServerPowerOffServerOperation) Wait(ctx context.Context, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	abstract, err := o.Operation.Wait(ctx, opts...)
	response, _ := abstract.(*emptypb.Empty)
	return response, err
}

// WaitInterval polls the operation until it's done with custom interval.
func (o *ServerPowerOffServerOperation) WaitInterval(ctx context.Context, pollInterval sdkop.PollIntervalFunc, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	abstract, err := o.Operation.WaitInterval(ctx, pollInterval, opts...)
	response, _ := abstract.(*emptypb.Empty)
	return response, err
}

// PowerOffServer is an operation of Yandex.Cloud Baremetal Server service.
// It returns an object which should be used to monitor the operation state.
func (c serverClient) PowerOffServer(ctx context.Context, in *baremetal.PowerOffServerRequest, opts ...grpc.CallOption) (*ServerPowerOffServerOperation, error) {
	connection, err := c.connector.GetConnection(ctx, ServerPowerOffServer, opts...)
	if err != nil {
		return nil, err
	}
	pb, err := baremetal.NewServerServiceClient(connection).PowerOffServer(ctx, in, opts...)
	if err != nil {
		return nil, err
	}
	op, err := sdkop.NewOperation(pb, &sdkop.Concretization{
		Poll: c.pollOperation,
		GetResourceID: func(metadata proto.Message) string {
			return metadata.(*baremetal.PowerOffServerMetadata).GetServerId()
		},
		MetadataType: (*baremetal.PowerOffServerMetadata)(nil),
		ResponseType: (*emptypb.Empty)(nil),
	})
	if err != nil {
		return nil, err
	}
	return &ServerPowerOffServerOperation{*op}, nil
}

// ServerPowerOnServerOperation is used to monitor the state of PowerOnServer operations.
type ServerPowerOnServerOperation struct {
	sdkop.Operation
}

// Metadata retrieves the operation metadata.
func (o *ServerPowerOnServerOperation) Metadata() *baremetal.PowerOnServerMetadata {
	return o.Operation.Metadata().(*baremetal.PowerOnServerMetadata)
}

// Response retrieves the operation response.
func (o *ServerPowerOnServerOperation) Response() *emptypb.Empty {
	return o.Operation.Response().(*emptypb.Empty)
}

// Wait polls the operation until it's done.
func (o *ServerPowerOnServerOperation) Wait(ctx context.Context, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	abstract, err := o.Operation.Wait(ctx, opts...)
	response, _ := abstract.(*emptypb.Empty)
	return response, err
}

// WaitInterval polls the operation until it's done with custom interval.
func (o *ServerPowerOnServerOperation) WaitInterval(ctx context.Context, pollInterval sdkop.PollIntervalFunc, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	abstract, err := o.Operation.WaitInterval(ctx, pollInterval, opts...)
	response, _ := abstract.(*emptypb.Empty)
	return response, err
}

// PowerOnServer is an operation of Yandex.Cloud Baremetal Server service.
// It returns an object which should be used to monitor the operation state.
func (c serverClient) PowerOnServer(ctx context.Context, in *baremetal.PowerOnServerRequest, opts ...grpc.CallOption) (*ServerPowerOnServerOperation, error) {
	connection, err := c.connector.GetConnection(ctx, ServerPowerOnServer, opts...)
	if err != nil {
		return nil, err
	}
	pb, err := baremetal.NewServerServiceClient(connection).PowerOnServer(ctx, in, opts...)
	if err != nil {
		return nil, err
	}
	op, err := sdkop.NewOperation(pb, &sdkop.Concretization{
		Poll: c.pollOperation,
		GetResourceID: func(metadata proto.Message) string {
			return metadata.(*baremetal.PowerOnServerMetadata).GetServerId()
		},
		MetadataType: (*baremetal.PowerOnServerMetadata)(nil),
		ResponseType: (*emptypb.Empty)(nil),
	})
	if err != nil {
		return nil, err
	}
	return &ServerPowerOnServerOperation{*op}, nil
}

// ServerRebootServerOperation is used to monitor the state of RebootServer operations.
type ServerRebootServerOperation struct {
	sdkop.Operation
}

// Metadata retrieves the operation metadata.
func (o *ServerRebootServerOperation) Metadata() *baremetal.RebootServerMetadata {
	return o.Operation.Metadata().(*baremetal.RebootServerMetadata)
}

// Response retrieves the operation response.
func (o *ServerRebootServerOperation) Response() *emptypb.Empty {
	return o.Operation.Response().(*emptypb.Empty)
}

// Wait polls the operation until it's done.
func (o *ServerRebootServerOperation) Wait(ctx context.Context, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	abstract, err := o.Operation.Wait(ctx, opts...)
	response, _ := abstract.(*emptypb.Empty)
	return response, err
}

// WaitInterval polls the operation until it's done with custom interval.
func (o *ServerRebootServerOperation) WaitInterval(ctx context.Context, pollInterval sdkop.PollIntervalFunc, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	abstract, err := o.Operation.WaitInterval(ctx, pollInterval, opts...)
	response, _ := abstract.(*emptypb.Empty)
	return response, err
}

// RebootServer is an operation of Yandex.Cloud Baremetal Server service.
// It returns an object which should be used to monitor the operation state.
func (c serverClient) RebootServer(ctx context.Context, in *baremetal.RebootServerRequest, opts ...grpc.CallOption) (*ServerRebootServerOperation, error) {
	connection, err := c.connector.GetConnection(ctx, ServerRebootServer, opts...)
	if err != nil {
		return nil, err
	}
	pb, err := baremetal.NewServerServiceClient(connection).RebootServer(ctx, in, opts...)
	if err != nil {
		return nil, err
	}
	op, err := sdkop.NewOperation(pb, &sdkop.Concretization{
		Poll: c.pollOperation,
		GetResourceID: func(metadata proto.Message) string {
			return metadata.(*baremetal.RebootServerMetadata).GetServerId()
		},
		MetadataType: (*baremetal.RebootServerMetadata)(nil),
		ResponseType: (*emptypb.Empty)(nil),
	})
	if err != nil {
		return nil, err
	}
	return &ServerRebootServerOperation{*op}, nil
}

// ServerReinstallServerOperation is used to monitor the state of ReinstallServer operations.
type ServerReinstallServerOperation struct {
	sdkop.Operation
}

// Metadata retrieves the operation metadata.
func (o *ServerReinstallServerOperation) Metadata() *baremetal.ReinstallServerMetadata {
	return o.Operation.Metadata().(*baremetal.ReinstallServerMetadata)
}

// Response retrieves the operation response.
func (o *ServerReinstallServerOperation) Response() *emptypb.Empty {
	return o.Operation.Response().(*emptypb.Empty)
}

// Wait polls the operation until it's done.
func (o *ServerReinstallServerOperation) Wait(ctx context.Context, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	abstract, err := o.Operation.Wait(ctx, opts...)
	response, _ := abstract.(*emptypb.Empty)
	return response, err
}

// WaitInterval polls the operation until it's done with custom interval.
func (o *ServerReinstallServerOperation) WaitInterval(ctx context.Context, pollInterval sdkop.PollIntervalFunc, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	abstract, err := o.Operation.WaitInterval(ctx, pollInterval, opts...)
	response, _ := abstract.(*emptypb.Empty)
	return response, err
}

// ReinstallServer is an operation of Yandex.Cloud Baremetal Server service.
// It returns an object which should be used to monitor the operation state.
func (c serverClient) ReinstallServer(ctx context.Context, in *baremetal.ReinstallServerRequest, opts ...grpc.CallOption) (*ServerReinstallServerOperation, error) {
	connection, err := c.connector.GetConnection(ctx, ServerReinstallServer, opts...)
	if err != nil {
		return nil, err
	}
	pb, err := baremetal.NewServerServiceClient(connection).ReinstallServer(ctx, in, opts...)
	if err != nil {
		return nil, err
	}
	op, err := sdkop.NewOperation(pb, &sdkop.Concretization{
		Poll: c.pollOperation,
		GetResourceID: func(metadata proto.Message) string {
			return metadata.(*baremetal.ReinstallServerMetadata).GetServerId()
		},
		MetadataType: (*baremetal.ReinstallServerMetadata)(nil),
		ResponseType: (*emptypb.Empty)(nil),
	})
	if err != nil {
		return nil, err
	}
	return &ServerReinstallServerOperation{*op}, nil
}

// ServerRenewServerRentalOperation is used to monitor the state of RenewServerRental operations.
type ServerRenewServerRentalOperation struct {
	sdkop.Operation
}

// Metadata retrieves the operation metadata.
func (o *ServerRenewServerRentalOperation) Metadata() *baremetal.RenewServerRentalMetadata {
	return o.Operation.Metadata().(*baremetal.RenewServerRentalMetadata)
}

// Response retrieves the operation response.
func (o *ServerRenewServerRentalOperation) Response() *baremetal.Server {
	return o.Operation.Response().(*baremetal.Server)
}

// Wait polls the operation until it's done.
func (o *ServerRenewServerRentalOperation) Wait(ctx context.Context, opts ...grpc.CallOption) (*baremetal.Server, error) {
	abstract, err := o.Operation.Wait(ctx, opts...)
	response, _ := abstract.(*baremetal.Server)
	return response, err
}

// WaitInterval polls the operation until it's done with custom interval.
func (o *ServerRenewServerRentalOperation) WaitInterval(ctx context.Context, pollInterval sdkop.PollIntervalFunc, opts ...grpc.CallOption) (*baremetal.Server, error) {
	abstract, err := o.Operation.WaitInterval(ctx, pollInterval, opts...)
	response, _ := abstract.(*baremetal.Server)
	return response, err
}

// RenewServerRental is an operation of Yandex.Cloud Baremetal Server service.
// It returns an object which should be used to monitor the operation state.
func (c serverClient) RenewServerRental(ctx context.Context, in *baremetal.RenewServerRentalRequest, opts ...grpc.CallOption) (*ServerRenewServerRentalOperation, error) {
	connection, err := c.connector.GetConnection(ctx, ServerRenewServerRental, opts...)
	if err != nil {
		return nil, err
	}
	pb, err := baremetal.NewServerServiceClient(connection).RenewServerRental(ctx, in, opts...)
	if err != nil {
		return nil, err
	}
	op, err := sdkop.NewOperation(pb, &sdkop.Concretization{
		Poll: c.pollOperation,
		GetResourceID: func(metadata proto.Message) string {
			return metadata.(*baremetal.RenewServerRentalMetadata).GetServerId()
		},
		MetadataType: (*baremetal.RenewServerRentalMetadata)(nil),
		ResponseType: (*baremetal.Server)(nil),
	})
	if err != nil {
		return nil, err
	}
	return &ServerRenewServerRentalOperation{*op}, nil
}

// ListServerOperations is an operation of Yandex.Cloud Baremetal Server service.
func (c serverClient) ListServerOperations(ctx context.Context, in *baremetal.ListServerOperationsRequest, opts ...grpc.CallOption) (*baremetal.ListServerOperationsResponse, error) {
	connection, err := c.connector.GetConnection(ctx, ServerListServerOperations, opts...)
	if err != nil {
		return nil, err
	}
	return baremetal.NewServerServiceClient(connection).ListServerOperations(ctx, in, opts...)
}

// pollOperation returns the current state of the polled operation.
func (c serverClient) pollOperation(ctx context.Context, operationId string, opts ...grpc.CallOption) (sdkop.YCOperation, error) {
	connection, err := c.connector.GetConnection(ctx, ServerOperationPoller, opts...)
	if err != nil {
		return nil, err
	}
	return operation.NewOperationServiceClient(connection).Get(ctx, &operation.GetOperationRequest{OperationId: operationId}, opts...)
}

var (
	ServerGetServer            = protoreflect.FullName("yandex.cloud.baremetal.v2.ServerService.GetServer")
	ServerListServers          = protoreflect.FullName("yandex.cloud.baremetal.v2.ServerService.ListServers")
	ServerCreateServer         = protoreflect.FullName("yandex.cloud.baremetal.v2.ServerService.CreateServer")
	ServerBatchCreateServers   = protoreflect.FullName("yandex.cloud.baremetal.v2.ServerService.BatchCreateServers")
	ServerUpdateServer         = protoreflect.FullName("yandex.cloud.baremetal.v2.ServerService.UpdateServer")
	ServerDeleteServer         = protoreflect.FullName("yandex.cloud.baremetal.v2.ServerService.DeleteServer")
	ServerPowerOffServer       = protoreflect.FullName("yandex.cloud.baremetal.v2.ServerService.PowerOffServer")
	ServerPowerOnServer        = protoreflect.FullName("yandex.cloud.baremetal.v2.ServerService.PowerOnServer")
	ServerRebootServer         = protoreflect.FullName("yandex.cloud.baremetal.v2.ServerService.RebootServer")
	ServerReinstallServer      = protoreflect.FullName("yandex.cloud.baremetal.v2.ServerService.ReinstallServer")
	ServerRenewServerRental    = protoreflect.FullName("yandex.cloud.baremetal.v2.ServerService.RenewServerRental")
	ServerListServerOperations = protoreflect.FullName("yandex.cloud.baremetal.v2.ServerService.ListServerOperations")
	ServerOperationPoller      = protoreflect.FullName("yandex.cloud.operation.OperationService.Get")
)
