// Code generated by sdkgen-v2. DO NOT EDIT.
package baremetalsdk

import (
	"context"

	baremetal "github.com/yandex-cloud/go-genproto/yandex/cloud/baremetal/v2"
	operation "github.com/yandex-cloud/go-genproto/yandex/cloud/operation"
	sdkop "github.com/yandex-cloud/go-sdk/v2/pkg/operation"
	"github.com/yandex-cloud/go-sdk/v2/pkg/transport"
	"google.golang.org/grpc"
	proto "google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// VrfClient provides methods for managing Vrf resources of Yandex.Cloud Baremetal.
type VrfClient interface {
	VrfClientIterator
	GetVrf(context.Context, *baremetal.GetVrfRequest, ...grpc.CallOption) (*baremetal.Vrf, error)
	ListVrfs(context.Context, *baremetal.ListVrfsRequest, ...grpc.CallOption) (*baremetal.ListVrfsResponse, error)
	CreateVrf(context.Context, *baremetal.CreateVrfRequest, ...grpc.CallOption) (*VrfCreateVrfOperation, error)
	UpdateVrf(context.Context, *baremetal.UpdateVrfRequest, ...grpc.CallOption) (*VrfUpdateVrfOperation, error)
	DeleteVrf(context.Context, *baremetal.DeleteVrfRequest, ...grpc.CallOption) (*VrfDeleteVrfOperation, error)
	ListVrfOperations(context.Context, *baremetal.ListVrfOperationsRequest, ...grpc.CallOption) (*baremetal.ListVrfOperationsResponse, error)
}

var _ VrfClient = vrfClient{}

type vrfClient struct {
	connector transport.Connector
}

// NewVrfClient returns VrfClient implementation.
func NewVrfClient(connector transport.Connector) VrfClient {
	return vrfClient{connector}
}

// GetVrf is an operation of Yandex.Cloud Baremetal Vrf service.
func (c vrfClient) GetVrf(ctx context.Context, in *baremetal.GetVrfRequest, opts ...grpc.CallOption) (*baremetal.Vrf, error) {
	connection, err := c.connector.GetConnection(ctx, VrfGetVrf, opts...)
	if err != nil {
		return nil, err
	}
	return baremetal.NewVrfServiceClient(connection).GetVrf(ctx, in, opts...)
}

// ListVrfs is an operation of Yandex.Cloud Baremetal Vrf service.
func (c vrfClient) ListVrfs(ctx context.Context, in *baremetal.ListVrfsRequest, opts ...grpc.CallOption) (*baremetal.ListVrfsResponse, error) {
	connection, err := c.connector.GetConnection(ctx, VrfListVrfs, opts...)
	if err != nil {
		return nil, err
	}
	return baremetal.NewVrfServiceClient(connection).ListVrfs(ctx, in, opts...)
}

// VrfCreateVrfOperation is used to monitor the state of CreateVrf operations.
type VrfCreateVrfOperation struct {
	sdkop.Operation
}

// Metadata retrieves the operation metadata.
func (o *VrfCreateVrfOperation) Metadata() *baremetal.CreateVrfMetadata {
	return o.Operation.Metadata().(*baremetal.CreateVrfMetadata)
}

// Response retrieves the operation response.
func (o *VrfCreateVrfOperation) Response() *baremetal.Vrf {
	return o.Operation.Response().(*baremetal.Vrf)
}

// Wait polls the operation until it's done.
func (o *VrfCreateVrfOperation) Wait(ctx context.Context, opts ...grpc.CallOption) (*baremetal.Vrf, error) {
	abstract, err := o.Operation.Wait(ctx, opts...)
	response, _ := abstract.(*baremetal.Vrf)
	return response, err
}

// WaitInterval polls the operation until it's done with custom interval.
func (o *VrfCreateVrfOperation) WaitInterval(ctx context.Context, pollInterval sdkop.PollIntervalFunc, opts ...grpc.CallOption) (*baremetal.Vrf, error) {
	abstract, err := o.Operation.WaitInterval(ctx, pollInterval, opts...)
	response, _ := abstract.(*baremetal.Vrf)
	return response, err
}

// CreateVrf is an operation of Yandex.Cloud Baremetal Vrf service.
// It returns an object which should be used to monitor the operation state.
func (c vrfClient) CreateVrf(ctx context.Context, in *baremetal.CreateVrfRequest, opts ...grpc.CallOption) (*VrfCreateVrfOperation, error) {
	connection, err := c.connector.GetConnection(ctx, VrfCreateVrf, opts...)
	if err != nil {
		return nil, err
	}
	pb, err := baremetal.NewVrfServiceClient(connection).CreateVrf(ctx, in, opts...)
	if err != nil {
		return nil, err
	}
	op, err := sdkop.NewOperation(pb, &sdkop.Concretization{
		Poll: c.pollOperation,
		GetResourceID: func(metadata proto.Message) string {
			return metadata.(*baremetal.CreateVrfMetadata).GetVrfId()
		},
		MetadataType: (*baremetal.CreateVrfMetadata)(nil),
		ResponseType: (*baremetal.Vrf)(nil),
	})
	if err != nil {
		return nil, err
	}
	return &VrfCreateVrfOperation{*op}, nil
}

// VrfUpdateVrfOperation is used to monitor the state of UpdateVrf operations.
type VrfUpdateVrfOperation struct {
	sdkop.Operation
}

// Metadata retrieves the operation metadata.
func (o *VrfUpdateVrfOperation) Metadata() *baremetal.UpdateVrfMetadata {
	return o.Operation.Metadata().(*baremetal.UpdateVrfMetadata)
}

// Response retrieves the operation response.
func (o *VrfUpdateVrfOperation) Response() *baremetal.Vrf {
	return o.Operation.Response().(*baremetal.Vrf)
}

// Wait polls the operation until it's done.
func (o *VrfUpdateVrfOperation) Wait(ctx context.Context, opts ...grpc.CallOption) (*baremetal.Vrf, error) {
	abstract, err := o.Operation.Wait(ctx, opts...)
	response, _ := abstract.(*baremetal.Vrf)
	return response, err
}

// WaitInterval polls the operation until it's done with custom interval.
func (o *VrfUpdateVrfOperation) WaitInterval(ctx context.Context, pollInterval sdkop.PollIntervalFunc, opts ...grpc.CallOption) (*baremetal.Vrf, error) {
	abstract, err := o.Operation.WaitInterval(ctx, pollInterval, opts...)
	response, _ := abstract.(*baremetal.Vrf)
	return response, err
}

// UpdateVrf is an operation of Yandex.Cloud Baremetal Vrf service.
// It returns an object which should be used to monitor the operation state.
func (c vrfClient) UpdateVrf(ctx context.Context, in *baremetal.UpdateVrfRequest, opts ...grpc.CallOption) (*VrfUpdateVrfOperation, error) {
	connection, err := c.connector.GetConnection(ctx, VrfUpdateVrf, opts...)
	if err != nil {
		return nil, err
	}
	pb, err := baremetal.NewVrfServiceClient(connection).UpdateVrf(ctx, in, opts...)
	if err != nil {
		return nil, err
	}
	op, err := sdkop.NewOperation(pb, &sdkop.Concretization{
		Poll: c.pollOperation,
		GetResourceID: func(metadata proto.Message) string {
			return metadata.(*baremetal.UpdateVrfMetadata).GetVrfId()
		},
		MetadataType: (*baremetal.UpdateVrfMetadata)(nil),
		ResponseType: (*baremetal.Vrf)(nil),
	})
	if err != nil {
		return nil, err
	}
	return &VrfUpdateVrfOperation{*op}, nil
}

// VrfDeleteVrfOperation is used to monitor the state of DeleteVrf operations.
type VrfDeleteVrfOperation struct {
	sdkop.Operation
}

// Metadata retrieves the operation metadata.
func (o *VrfDeleteVrfOperation) Metadata() *baremetal.DeleteVrfMetadata {
	return o.Operation.Metadata().(*baremetal.DeleteVrfMetadata)
}

// Response retrieves the operation response.
func (o *VrfDeleteVrfOperation) Response() *emptypb.Empty {
	return o.Operation.Response().(*emptypb.Empty)
}

// Wait polls the operation until it's done.
func (o *VrfDeleteVrfOperation) Wait(ctx context.Context, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	abstract, err := o.Operation.Wait(ctx, opts...)
	response, _ := abstract.(*emptypb.Empty)
	return response, err
}

// WaitInterval polls the operation until it's done with custom interval.
func (o *VrfDeleteVrfOperation) WaitInterval(ctx context.Context, pollInterval sdkop.PollIntervalFunc, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	abstract, err := o.Operation.WaitInterval(ctx, pollInterval, opts...)
	response, _ := abstract.(*emptypb.Empty)
	return response, err
}

// DeleteVrf is an operation of Yandex.Cloud Baremetal Vrf service.
// It returns an object which should be used to monitor the operation state.
func (c vrfClient) DeleteVrf(ctx context.Context, in *baremetal.DeleteVrfRequest, opts ...grpc.CallOption) (*VrfDeleteVrfOperation, error) {
	connection, err := c.connector.GetConnection(ctx, VrfDeleteVrf, opts...)
	if err != nil {
		return nil, err
	}
	pb, err := baremetal.NewVrfServiceClient(connection).DeleteVrf(ctx, in, opts...)
	if err != nil {
		return nil, err
	}
	op, err := sdkop.NewOperation(pb, &sdkop.Concretization{
		Poll: c.pollOperation,
		GetResourceID: func(metadata proto.Message) string {
			return metadata.(*baremetal.DeleteVrfMetadata).GetVrfId()
		},
		MetadataType: (*baremetal.DeleteVrfMetadata)(nil),
		ResponseType: (*emptypb.Empty)(nil),
	})
	if err != nil {
		return nil, err
	}
	return &VrfDeleteVrfOperation{*op}, nil
}

// ListVrfOperations is an operation of Yandex.Cloud Baremetal Vrf service.
func (c vrfClient) ListVrfOperations(ctx context.Context, in *baremetal.ListVrfOperationsRequest, opts ...grpc.CallOption) (*baremetal.ListVrfOperationsResponse, error) {
	connection, err := c.connector.GetConnection(ctx, VrfListVrfOperations, opts...)
	if err != nil {
		return nil, err
	}
	return baremetal.NewVrfServiceClient(connection).ListVrfOperations(ctx, in, opts...)
}

// pollOperation returns the current state of the polled operation.
func (c vrfClient) pollOperation(ctx context.Context, operationId string, opts ...grpc.CallOption) (sdkop.YCOperation, error) {
	connection, err := c.connector.GetConnection(ctx, VrfOperationPoller, opts...)
	if err != nil {
		return nil, err
	}
	return operation.NewOperationServiceClient(connection).Get(ctx, &operation.GetOperationRequest{OperationId: operationId}, opts...)
}

var (
	VrfGetVrf            = protoreflect.FullName("yandex.cloud.baremetal.v2.VrfService.GetVrf")
	VrfListVrfs          = protoreflect.FullName("yandex.cloud.baremetal.v2.VrfService.ListVrfs")
	VrfCreateVrf         = protoreflect.FullName("yandex.cloud.baremetal.v2.VrfService.CreateVrf")
	VrfUpdateVrf         = protoreflect.FullName("yandex.cloud.baremetal.v2.VrfService.UpdateVrf")
	VrfDeleteVrf         = protoreflect.FullName("yandex.cloud.baremetal.v2.VrfService.DeleteVrf")
	VrfListVrfOperations = protoreflect.FullName("yandex.cloud.baremetal.v2.VrfService.ListVrfOperations")
	VrfOperationPoller   = protoreflect.FullName("yandex.cloud.operation.OperationService.Get")
)
