// Code generated by sdkgen-v2. DO NOT EDIT.
package baremetalsdk

import (
	"context"

	baremetal "github.com/yandex-cloud/go-genproto/yandex/cloud/baremetal/v2"
	"github.com/yandex-cloud/go-sdk/v2/pkg/sdkresolvers"
)

type vrfVrfsResolver struct {
	client VrfClient
	sdkresolvers.BaseNameResolver
}

func VrfVrfsResolver(name string, client VrfClient, opts ...sdkresolvers.ResolveOption) sdkresolvers.Resolver {
	return &vrfVrfsResolver{
		client:           client,
		BaseNameResolver: sdkresolvers.NewBaseNameResolver(name, "VrfVrfs", opts...),
	}
}

func (r *vrfVrfsResolver) Run(ctx context.Context) error {
	resp := r.client.VrfsIterator(ctx, &baremetal.ListVrfsRequest{
		CloudId:  r.CloudID(),
		Filter:   sdkresolvers.CreateResolverFilter("name", r.Name),
		PageSize: sdkresolvers.DefaultResolverPageSize,
	})
	return r.FindName(resp.TakeAll())
}

type vrfVrfOperationsResolver struct {
	client VrfClient
	sdkresolvers.BaseNameResolver
}

func VrfVrfOperationsResolver(name string, client VrfClient, opts ...sdkresolvers.ResolveOption) sdkresolvers.Resolver {
	return &vrfVrfOperationsResolver{
		client:           client,
		BaseNameResolver: sdkresolvers.NewBaseNameResolver(name, "VrfVrfOperations", opts...),
	}
}

func (r *vrfVrfOperationsResolver) Run(ctx context.Context) error {
	resp := r.client.VrfOperationsIterator(ctx, &baremetal.ListVrfOperationsRequest{
		CloudId: r.CloudID(),

		PageSize: sdkresolvers.DefaultResolverPageSize,
	})
	return r.FindName(resp.TakeAll())
}
