// Code generated by sdkgen-v2. DO NOT EDIT.
package baremetalsdk

import (
	"context"

	baremetal "github.com/yandex-cloud/go-genproto/yandex/cloud/baremetal/v2"
	operation "github.com/yandex-cloud/go-genproto/yandex/cloud/operation"
	"github.com/yandex-cloud/go-sdk/v2/pkg/iterator"
	"google.golang.org/grpc"
)

type VrfClientIterator interface {
	VrfsIterator(context.Context, *baremetal.ListVrfsRequest, ...grpc.CallOption) *iterator.Iterator[*baremetal.ListVrfsRequest, *baremetal.Vrf]
	VrfOperationsIterator(context.Context, *baremetal.ListVrfOperationsRequest, ...grpc.CallOption) *iterator.Iterator[*baremetal.ListVrfOperationsRequest, *operation.Operation]
}

type vrfServiceListVrfsInternal struct {
	*baremetal.ListVrfsResponse
}

func (r vrfServiceListVrfsInternal) Items() []*baremetal.Vrf { return r.ListVrfsResponse.Vrfs }

func (c vrfClient) VrfsIterator(ctx context.Context, req *baremetal.ListVrfsRequest, opts ...grpc.CallOption) *iterator.Iterator[*baremetal.ListVrfsRequest, *baremetal.Vrf] {
	return iterator.NewIterator[*baremetal.ListVrfsRequest, *baremetal.Vrf](ctx, req,
		func(ctx context.Context, req *baremetal.ListVrfsRequest, opts ...grpc.CallOption) (iterator.PageResponse[*baremetal.Vrf], error) {
			resp, err := c.ListVrfs(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return vrfServiceListVrfsInternal{resp}, nil
		})
}

type vrfServiceListVrfOperationsInternal struct {
	*baremetal.ListVrfOperationsResponse
}

func (r vrfServiceListVrfOperationsInternal) Items() []*operation.Operation {
	return r.ListVrfOperationsResponse.Operations
}

func (c vrfClient) VrfOperationsIterator(ctx context.Context, req *baremetal.ListVrfOperationsRequest, opts ...grpc.CallOption) *iterator.Iterator[*baremetal.ListVrfOperationsRequest, *operation.Operation] {
	return iterator.NewIterator[*baremetal.ListVrfOperationsRequest, *operation.Operation](ctx, req,
		func(ctx context.Context, req *baremetal.ListVrfOperationsRequest, opts ...grpc.CallOption) (iterator.PageResponse[*operation.Operation], error) {
			resp, err := c.ListVrfOperations(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return vrfServiceListVrfOperationsInternal{resp}, nil
		})
}
