// Code generated by sdkgen-v2. DO NOT EDIT.
package baremetalsdk

import (
	"context"

	baremetal "github.com/yandex-cloud/go-genproto/yandex/cloud/baremetal/v2"
	"github.com/yandex-cloud/go-sdk/v2/pkg/transport"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// ZoneClient provides methods for managing Zone resources of Yandex.Cloud Baremetal.
type ZoneClient interface {
	ZoneClientIterator
	GetZone(context.Context, *baremetal.GetZoneRequest, ...grpc.CallOption) (*baremetal.Zone, error)
	ListZones(context.Context, *baremetal.ListZonesRequest, ...grpc.CallOption) (*baremetal.ListZonesResponse, error)
}

var _ ZoneClient = zoneClient{}

type zoneClient struct {
	connector transport.Connector
}

// NewZoneClient returns ZoneClient implementation.
func NewZoneClient(connector transport.Connector) ZoneClient {
	return zoneClient{connector}
}

// GetZone is an operation of Yandex.Cloud Baremetal Zone service.
func (c zoneClient) GetZone(ctx context.Context, in *baremetal.GetZoneRequest, opts ...grpc.CallOption) (*baremetal.Zone, error) {
	connection, err := c.connector.GetConnection(ctx, ZoneGetZone, opts...)
	if err != nil {
		return nil, err
	}
	return baremetal.NewZoneServiceClient(connection).GetZone(ctx, in, opts...)
}

// ListZones is an operation of Yandex.Cloud Baremetal Zone service.
func (c zoneClient) ListZones(ctx context.Context, in *baremetal.ListZonesRequest, opts ...grpc.CallOption) (*baremetal.ListZonesResponse, error) {
	connection, err := c.connector.GetConnection(ctx, ZoneListZones, opts...)
	if err != nil {
		return nil, err
	}
	return baremetal.NewZoneServiceClient(connection).ListZones(ctx, in, opts...)
}

var (
	ZoneGetZone   = protoreflect.FullName("yandex.cloud.baremetal.v2.ZoneService.GetZone")
	ZoneListZones = protoreflect.FullName("yandex.cloud.baremetal.v2.ZoneService.ListZones")
)
