// Code generated by sdkgen-v2. DO NOT EDIT.
package foundationmodelssdk

import (
	"context"

	text_generation "github.com/yandex-cloud/go-genproto/yandex/cloud/ai/foundation_models/v1/text_generation"
	operation "github.com/yandex-cloud/go-genproto/yandex/cloud/operation"
	sdkop "github.com/yandex-cloud/go-sdk/v2/pkg/operation"
	"github.com/yandex-cloud/go-sdk/v2/pkg/transport"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// TextGenerationBatchClient provides methods for managing TextGenerationBatch resources of Yandex.Cloud FoundationModels.
type TextGenerationBatchClient interface {
	Completion(context.Context, *text_generation.BatchCompletionRequest, ...grpc.CallOption) (*TextGenerationBatchCompletionOperation, error)
}

var _ TextGenerationBatchClient = textGenerationBatchClient{}

type textGenerationBatchClient struct {
	connector transport.Connector
}

// NewTextGenerationBatchClient returns TextGenerationBatchClient implementation.
func NewTextGenerationBatchClient(connector transport.Connector) TextGenerationBatchClient {
	return textGenerationBatchClient{connector}
}

// TextGenerationBatchCompletionOperation is used to monitor the state of Completion operations.
type TextGenerationBatchCompletionOperation struct {
	sdkop.Operation
}

// Metadata retrieves the operation metadata.
func (o *TextGenerationBatchCompletionOperation) Metadata() *text_generation.BatchCompletionMetadata {
	return o.Operation.Metadata().(*text_generation.BatchCompletionMetadata)
}

// Response retrieves the operation response.
func (o *TextGenerationBatchCompletionOperation) Response() *text_generation.BatchCompletionResponse {
	return o.Operation.Response().(*text_generation.BatchCompletionResponse)
}

// Wait polls the operation until it's done.
func (o *TextGenerationBatchCompletionOperation) Wait(ctx context.Context, opts ...grpc.CallOption) (*text_generation.BatchCompletionResponse, error) {
	abstract, err := o.Operation.Wait(ctx, opts...)
	response, _ := abstract.(*text_generation.BatchCompletionResponse)
	return response, err
}

// WaitInterval polls the operation until it's done with custom interval.
func (o *TextGenerationBatchCompletionOperation) WaitInterval(ctx context.Context, pollInterval sdkop.PollIntervalFunc, opts ...grpc.CallOption) (*text_generation.BatchCompletionResponse, error) {
	abstract, err := o.Operation.WaitInterval(ctx, pollInterval, opts...)
	response, _ := abstract.(*text_generation.BatchCompletionResponse)
	return response, err
}

// Completion is an operation of Yandex.Cloud FoundationModels TextGenerationBatch service.
// It returns an object which should be used to monitor the operation state.
func (c textGenerationBatchClient) Completion(ctx context.Context, in *text_generation.BatchCompletionRequest, opts ...grpc.CallOption) (*TextGenerationBatchCompletionOperation, error) {
	connection, err := c.connector.GetConnection(ctx, TextGenerationBatchCompletion, opts...)
	if err != nil {
		return nil, err
	}
	pb, err := text_generation.NewTextGenerationBatchServiceClient(connection).Completion(ctx, in, opts...)
	if err != nil {
		return nil, err
	}
	op, err := sdkop.NewOperation(pb, &sdkop.Concretization{
		Poll:         c.pollOperation,
		MetadataType: (*text_generation.BatchCompletionMetadata)(nil),
		ResponseType: (*text_generation.BatchCompletionResponse)(nil),
	})
	if err != nil {
		return nil, err
	}
	return &TextGenerationBatchCompletionOperation{*op}, nil
}

// pollOperation returns the current state of the polled operation.
func (c textGenerationBatchClient) pollOperation(ctx context.Context, operationId string, opts ...grpc.CallOption) (sdkop.YCOperation, error) {
	connection, err := c.connector.GetConnection(ctx, TextGenerationBatchOperationPoller, opts...)
	if err != nil {
		return nil, err
	}
	return operation.NewOperationServiceClient(connection).Get(ctx, &operation.GetOperationRequest{OperationId: operationId}, opts...)
}

var (
	TextGenerationBatchCompletion      = protoreflect.FullName("yandex.cloud.ai.foundation_models.v1.TextGenerationBatchService.Completion")
	TextGenerationBatchOperationPoller = protoreflect.FullName("yandex.cloud.operation.OperationService.Get")
)
