// Code generated by sdkgen-v2. DO NOT EDIT.
package foundationmodelssdk

import (
	"context"

	text_generation "github.com/yandex-cloud/go-genproto/yandex/cloud/ai/foundation_models/v1/text_generation"
	"github.com/yandex-cloud/go-sdk/v2/pkg/transport"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// TextGenerationClient provides methods for managing TextGeneration resources of Yandex.Cloud FoundationModels.
type TextGenerationClient interface {
	TextGenerationClientIterator
	Completion(context.Context, *text_generation.CompletionRequest, ...grpc.CallOption) (text_generation.TextGenerationService_CompletionClient, error)
}

var _ TextGenerationClient = textGenerationClient{}

type textGenerationClient struct {
	connector transport.Connector
}

// NewTextGenerationClient returns TextGenerationClient implementation.
func NewTextGenerationClient(connector transport.Connector) TextGenerationClient {
	return textGenerationClient{connector}
}

// Completion is an operation of Yandex.Cloud FoundationModels TextGeneration service.
func (c textGenerationClient) Completion(ctx context.Context, in *text_generation.CompletionRequest, opts ...grpc.CallOption) (text_generation.TextGenerationService_CompletionClient, error) {
	connection, err := c.connector.GetConnection(ctx, TextGenerationCompletion, opts...)
	if err != nil {
		return nil, err
	}
	return text_generation.NewTextGenerationServiceClient(connection).Completion(ctx, in, opts...)
}

var (
	TextGenerationCompletion = protoreflect.FullName("yandex.cloud.ai.foundation_models.v1.TextGenerationService.Completion")
)
