// Code generated by sdkgen-v2. DO NOT EDIT.
package foundationmodelssdk

import (
	"context"

	text_generation "github.com/yandex-cloud/go-genproto/yandex/cloud/ai/foundation_models/v1/text_generation"
	operation "github.com/yandex-cloud/go-genproto/yandex/cloud/operation"
	sdkop "github.com/yandex-cloud/go-sdk/v2/pkg/operation"
	"github.com/yandex-cloud/go-sdk/v2/pkg/transport"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// TextGenerationAsyncClient provides methods for managing TextGenerationAsync resources of Yandex.Cloud FoundationModels.
type TextGenerationAsyncClient interface {
	Completion(context.Context, *text_generation.CompletionRequest, ...grpc.CallOption) (*TextGenerationAsyncCompletionOperation, error)
}

var _ TextGenerationAsyncClient = textGenerationAsyncClient{}

type textGenerationAsyncClient struct {
	connector transport.Connector
}

// NewTextGenerationAsyncClient returns TextGenerationAsyncClient implementation.
func NewTextGenerationAsyncClient(connector transport.Connector) TextGenerationAsyncClient {
	return textGenerationAsyncClient{connector}
}

// TextGenerationAsyncCompletionOperation is used to monitor the state of Completion operations.
type TextGenerationAsyncCompletionOperation struct {
	sdkop.Operation
}

// Response retrieves the operation response.
func (o *TextGenerationAsyncCompletionOperation) Response() *text_generation.CompletionResponse {
	return o.Operation.Response().(*text_generation.CompletionResponse)
}

// Wait polls the operation until it's done.
func (o *TextGenerationAsyncCompletionOperation) Wait(ctx context.Context, opts ...grpc.CallOption) (*text_generation.CompletionResponse, error) {
	abstract, err := o.Operation.Wait(ctx, opts...)
	response, _ := abstract.(*text_generation.CompletionResponse)
	return response, err
}

// WaitInterval polls the operation until it's done with custom interval.
func (o *TextGenerationAsyncCompletionOperation) WaitInterval(ctx context.Context, pollInterval sdkop.PollIntervalFunc, opts ...grpc.CallOption) (*text_generation.CompletionResponse, error) {
	abstract, err := o.Operation.WaitInterval(ctx, pollInterval, opts...)
	response, _ := abstract.(*text_generation.CompletionResponse)
	return response, err
}

// Completion is an operation of Yandex.Cloud FoundationModels TextGenerationAsync service.
// It returns an object which should be used to monitor the operation state.
func (c textGenerationAsyncClient) Completion(ctx context.Context, in *text_generation.CompletionRequest, opts ...grpc.CallOption) (*TextGenerationAsyncCompletionOperation, error) {
	connection, err := c.connector.GetConnection(ctx, TextGenerationAsyncCompletion, opts...)
	if err != nil {
		return nil, err
	}
	pb, err := text_generation.NewTextGenerationAsyncServiceClient(connection).Completion(ctx, in, opts...)
	if err != nil {
		return nil, err
	}
	op, err := sdkop.NewOperation(pb, &sdkop.Concretization{
		Poll:         c.pollOperation,
		MetadataType: nil,
		ResponseType: (*text_generation.CompletionResponse)(nil),
	})
	if err != nil {
		return nil, err
	}
	return &TextGenerationAsyncCompletionOperation{*op}, nil
}

// pollOperation returns the current state of the polled operation.
func (c textGenerationAsyncClient) pollOperation(ctx context.Context, operationId string, opts ...grpc.CallOption) (sdkop.YCOperation, error) {
	connection, err := c.connector.GetConnection(ctx, TextGenerationAsyncOperationPoller, opts...)
	if err != nil {
		return nil, err
	}
	return operation.NewOperationServiceClient(connection).Get(ctx, &operation.GetOperationRequest{OperationId: operationId}, opts...)
}

var (
	TextGenerationAsyncCompletion      = protoreflect.FullName("yandex.cloud.ai.foundation_models.v1.TextGenerationAsyncService.Completion")
	TextGenerationAsyncOperationPoller = protoreflect.FullName("yandex.cloud.operation.OperationService.Get")
)
