// Code generated by sdkgen-v2. DO NOT EDIT.
package foundationmodelssdk

import (
	"context"

	text_generation "github.com/yandex-cloud/go-genproto/yandex/cloud/ai/foundation_models/v1/text_generation"
	"github.com/yandex-cloud/go-sdk/v2/pkg/transport"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// TokenizerClient provides methods for managing Tokenizer resources of Yandex.Cloud FoundationModels.
type TokenizerClient interface {
	Tokenize(context.Context, *text_generation.TokenizeRequest, ...grpc.CallOption) (*text_generation.TokenizeResponse, error)
	TokenizeCompletion(context.Context, *text_generation.CompletionRequest, ...grpc.CallOption) (*text_generation.TokenizeResponse, error)
}

var _ TokenizerClient = tokenizerClient{}

type tokenizerClient struct {
	connector transport.Connector
}

// NewTokenizerClient returns TokenizerClient implementation.
func NewTokenizerClient(connector transport.Connector) TokenizerClient {
	return tokenizerClient{connector}
}

// Tokenize is an operation of Yandex.Cloud FoundationModels Tokenizer service.
func (c tokenizerClient) Tokenize(ctx context.Context, in *text_generation.TokenizeRequest, opts ...grpc.CallOption) (*text_generation.TokenizeResponse, error) {
	connection, err := c.connector.GetConnection(ctx, TokenizerTokenize, opts...)
	if err != nil {
		return nil, err
	}
	return text_generation.NewTokenizerServiceClient(connection).Tokenize(ctx, in, opts...)
}

// TokenizeCompletion is an operation of Yandex.Cloud FoundationModels Tokenizer service.
func (c tokenizerClient) TokenizeCompletion(ctx context.Context, in *text_generation.CompletionRequest, opts ...grpc.CallOption) (*text_generation.TokenizeResponse, error) {
	connection, err := c.connector.GetConnection(ctx, TokenizerTokenizeCompletion, opts...)
	if err != nil {
		return nil, err
	}
	return text_generation.NewTokenizerServiceClient(connection).TokenizeCompletion(ctx, in, opts...)
}

var (
	TokenizerTokenize           = protoreflect.FullName("yandex.cloud.ai.foundation_models.v1.TokenizerService.Tokenize")
	TokenizerTokenizeCompletion = protoreflect.FullName("yandex.cloud.ai.foundation_models.v1.TokenizerService.TokenizeCompletion")
)
