// Code generated by sdkgen-v2. DO NOT EDIT.
package apisdk

import (
	"context"

	api "github.com/yandex-cloud/go-genproto/yandex/cloud/loadtesting/api/v1"
	config "github.com/yandex-cloud/go-genproto/yandex/cloud/loadtesting/api/v1/config"
	"github.com/yandex-cloud/go-sdk/v2/pkg/iterator"
	"google.golang.org/grpc"
)

type ConfigClientIterator interface {
	Iterator(context.Context, *api.ListConfigsRequest, ...grpc.CallOption) *iterator.Iterator[*api.ListConfigsRequest, *config.Config]
}

type configServiceListInternal struct {
	*api.ListConfigsResponse
}

func (r configServiceListInternal) Items() []*config.Config { return r.ListConfigsResponse.Configs }

func (c configClient) Iterator(ctx context.Context, req *api.ListConfigsRequest, opts ...grpc.CallOption) *iterator.Iterator[*api.ListConfigsRequest, *config.Config] {
	return iterator.NewIterator[*api.ListConfigsRequest, *config.Config](ctx, req,
		func(ctx context.Context, req *api.ListConfigsRequest, opts ...grpc.CallOption) (iterator.PageResponse[*config.Config], error) {
			resp, err := c.List(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return configServiceListInternal{resp}, nil
		})
}
