// Code generated by sdkgen-v2. DO NOT EDIT.
package apisdk

import (
	"context"

	api "github.com/yandex-cloud/go-genproto/yandex/cloud/loadtesting/api/v1"
	"github.com/yandex-cloud/go-sdk/v2/pkg/sdkresolvers"
)

type testResolver struct {
	client TestClient
	sdkresolvers.BaseNameResolver
}

func TestResolver(name string, client TestClient, opts ...sdkresolvers.ResolveOption) sdkresolvers.Resolver {
	return &testResolver{
		client:           client,
		BaseNameResolver: sdkresolvers.NewBaseNameResolver(name, "Test", opts...),
	}
}

func (r *testResolver) Run(ctx context.Context) error {
	err := r.EnsureFolderID()
	if err != nil {
		return err
	}

	resp := r.client.Iterator(ctx, &api.ListTestsRequest{
		FolderId: r.FolderID(),
		Filter:   sdkresolvers.CreateResolverFilter("name", r.Name),
		PageSize: sdkresolvers.DefaultResolverPageSize,
	})
	return r.FindName(resp.TakeAll())
}
