// Code generated by sdkgen-v2. DO NOT EDIT.
package cicsdk

import (
	"context"

	cic "github.com/yandex-cloud/go-genproto/yandex/cloud/cic/v1"
	"github.com/yandex-cloud/go-sdk/v2/pkg/iterator"
	"google.golang.org/grpc"
)

type PointOfPresenceClientIterator interface {
	Iterator(context.Context, *cic.ListPointOfPresencesRequest, ...grpc.CallOption) *iterator.Iterator[*cic.ListPointOfPresencesRequest, *cic.PointOfPresence]
}

type pointOfPresenceServiceListInternal struct {
	*cic.ListPointOfPresencesResponse
}

func (r pointOfPresenceServiceListInternal) Items() []*cic.PointOfPresence {
	return r.ListPointOfPresencesResponse.PointOfPresences
}

func (c pointOfPresenceClient) Iterator(ctx context.Context, req *cic.ListPointOfPresencesRequest, opts ...grpc.CallOption) *iterator.Iterator[*cic.ListPointOfPresencesRequest, *cic.PointOfPresence] {
	return iterator.NewIterator[*cic.ListPointOfPresencesRequest, *cic.PointOfPresence](ctx, req,
		func(ctx context.Context, req *cic.ListPointOfPresencesRequest, opts ...grpc.CallOption) (iterator.PageResponse[*cic.PointOfPresence], error) {
			resp, err := c.List(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return pointOfPresenceServiceListInternal{resp}, nil
		})
}
