// Code generated by sdkgen-v2. DO NOT EDIT.
package cicsdk

import (
	"context"

	cic "github.com/yandex-cloud/go-genproto/yandex/cloud/cic/v1"
	operation "github.com/yandex-cloud/go-genproto/yandex/cloud/operation"
	"github.com/yandex-cloud/go-sdk/v2/pkg/iterator"
	"google.golang.org/grpc"
)

type PublicConnectionClientIterator interface {
	Iterator(context.Context, *cic.ListPublicConnectionsRequest, ...grpc.CallOption) *iterator.Iterator[*cic.ListPublicConnectionsRequest, *cic.PublicConnection]
	OperationsIterator(context.Context, *cic.ListPublicConnectionOperationsRequest, ...grpc.CallOption) *iterator.Iterator[*cic.ListPublicConnectionOperationsRequest, *operation.Operation]
}

type publicConnectionServiceListInternal struct {
	*cic.ListPublicConnectionsResponse
}

func (r publicConnectionServiceListInternal) Items() []*cic.PublicConnection {
	return r.ListPublicConnectionsResponse.PublicConnections
}

func (c publicConnectionClient) Iterator(ctx context.Context, req *cic.ListPublicConnectionsRequest, opts ...grpc.CallOption) *iterator.Iterator[*cic.ListPublicConnectionsRequest, *cic.PublicConnection] {
	return iterator.NewIterator[*cic.ListPublicConnectionsRequest, *cic.PublicConnection](ctx, req,
		func(ctx context.Context, req *cic.ListPublicConnectionsRequest, opts ...grpc.CallOption) (iterator.PageResponse[*cic.PublicConnection], error) {
			resp, err := c.List(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return publicConnectionServiceListInternal{resp}, nil
		})
}

type publicConnectionServiceListOperationsInternal struct {
	*cic.ListPublicConnectionOperationsResponse
}

func (r publicConnectionServiceListOperationsInternal) Items() []*operation.Operation {
	return r.ListPublicConnectionOperationsResponse.Operations
}

func (c publicConnectionClient) OperationsIterator(ctx context.Context, req *cic.ListPublicConnectionOperationsRequest, opts ...grpc.CallOption) *iterator.Iterator[*cic.ListPublicConnectionOperationsRequest, *operation.Operation] {
	return iterator.NewIterator[*cic.ListPublicConnectionOperationsRequest, *operation.Operation](ctx, req,
		func(ctx context.Context, req *cic.ListPublicConnectionOperationsRequest, opts ...grpc.CallOption) (iterator.PageResponse[*operation.Operation], error) {
			resp, err := c.ListOperations(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return publicConnectionServiceListOperationsInternal{resp}, nil
		})
}
