// Code generated by sdkgen-v2. DO NOT EDIT.
package cicsdk

import (
	"context"

	cic "github.com/yandex-cloud/go-genproto/yandex/cloud/cic/v1"
	"github.com/yandex-cloud/go-sdk/v2/pkg/sdkresolvers"
)

type publicConnectionResolver struct {
	client PublicConnectionClient
	sdkresolvers.BaseNameResolver
}

func PublicConnectionResolver(name string, client PublicConnectionClient, opts ...sdkresolvers.ResolveOption) sdkresolvers.Resolver {
	return &publicConnectionResolver{
		client:           client,
		BaseNameResolver: sdkresolvers.NewBaseNameResolver(name, "PublicConnection", opts...),
	}
}

func (r *publicConnectionResolver) Run(ctx context.Context) error {
	err := r.EnsureFolderID()
	if err != nil {
		return err
	}

	resp := r.client.Iterator(ctx, &cic.ListPublicConnectionsRequest{
		FolderId: r.FolderID(),
		Filter:   sdkresolvers.CreateResolverFilter("name", r.Name),
		PageSize: sdkresolvers.DefaultResolverPageSize,
	})
	return r.FindName(resp.TakeAll())
}
