// Code generated by sdkgen-v2. DO NOT EDIT.
package cicsdk

import (
	"context"

	cic "github.com/yandex-cloud/go-genproto/yandex/cloud/cic/v1"
	"github.com/yandex-cloud/go-sdk/v2/pkg/sdkresolvers"
)

type trunkConnectionTicketResolver struct {
	client TrunkConnectionTicketClient
	sdkresolvers.BaseNameResolver
}

func TrunkConnectionTicketResolver(name string, client TrunkConnectionTicketClient, opts ...sdkresolvers.ResolveOption) sdkresolvers.Resolver {
	return &trunkConnectionTicketResolver{
		client:           client,
		BaseNameResolver: sdkresolvers.NewBaseNameResolver(name, "TrunkConnectionTicket", opts...),
	}
}

func (r *trunkConnectionTicketResolver) Run(ctx context.Context) error {
	resp := r.client.Iterator(ctx, &cic.ListTrunkConnectionTicketsRequest{
		FolderId: r.FolderID(),
		Filter:   sdkresolvers.CreateResolverFilter("name", r.Name),
		PageSize: sdkresolvers.DefaultResolverPageSize,
	})
	return r.FindName(resp.TakeAll())
}
