// Code generated by sdkgen-v2. DO NOT EDIT.
package cicsdk

import (
	"context"

	cic "github.com/yandex-cloud/go-genproto/yandex/cloud/cic/v1"
	"github.com/yandex-cloud/go-sdk/v2/pkg/iterator"
	"google.golang.org/grpc"
)

type TrunkConnectionTicketClientIterator interface {
	Iterator(context.Context, *cic.ListTrunkConnectionTicketsRequest, ...grpc.CallOption) *iterator.Iterator[*cic.ListTrunkConnectionTicketsRequest, *cic.TrunkConnectionTicket]
}

type trunkConnectionTicketServiceListInternal struct {
	*cic.ListTrunkConnectionTicketsResponse
}

func (r trunkConnectionTicketServiceListInternal) Items() []*cic.TrunkConnectionTicket {
	return r.ListTrunkConnectionTicketsResponse.TrunkConnectionTickets
}

func (c trunkConnectionTicketClient) Iterator(ctx context.Context, req *cic.ListTrunkConnectionTicketsRequest, opts ...grpc.CallOption) *iterator.Iterator[*cic.ListTrunkConnectionTicketsRequest, *cic.TrunkConnectionTicket] {
	return iterator.NewIterator[*cic.ListTrunkConnectionTicketsRequest, *cic.TrunkConnectionTicket](ctx, req,
		func(ctx context.Context, req *cic.ListTrunkConnectionTicketsRequest, opts ...grpc.CallOption) (iterator.PageResponse[*cic.TrunkConnectionTicket], error) {
			resp, err := c.List(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return trunkConnectionTicketServiceListInternal{resp}, nil
		})
}
