// Code generated by sdkgen-v2. DO NOT EDIT.
package cicsdk

import (
	"context"

	cic "github.com/yandex-cloud/go-genproto/yandex/cloud/cic/v1"
	operation "github.com/yandex-cloud/go-genproto/yandex/cloud/operation"
	"github.com/yandex-cloud/go-sdk/v2/pkg/iterator"
	"google.golang.org/grpc"
)

type TrunkConnectionClientIterator interface {
	Iterator(context.Context, *cic.ListTrunkConnectionsRequest, ...grpc.CallOption) *iterator.Iterator[*cic.ListTrunkConnectionsRequest, *cic.TrunkConnection]
	OperationsIterator(context.Context, *cic.ListTrunkConnectionOperationsRequest, ...grpc.CallOption) *iterator.Iterator[*cic.ListTrunkConnectionOperationsRequest, *operation.Operation]
}

type trunkConnectionServiceListInternal struct {
	*cic.ListTrunkConnectionsResponse
}

func (r trunkConnectionServiceListInternal) Items() []*cic.TrunkConnection {
	return r.ListTrunkConnectionsResponse.TrunkConnections
}

func (c trunkConnectionClient) Iterator(ctx context.Context, req *cic.ListTrunkConnectionsRequest, opts ...grpc.CallOption) *iterator.Iterator[*cic.ListTrunkConnectionsRequest, *cic.TrunkConnection] {
	return iterator.NewIterator[*cic.ListTrunkConnectionsRequest, *cic.TrunkConnection](ctx, req,
		func(ctx context.Context, req *cic.ListTrunkConnectionsRequest, opts ...grpc.CallOption) (iterator.PageResponse[*cic.TrunkConnection], error) {
			resp, err := c.List(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return trunkConnectionServiceListInternal{resp}, nil
		})
}

type trunkConnectionServiceListOperationsInternal struct {
	*cic.ListTrunkConnectionOperationsResponse
}

func (r trunkConnectionServiceListOperationsInternal) Items() []*operation.Operation {
	return r.ListTrunkConnectionOperationsResponse.Operations
}

func (c trunkConnectionClient) OperationsIterator(ctx context.Context, req *cic.ListTrunkConnectionOperationsRequest, opts ...grpc.CallOption) *iterator.Iterator[*cic.ListTrunkConnectionOperationsRequest, *operation.Operation] {
	return iterator.NewIterator[*cic.ListTrunkConnectionOperationsRequest, *operation.Operation](ctx, req,
		func(ctx context.Context, req *cic.ListTrunkConnectionOperationsRequest, opts ...grpc.CallOption) (iterator.PageResponse[*operation.Operation], error) {
			resp, err := c.ListOperations(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return trunkConnectionServiceListOperationsInternal{resp}, nil
		})
}
