// Code generated by sdkgen-v2. DO NOT EDIT.
package baremetalsdk

import (
	"context"

	baremetal "github.com/yandex-cloud/go-genproto/yandex/cloud/baremetal/v1alpha"
	"github.com/yandex-cloud/go-sdk/v2/pkg/iterator"
	"google.golang.org/grpc"
)

type ConfigurationClientIterator interface {
	Iterator(context.Context, *baremetal.ListConfigurationsRequest, ...grpc.CallOption) *iterator.Iterator[*baremetal.ListConfigurationsRequest, *baremetal.Configuration]
	ConfigurationNetworkInterfaceIterator(context.Context, *baremetal.ListConfigurationNetworkInterfaceRequest, ...grpc.CallOption) *iterator.Iterator[*baremetal.ListConfigurationNetworkInterfaceRequest, *baremetal.ConfigurationNetworkInterface]
}

type configurationServiceListInternal struct {
	*baremetal.ListConfigurationsResponse
}

func (r configurationServiceListInternal) Items() []*baremetal.Configuration {
	return r.ListConfigurationsResponse.Configurations
}

func (c configurationClient) Iterator(ctx context.Context, req *baremetal.ListConfigurationsRequest, opts ...grpc.CallOption) *iterator.Iterator[*baremetal.ListConfigurationsRequest, *baremetal.Configuration] {
	return iterator.NewIterator[*baremetal.ListConfigurationsRequest, *baremetal.Configuration](ctx, req,
		func(ctx context.Context, req *baremetal.ListConfigurationsRequest, opts ...grpc.CallOption) (iterator.PageResponse[*baremetal.Configuration], error) {
			resp, err := c.List(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return configurationServiceListInternal{resp}, nil
		})
}

type configurationServiceListConfigurationNetworkInterfaceInternal struct {
	*baremetal.ListConfigurationNetworkInterfaceResponse
}

func (r configurationServiceListConfigurationNetworkInterfaceInternal) Items() []*baremetal.ConfigurationNetworkInterface {
	return r.ListConfigurationNetworkInterfaceResponse.ConfigurationNetworkInterfaces
}

func (c configurationClient) ConfigurationNetworkInterfaceIterator(ctx context.Context, req *baremetal.ListConfigurationNetworkInterfaceRequest, opts ...grpc.CallOption) *iterator.Iterator[*baremetal.ListConfigurationNetworkInterfaceRequest, *baremetal.ConfigurationNetworkInterface] {
	return iterator.NewIterator[*baremetal.ListConfigurationNetworkInterfaceRequest, *baremetal.ConfigurationNetworkInterface](ctx, req,
		func(ctx context.Context, req *baremetal.ListConfigurationNetworkInterfaceRequest, opts ...grpc.CallOption) (iterator.PageResponse[*baremetal.ConfigurationNetworkInterface], error) {
			resp, err := c.ListConfigurationNetworkInterface(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return configurationServiceListConfigurationNetworkInterfaceInternal{resp}, nil
		})
}
