// Code generated by sdkgen-v2. DO NOT EDIT.
package baremetalsdk

import (
	"context"

	baremetal "github.com/yandex-cloud/go-genproto/yandex/cloud/baremetal/v1alpha"
	"github.com/yandex-cloud/go-sdk/v2/pkg/iterator"
	"google.golang.org/grpc"
)

type ConfigurationClientIterator interface {
	Iterator(context.Context, *baremetal.ListConfigurationsRequest, ...grpc.CallOption) *iterator.Iterator[*baremetal.ListConfigurationsRequest, *baremetal.Configuration]
}

type configurationServiceListInternal struct {
	*baremetal.ListConfigurationsResponse
}

func (r configurationServiceListInternal) Items() []*baremetal.Configuration {
	return r.ListConfigurationsResponse.Configurations
}

func (c configurationClient) Iterator(ctx context.Context, req *baremetal.ListConfigurationsRequest, opts ...grpc.CallOption) *iterator.Iterator[*baremetal.ListConfigurationsRequest, *baremetal.Configuration] {
	return iterator.NewIterator[*baremetal.ListConfigurationsRequest, *baremetal.Configuration](ctx, req,
		func(ctx context.Context, req *baremetal.ListConfigurationsRequest, opts ...grpc.CallOption) (iterator.PageResponse[*baremetal.Configuration], error) {
			resp, err := c.List(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return configurationServiceListInternal{resp}, nil
		})
}
