// Code generated by sdkgen-v2. DO NOT EDIT.
package baremetalsdk

import (
	"context"

	baremetal "github.com/yandex-cloud/go-genproto/yandex/cloud/baremetal/v1alpha"
	"github.com/yandex-cloud/go-sdk/v2/pkg/iterator"
	"google.golang.org/grpc"
)

type PrivateCloudConnectionClientIterator interface {
	Iterator(context.Context, *baremetal.ListPrivateCloudConnectionRequest, ...grpc.CallOption) *iterator.Iterator[*baremetal.ListPrivateCloudConnectionRequest, *baremetal.PrivateCloudConnection]
}

type privateCloudConnectionServiceListInternal struct {
	*baremetal.ListPrivateCloudConnectionResponse
}

func (r privateCloudConnectionServiceListInternal) Items() []*baremetal.PrivateCloudConnection {
	return r.ListPrivateCloudConnectionResponse.PrivateCloudConnections
}

func (c privateCloudConnectionClient) Iterator(ctx context.Context, req *baremetal.ListPrivateCloudConnectionRequest, opts ...grpc.CallOption) *iterator.Iterator[*baremetal.ListPrivateCloudConnectionRequest, *baremetal.PrivateCloudConnection] {
	return iterator.NewIterator[*baremetal.ListPrivateCloudConnectionRequest, *baremetal.PrivateCloudConnection](ctx, req,
		func(ctx context.Context, req *baremetal.ListPrivateCloudConnectionRequest, opts ...grpc.CallOption) (iterator.PageResponse[*baremetal.PrivateCloudConnection], error) {
			resp, err := c.List(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return privateCloudConnectionServiceListInternal{resp}, nil
		})
}
