// Code generated by sdkgen-v2. DO NOT EDIT.
package baremetalsdk

import (
	"context"

	baremetal "github.com/yandex-cloud/go-genproto/yandex/cloud/baremetal/v1alpha"
	operation "github.com/yandex-cloud/go-genproto/yandex/cloud/operation"
	"github.com/yandex-cloud/go-sdk/v2/pkg/iterator"
	"google.golang.org/grpc"
)

type PublicPrefixPoolClientIterator interface {
	Iterator(context.Context, *baremetal.ListPublicPrefixPoolRequest, ...grpc.CallOption) *iterator.Iterator[*baremetal.ListPublicPrefixPoolRequest, *baremetal.PublicPrefixPool]
	OperationsIterator(context.Context, *baremetal.ListPublicPrefixPoolOperationsRequest, ...grpc.CallOption) *iterator.Iterator[*baremetal.ListPublicPrefixPoolOperationsRequest, *operation.Operation]
}

type publicPrefixPoolServiceListInternal struct {
	*baremetal.ListPublicPrefixPoolResponse
}

func (r publicPrefixPoolServiceListInternal) Items() []*baremetal.PublicPrefixPool {
	return r.ListPublicPrefixPoolResponse.PublicPrefixPools
}

func (c publicPrefixPoolClient) Iterator(ctx context.Context, req *baremetal.ListPublicPrefixPoolRequest, opts ...grpc.CallOption) *iterator.Iterator[*baremetal.ListPublicPrefixPoolRequest, *baremetal.PublicPrefixPool] {
	return iterator.NewIterator[*baremetal.ListPublicPrefixPoolRequest, *baremetal.PublicPrefixPool](ctx, req,
		func(ctx context.Context, req *baremetal.ListPublicPrefixPoolRequest, opts ...grpc.CallOption) (iterator.PageResponse[*baremetal.PublicPrefixPool], error) {
			resp, err := c.List(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return publicPrefixPoolServiceListInternal{resp}, nil
		})
}

type publicPrefixPoolServiceListOperationsInternal struct {
	*baremetal.ListPublicPrefixPoolOperationsResponse
}

func (r publicPrefixPoolServiceListOperationsInternal) Items() []*operation.Operation {
	return r.ListPublicPrefixPoolOperationsResponse.Operations
}

func (c publicPrefixPoolClient) OperationsIterator(ctx context.Context, req *baremetal.ListPublicPrefixPoolOperationsRequest, opts ...grpc.CallOption) *iterator.Iterator[*baremetal.ListPublicPrefixPoolOperationsRequest, *operation.Operation] {
	return iterator.NewIterator[*baremetal.ListPublicPrefixPoolOperationsRequest, *operation.Operation](ctx, req,
		func(ctx context.Context, req *baremetal.ListPublicPrefixPoolOperationsRequest, opts ...grpc.CallOption) (iterator.PageResponse[*operation.Operation], error) {
			resp, err := c.ListOperations(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return publicPrefixPoolServiceListOperationsInternal{resp}, nil
		})
}
