// Code generated by sdkgen-v2. DO NOT EDIT.
package baremetalsdk

import (
	"context"

	baremetal "github.com/yandex-cloud/go-genproto/yandex/cloud/baremetal/v1alpha"
	"github.com/yandex-cloud/go-sdk/v2/pkg/sdkresolvers"
)

type standardImageResolver struct {
	client StandardImageClient
	sdkresolvers.BaseNameResolver
}

func StandardImageResolver(name string, client StandardImageClient, opts ...sdkresolvers.ResolveOption) sdkresolvers.Resolver {
	return &standardImageResolver{
		client:           client,
		BaseNameResolver: sdkresolvers.NewBaseNameResolver(name, "StandardImage", opts...),
	}
}

func (r *standardImageResolver) Run(ctx context.Context) error {
	err := r.EnsureFolderID()
	if err != nil {
		return err
	}

	resp := r.client.Iterator(ctx, &baremetal.ListStandardImagesRequest{
		FolderId: r.FolderID(),
		Filter:   sdkresolvers.CreateResolverFilter("name", r.Name),
		PageSize: sdkresolvers.DefaultResolverPageSize,
	})
	return r.FindName(resp.TakeAll())
}
