// Code generated by sdkgen-v2. DO NOT EDIT.
package baremetalsdk

import (
	"context"

	baremetal "github.com/yandex-cloud/go-genproto/yandex/cloud/baremetal/v1alpha"
	"github.com/yandex-cloud/go-sdk/v2/pkg/transport"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// StorageClient provides methods for managing Storage resources of Yandex.Cloud Baremetal.
type StorageClient interface {
	StorageClientIterator
	GetDefault(context.Context, *baremetal.GetDefaultStorageRequest, ...grpc.CallOption) (*baremetal.DefaultStorage, error)
	BatchGetDefault(context.Context, *baremetal.BatchGetDefaultStoragesRequest, ...grpc.CallOption) (*baremetal.BatchGetDefaultStoragesResponse, error)
}

var _ StorageClient = storageClient{}

type storageClient struct {
	connector transport.Connector
}

// NewStorageClient returns StorageClient implementation.
func NewStorageClient(connector transport.Connector) StorageClient {
	return storageClient{connector}
}

// GetDefault is an operation of Yandex.Cloud Baremetal Storage service.
func (c storageClient) GetDefault(ctx context.Context, in *baremetal.GetDefaultStorageRequest, opts ...grpc.CallOption) (*baremetal.DefaultStorage, error) {
	connection, err := c.connector.GetConnection(ctx, StorageGetDefault, opts...)
	if err != nil {
		return nil, err
	}
	return baremetal.NewStorageServiceClient(connection).GetDefault(ctx, in, opts...)
}

// BatchGetDefault is an operation of Yandex.Cloud Baremetal Storage service.
func (c storageClient) BatchGetDefault(ctx context.Context, in *baremetal.BatchGetDefaultStoragesRequest, opts ...grpc.CallOption) (*baremetal.BatchGetDefaultStoragesResponse, error) {
	connection, err := c.connector.GetConnection(ctx, StorageBatchGetDefault, opts...)
	if err != nil {
		return nil, err
	}
	return baremetal.NewStorageServiceClient(connection).BatchGetDefault(ctx, in, opts...)
}

var (
	StorageGetDefault      = protoreflect.FullName("yandex.cloud.baremetal.v1alpha.StorageService.GetDefault")
	StorageBatchGetDefault = protoreflect.FullName("yandex.cloud.baremetal.v1alpha.StorageService.BatchGetDefault")
)
