// Code generated by sdkgen-v2. DO NOT EDIT.
package baremetalsdk

import (
	"context"

	baremetal "github.com/yandex-cloud/go-genproto/yandex/cloud/baremetal/v1alpha"
	"github.com/yandex-cloud/go-sdk/v2/pkg/iterator"
	"google.golang.org/grpc"
)

type ZoneClientIterator interface {
	Iterator(context.Context, *baremetal.ListZonesRequest, ...grpc.CallOption) *iterator.Iterator[*baremetal.ListZonesRequest, *baremetal.Zone]
}

type zoneServiceListInternal struct {
	*baremetal.ListZonesResponse
}

func (r zoneServiceListInternal) Items() []*baremetal.Zone { return r.ListZonesResponse.Zones }

func (c zoneClient) Iterator(ctx context.Context, req *baremetal.ListZonesRequest, opts ...grpc.CallOption) *iterator.Iterator[*baremetal.ListZonesRequest, *baremetal.Zone] {
	return iterator.NewIterator[*baremetal.ListZonesRequest, *baremetal.Zone](ctx, req,
		func(ctx context.Context, req *baremetal.ListZonesRequest, opts ...grpc.CallOption) (iterator.PageResponse[*baremetal.Zone], error) {
			resp, err := c.List(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return zoneServiceListInternal{resp}, nil
		})
}
