// Code generated by sdkgen-v2. DO NOT EDIT.
package elasticsearchsdk

import (
	"context"

	elasticsearch "github.com/yandex-cloud/go-genproto/yandex/cloud/mdb/elasticsearch/v1"
	"github.com/yandex-cloud/go-sdk/v2/pkg/iterator"
	"google.golang.org/grpc"
)

type AuthClientIterator interface {
	ProvidersIterator(context.Context, *elasticsearch.ListAuthProvidersRequest, ...grpc.CallOption) *iterator.SimpleIterator[*elasticsearch.ListAuthProvidersRequest, *elasticsearch.AuthProvider]
}

type authServiceListProvidersInternal struct {
	*elasticsearch.ListAuthProvidersResponse
}

func (r authServiceListProvidersInternal) Items() []*elasticsearch.AuthProvider {
	return r.ListAuthProvidersResponse.Providers
}

func (c authClient) ProvidersIterator(ctx context.Context, req *elasticsearch.ListAuthProvidersRequest, opts ...grpc.CallOption) *iterator.SimpleIterator[*elasticsearch.ListAuthProvidersRequest, *elasticsearch.AuthProvider] {
	return iterator.NewSimpleIterator[*elasticsearch.ListAuthProvidersRequest, *elasticsearch.AuthProvider](ctx, req,
		func(ctx context.Context, req *elasticsearch.ListAuthProvidersRequest, opts ...grpc.CallOption) (iterator.SimpleResponse[*elasticsearch.AuthProvider], error) {
			resp, err := c.ListProviders(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return authServiceListProvidersInternal{resp}, nil
		})
}
