// Code generated by sdkgen-v2. DO NOT EDIT.
package elasticsearchsdk

import (
	"context"

	elasticsearch "github.com/yandex-cloud/go-genproto/yandex/cloud/mdb/elasticsearch/v1"
	"github.com/yandex-cloud/go-sdk/v2/pkg/transport"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// BackupClient provides methods for managing Backup resources of Yandex.Cloud Elasticsearch.
type BackupClient interface {
	BackupClientIterator
	Get(context.Context, *elasticsearch.GetBackupRequest, ...grpc.CallOption) (*elasticsearch.Backup, error)
	List(context.Context, *elasticsearch.ListBackupsRequest, ...grpc.CallOption) (*elasticsearch.ListBackupsResponse, error)
}

var _ BackupClient = backupClient{}

type backupClient struct {
	connector transport.Connector
}

// NewBackupClient returns BackupClient implementation.
func NewBackupClient(connector transport.Connector) BackupClient {
	return backupClient{connector}
}

// Get is an operation of Yandex.Cloud Elasticsearch Backup service.
func (c backupClient) Get(ctx context.Context, in *elasticsearch.GetBackupRequest, opts ...grpc.CallOption) (*elasticsearch.Backup, error) {
	connection, err := c.connector.GetConnection(ctx, BackupGet, opts...)
	if err != nil {
		return nil, err
	}
	return elasticsearch.NewBackupServiceClient(connection).Get(ctx, in, opts...)
}

// List is an operation of Yandex.Cloud Elasticsearch Backup service.
func (c backupClient) List(ctx context.Context, in *elasticsearch.ListBackupsRequest, opts ...grpc.CallOption) (*elasticsearch.ListBackupsResponse, error) {
	connection, err := c.connector.GetConnection(ctx, BackupList, opts...)
	if err != nil {
		return nil, err
	}
	return elasticsearch.NewBackupServiceClient(connection).List(ctx, in, opts...)
}

var (
	BackupGet  = protoreflect.FullName("yandex.cloud.mdb.elasticsearch.v1.BackupService.Get")
	BackupList = protoreflect.FullName("yandex.cloud.mdb.elasticsearch.v1.BackupService.List")
)
