// Code generated by sdkgen-v2. DO NOT EDIT.
package elasticsearchsdk

import (
	"context"

	elasticsearch "github.com/yandex-cloud/go-genproto/yandex/cloud/mdb/elasticsearch/v1"
	"github.com/yandex-cloud/go-sdk/v2/pkg/iterator"
	"google.golang.org/grpc"
)

type ExtensionClientIterator interface {
	Iterator(context.Context, *elasticsearch.ListExtensionsRequest, ...grpc.CallOption) *iterator.Iterator[*elasticsearch.ListExtensionsRequest, *elasticsearch.Extension]
}

type extensionServiceListInternal struct {
	*elasticsearch.ListExtensionsResponse
}

func (r extensionServiceListInternal) Items() []*elasticsearch.Extension {
	return r.ListExtensionsResponse.Extensions
}

func (c extensionClient) Iterator(ctx context.Context, req *elasticsearch.ListExtensionsRequest, opts ...grpc.CallOption) *iterator.Iterator[*elasticsearch.ListExtensionsRequest, *elasticsearch.Extension] {
	return iterator.NewIterator[*elasticsearch.ListExtensionsRequest, *elasticsearch.Extension](ctx, req,
		func(ctx context.Context, req *elasticsearch.ListExtensionsRequest, opts ...grpc.CallOption) (iterator.PageResponse[*elasticsearch.Extension], error) {
			resp, err := c.List(ctx, req, opts...)
			if err != nil {
				return nil, err
			}
			return extensionServiceListInternal{resp}, nil
		})
}
