name: Build

on: [push]

defaults:
  run:
    working-directory: /go/src/github.com/yandex-cloud/go-sdk

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.15'
          cache: false
      - name: build
        run: go build
