name: Run tests

on:
  push:
    branches:
      - master
  pull_request:

defaults:
  run:
    working-directory: /go/src/github.com/yandex-cloud/go-sdk

jobs:
  tests:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.15'
          cache: false
      - name: run tests
        run: go test -v -race ./...
