// Code generated by sdkgen-v2. DO NOT EDIT.
package privatecasdk

import (
	"context"

	privateca "github.com/yandex-cloud/go-genproto/yandex/cloud/certificatemanager/v1/privateca"
	"github.com/yandex-cloud/go-sdk/v2/pkg/transport"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// PrivateCaContentClient provides methods for managing PrivateCaContent resources of Yandex.Cloud Privateca.
type PrivateCaContentClient interface {
	GetChain(context.Context, *privateca.GetCertificateAuthorityChainRequest, ...grpc.CallOption) (*privateca.GetCertificateAuthorityChainResponse, error)
	GetPrivateKey(context.Context, *privateca.GetCertificateAuthorityPrivateKeyRequest, ...grpc.CallOption) (*privateca.GetCertificateAuthorityPrivateKeyResponse, error)
}

var _ PrivateCaContentClient = privateCaContentClient{}

type privateCaContentClient struct {
	connector transport.Connector
}

// NewPrivateCaContentClient returns PrivateCaContentClient implementation.
func NewPrivateCaContentClient(connector transport.Connector) PrivateCaContentClient {
	return privateCaContentClient{connector}
}

// GetChain is an operation of Yandex.Cloud Privateca PrivateCaContent service.
func (c privateCaContentClient) GetChain(ctx context.Context, in *privateca.GetCertificateAuthorityChainRequest, opts ...grpc.CallOption) (*privateca.GetCertificateAuthorityChainResponse, error) {
	connection, err := c.connector.GetConnection(ctx, PrivateCaContentGetChain, opts...)
	if err != nil {
		return nil, err
	}
	return privateca.NewPrivateCaContentServiceClient(connection).GetChain(ctx, in, opts...)
}

// GetPrivateKey is an operation of Yandex.Cloud Privateca PrivateCaContent service.
func (c privateCaContentClient) GetPrivateKey(ctx context.Context, in *privateca.GetCertificateAuthorityPrivateKeyRequest, opts ...grpc.CallOption) (*privateca.GetCertificateAuthorityPrivateKeyResponse, error) {
	connection, err := c.connector.GetConnection(ctx, PrivateCaContentGetPrivateKey, opts...)
	if err != nil {
		return nil, err
	}
	return privateca.NewPrivateCaContentServiceClient(connection).GetPrivateKey(ctx, in, opts...)
}

var (
	PrivateCaContentGetChain      = protoreflect.FullName("yandex.cloud.certificatemanager.v1.privateca.PrivateCaContentService.GetChain")
	PrivateCaContentGetPrivateKey = protoreflect.FullName("yandex.cloud.certificatemanager.v1.privateca.PrivateCaContentService.GetPrivateKey")
)
