// Code generated by sdkgen-v2. DO NOT EDIT.
package privatecasdk

import (
	"github.com/yandex-cloud/go-sdk/v2/pkg/transport"
)

// Privateca provides access to components and services of Yandex.Cloud Privateca.
type Privateca struct {
	connector transport.Connector
}

// New creates an instance of Privateca.
func New(connector transport.Connector) Privateca {
	return Privateca{connector: connector}
}

// Policy provides access to the Policy service of Yandex.Cloud Privateca.
func (g Privateca) Policy() PolicyClient {
	return NewPolicyClient(g.connector)
}

// PrivateCaCertificateContent provides access to the PrivateCaCertificateContent service of Yandex.Cloud Privateca.
func (g Privateca) PrivateCaCertificateContent() PrivateCaCertificateContentClient {
	return NewPrivateCaCertificateContentClient(g.connector)
}

// PrivateCaCertificate provides access to the PrivateCaCertificate service of Yandex.Cloud Privateca.
func (g Privateca) PrivateCaCertificate() PrivateCaCertificateClient {
	return NewPrivateCaCertificateClient(g.connector)
}

// PrivateCaContent provides access to the PrivateCaContent service of Yandex.Cloud Privateca.
func (g Privateca) PrivateCaContent() PrivateCaContentClient {
	return NewPrivateCaContentClient(g.connector)
}

// PrivateCa provides access to the PrivateCa service of Yandex.Cloud Privateca.
func (g Privateca) PrivateCa() PrivateCaClient {
	return NewPrivateCaClient(g.connector)
}

// Template provides access to the Template service of Yandex.Cloud Privateca.
func (g Privateca) Template() TemplateClient {
	return NewTemplateClient(g.connector)
}
